"""2 · Al-Baqarah · The Cow · البقرة — 286 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–5 · The Book and the qualities of the muttaqin
    1: ["muqattaat", "revelation"],
    2: ["revelation", "hidayah", "taqwa"],
    3: ["iman", "salah", "zakat"],
    4: ["iman", "revelation", "akhirah"],
    5: ["hidayah", "iman", "glad_tidings"],
    # 6–7 · The disbelievers
    6: ["kufr", "hidayah"],
    7: ["kufr", "tazkiyah", "warnings"],
    # 8–20 · The hypocrites and their two parables
    8: ["nifaq"],
    9: ["nifaq"],
    10: ["nifaq", "tazkiyah", "sidq", "warnings"],
    11: ["nifaq", "environment"],
    12: ["nifaq", "environment"],
    13: ["nifaq", "kibr"],
    14: ["nifaq", "shaytan", "speech_ethics"],
    15: ["nifaq", "hidayah"],
    16: ["nifaq", "hidayah"],
    17: ["parables", "nifaq", "hidayah"],
    18: ["nifaq", "hidayah"],
    19: ["parables", "nifaq"],
    20: ["parables", "nifaq"],
    # 21–29 · Call to worship the Creator; the challenge of the Quran
    21: ["o_mankind", "tawheed", "commands", "purpose_of_life"],
    22: ["nature_signs", "tawheed", "shirk", "rizq"],
    23: ["revelation", "kufr"],
    24: ["jahannam", "warnings", "revelation"],
    25: ["jannah", "glad_tidings", "iman"],
    26: ["parables", "hidayah", "kufr"],
    27: ["amanah", "family", "environment"],
    28: ["resurrection", "death_reminder", "kufr"],
    29: ["nature_signs", "tawheed"],
    # 30–39 · Adam, the angels and Iblis
    30: ["story_adam", "angels", "purpose_of_life", "knowledge"],
    31: ["story_adam", "knowledge", "angels"],
    32: ["story_adam", "angels", "knowledge"],
    33: ["story_adam", "angels", "knowledge"],
    34: ["story_adam", "angels", "shaytan", "kibr"],
    35: ["story_adam", "jannah", "trial_test"],
    36: ["story_adam", "shaytan", "trial_test"],
    37: ["story_adam", "tawbah", "rahmah"],
    38: ["story_adam", "hidayah", "glad_tidings"],
    39: ["kufr", "jahannam", "warnings"],
    # 40–48 · Address to the Children of Israel
    40: ["story_bani_israil", "ahl_al_kitab", "shukr", "amanah", "taqwa"],
    41: ["ahl_al_kitab", "revelation", "taqwa", "dunya"],
    42: ["ahl_al_kitab", "sidq", "prohibitions"],
    43: ["salah", "zakat", "commands"],
    44: ["dawah", "ahl_al_kitab", "knowledge"],
    45: ["sabr", "salah", "commands"],
    46: ["iman", "akhirah"],
    47: ["story_bani_israil", "shukr"],
    48: ["akhirah", "taqwa", "warnings"],
    # 49–74 · Favours and failings of Bani Israil; the cow
    49: ["story_musa", "story_bani_israil", "oppression", "trial_test"],
    50: ["story_musa", "story_bani_israil", "miracles"],
    51: ["story_musa", "story_bani_israil", "shirk"],
    52: ["story_bani_israil", "rahmah", "shukr"],
    53: ["story_musa", "revelation", "hidayah"],
    54: ["story_musa", "story_bani_israil", "tawbah", "shirk"],
    55: ["story_bani_israil", "story_musa", "kufr"],
    56: ["story_bani_israil", "resurrection", "shukr"],
    57: ["story_bani_israil", "rizq", "miracles"],
    58: ["story_bani_israil", "tawbah", "kibr"],
    59: ["story_bani_israil", "history_lessons"],
    60: ["story_musa", "story_bani_israil", "miracles", "environment"],
    61: ["story_bani_israil", "shukr", "kufr", "history_lessons"],
    62: ["ahl_al_kitab", "iman", "glad_tidings"],
    63: ["story_bani_israil", "amanah", "revelation"],
    64: ["story_bani_israil", "rahmah"],
    65: ["story_bani_israil", "history_lessons", "warnings"],
    66: ["story_bani_israil", "history_lessons", "taqwa"],
    67: ["story_musa", "story_bani_israil", "speech_ethics"],
    68: ["story_bani_israil", "story_musa"],
    69: ["story_bani_israil", "story_musa"],
    70: ["story_bani_israil", "story_musa"],
    71: ["story_bani_israil", "story_musa"],
    72: ["story_bani_israil", "criminal_law"],
    73: ["story_bani_israil", "resurrection", "miracles"],
    74: ["tazkiyah", "story_bani_israil", "parables"],
    # 75–103 · The People of the Book in Madinah
    75: ["ahl_al_kitab", "revelation"],
    76: ["ahl_al_kitab", "nifaq"],
    77: ["ahl_al_kitab", "taqwa"],
    78: ["ahl_al_kitab", "knowledge"],
    79: ["ahl_al_kitab", "revelation", "sidq", "warnings"],
    80: ["ahl_al_kitab", "jahannam"],
    81: ["jahannam", "warnings"],
    82: ["jannah", "iman", "glad_tidings"],
    83: ["story_bani_israil", "parents", "family", "orphans", "social_justice", "speech_ethics", "commands"],
    84: ["story_bani_israil", "amanah", "community"],
    85: ["ahl_al_kitab", "community", "revelation", "warnings"],
    86: ["dunya", "akhirah", "warnings"],
    87: ["prophethood", "story_bani_israil", "story_isa", "kibr"],
    88: ["ahl_al_kitab", "kufr", "tazkiyah"],
    89: ["ahl_al_kitab", "kufr", "revelation"],
    90: ["ahl_al_kitab", "hasad", "kufr"],
    91: ["ahl_al_kitab", "revelation", "kufr", "prophethood"],
    92: ["story_bani_israil", "story_musa", "shirk"],
    93: ["story_bani_israil", "amanah", "shirk", "kufr"],
    94: ["ahl_al_kitab", "death_reminder", "akhirah"],
    95: ["ahl_al_kitab", "death_reminder"],
    96: ["ahl_al_kitab", "dunya", "death_reminder"],
    97: ["angels", "revelation", "ahl_al_kitab"],
    98: ["angels", "kufr", "prophethood"],
    99: ["revelation", "kufr"],
    100: ["ahl_al_kitab", "amanah", "kufr"],
    101: ["ahl_al_kitab", "revelation", "kufr"],
    102: ["shaytan", "story_sulayman", "angels", "ahl_al_kitab", "trial_test", "marriage"],
    103: ["iman", "taqwa", "glad_tidings"],
    # 104–121 · Manners with the Prophet; abrogation; claims of the People of the Book
    104: ["o_believers", "speech_ethics", "adab", "prohibitions"],
    105: ["ahl_al_kitab", "hasad", "rahmah"],
    106: ["revelation"],
    107: ["tawheed", "tawakkul"],
    108: ["adab", "kufr", "hidayah"],
    109: ["ahl_al_kitab", "hasad", "hilm", "commands"],
    110: ["salah", "zakat", "commands", "glad_tidings"],
    111: ["ahl_al_kitab", "jannah"],
    112: ["ikhlas", "ihsan", "glad_tidings"],
    113: ["ahl_al_kitab", "akhirah"],
    114: ["oppression", "kaaba", "warnings"],
    115: ["tawheed", "asma_ul_husna", "kaaba"],
    116: ["shirk", "tawheed"],
    117: ["asma_ul_husna", "nature_signs", "qadr"],
    118: ["kufr", "miracles"],
    119: ["prophethood", "story_muhammad", "dawah"],
    120: ["ahl_al_kitab", "hidayah", "wala_bara"],
    121: ["quran_recitation", "iman", "ahl_al_kitab"],
    122: ["story_bani_israil", "shukr"],
    123: ["akhirah", "taqwa", "warnings"],
    # 124–141 · Ibrahim, Ismail, the Kaaba and the religion of Ibrahim
    124: ["story_ibrahim", "trial_test", "leadership", "oppression"],
    125: ["kaaba", "story_ibrahim", "story_ismail", "salah", "hajj", "taharah"],
    126: ["story_ibrahim", "dua", "kaaba", "rizq"],
    127: ["story_ibrahim", "story_ismail", "kaaba", "dua"],
    128: ["story_ibrahim", "story_ismail", "dua", "hajj", "tawbah"],
    129: ["story_ibrahim", "dua", "story_muhammad", "knowledge", "tazkiyah"],
    130: ["story_ibrahim", "iman"],
    131: ["story_ibrahim", "iman"],
    132: ["story_yaqub", "story_ibrahim", "parenting", "iman", "death_reminder"],
    133: ["story_yaqub", "parenting", "tawheed", "death_reminder"],
    134: ["history_lessons", "akhirah"],
    135: ["story_ibrahim", "ahl_al_kitab", "tawheed"],
    136: ["iman", "prophethood", "revelation"],
    137: ["ahl_al_kitab", "hidayah", "tawakkul"],
    138: ["iman", "tawheed"],
    139: ["ahl_al_kitab", "ikhlas", "tawheed"],
    140: ["ahl_al_kitab", "story_ibrahim", "sidq"],
    141: ["history_lessons", "akhirah"],
    # 142–152 · The change of qiblah
    142: ["kaaba", "hidayah"],
    143: ["community", "adl", "kaaba", "trial_test", "hidayah"],
    144: ["kaaba", "salah", "commands", "story_muhammad"],
    145: ["kaaba", "ahl_al_kitab"],
    146: ["ahl_al_kitab", "story_muhammad", "sidq"],
    147: ["iman", "revelation"],
    148: ["ihsan", "commands", "akhirah"],
    149: ["kaaba", "salah", "commands"],
    150: ["kaaba", "salah", "commands", "taqwa"],
    151: ["story_muhammad", "revelation", "tazkiyah", "knowledge"],
    152: ["dhikr", "shukr", "commands"],
    # 153–157 · Patience, prayer and trials
    153: ["o_believers", "sabr", "salah", "commands", "anxiety_fear"],
    154: ["conflict", "death_reminder", "glad_tidings"],
    155: ["trial_test", "sabr", "glad_tidings", "grief_loss"],
    156: ["sabr", "grief_loss", "tawakkul", "akhirah"],
    157: ["sabr", "glad_tidings", "rahmah", "hidayah"],
    # 158–162 · Safa and Marwah; concealing the truth
    158: ["hajj", "kaaba", "ihsan"],
    159: ["revelation", "sidq", "ahl_al_kitab", "warnings"],
    160: ["tawbah", "rahmah"],
    161: ["kufr", "death_reminder", "warnings"],
    162: ["jahannam", "kufr", "warnings"],
    # 163–171 · Oneness, signs in creation, and blind following
    163: ["tawheed", "asma_ul_husna", "rahmah"],
    164: ["nature_signs", "tawheed", "knowledge"],
    165: ["shirk", "love_of_allah", "warnings"],
    166: ["akhirah", "leadership", "warnings"],
    167: ["akhirah", "jahannam", "leadership"],
    168: ["o_mankind", "food_halal", "shaytan", "commands"],
    169: ["shaytan", "knowledge"],
    170: ["hidayah", "kufr", "knowledge"],
    171: ["parables", "kufr"],
    # 172–176 · Lawful food; concealing the Book
    172: ["o_believers", "food_halal", "shukr", "commands"],
    173: ["food_halal", "prohibitions", "rahmah"],
    174: ["revelation", "dunya", "warnings", "ahl_al_kitab"],
    175: ["hidayah", "jahannam", "warnings"],
    176: ["revelation", "community"],
    # 177 · True righteousness (al-birr)
    177: ["taqwa", "iman", "zakat", "social_justice", "family", "sabr", "sidq"],
    # 178–182 · Retribution and bequests
    178: ["o_believers", "criminal_law", "hilm", "commands"],
    179: ["criminal_law", "taqwa"],
    180: ["inheritance", "parents", "family", "commands"],
    181: ["inheritance", "amanah"],
    182: ["inheritance", "adl"],
    # 183–187 · Fasting and Ramadan
    183: ["o_believers", "sawm", "taqwa", "commands"],
    184: ["sawm", "health", "commands"],
    185: ["sawm", "revelation", "commands", "hidayah", "dhikr", "shukr"],
    186: ["dua", "they_ask_you", "hope_raja", "iman", "hidayah"],
    187: ["sawm", "marriage", "commands", "taqwa"],
    # 188–189 · Wealth; new moons
    188: ["wealth", "prohibitions", "adl"],
    189: ["they_ask_you", "time", "hajj", "taqwa"],
    # 190–195 · Fighting in Allah's way and spending
    190: ["conflict", "commands", "love_of_allah"],
    191: ["conflict", "kaaba", "commands"],
    192: ["conflict", "rahmah"],
    193: ["conflict", "oppression", "commands"],
    194: ["conflict", "taqwa", "commands"],
    195: ["zakat", "ihsan", "love_of_allah", "commands", "prohibitions"],
    # 196–203 · Hajj
    196: ["hajj", "commands", "taqwa"],
    197: ["hajj", "taqwa", "commands", "prohibitions"],
    198: ["hajj", "dhikr", "trade", "hidayah"],
    199: ["hajj", "tawbah", "commands"],
    200: ["hajj", "dhikr", "dua", "dunya"],
    201: ["dua", "dunya", "akhirah"],
    202: ["akhirah", "glad_tidings"],
    203: ["hajj", "dhikr", "taqwa", "akhirah"],
    # 204–212 · The corrupter and the one who sells himself for Allah
    204: ["nifaq", "speech_ethics", "sidq"],
    205: ["nifaq", "environment", "love_of_allah"],
    206: ["kibr", "nifaq", "jahannam"],
    207: ["ikhlas", "sahabah"],
    208: ["o_believers", "iman", "shaytan", "commands"],
    209: ["hidayah", "warnings"],
    210: ["akhirah", "angels"],
    211: ["story_bani_israil", "shukr", "warnings"],
    212: ["dunya", "kufr", "taqwa", "rizq"],
    # 213–218 · One religion, trials before victory, spending and fighting
    213: ["prophethood", "revelation", "community", "hidayah", "hasad"],
    214: ["trial_test", "sabr", "jannah", "hope_raja"],
    215: ["they_ask_you", "zakat", "parents", "family", "orphans", "social_justice"],
    216: ["conflict", "trial_test", "tawakkul", "qadr"],
    217: ["they_ask_you", "conflict", "kaaba", "oppression", "kufr", "warnings"],
    218: ["hijrah", "iman", "conflict", "hope_raja"],
    # 219–221 · Wine and gambling, orphans, marrying polytheists
    219: ["they_ask_you", "food_halal", "wealth", "zakat", "prohibitions", "knowledge"],
    220: ["they_ask_you", "orphans", "ihsan"],
    221: ["marriage", "shirk", "prohibitions", "iman"],
    # 222–242 · Marriage, oaths, divorce, nursing, widows
    222: ["they_ask_you", "taharah", "marriage", "tawbah", "love_of_allah", "commands"],
    223: ["marriage", "taqwa", "akhirah"],
    224: ["amanah", "ihsan", "community"],
    225: ["amanah", "ikhlas"],
    226: ["marriage", "divorce", "amanah"],
    227: ["divorce"],
    228: ["divorce", "women", "marriage", "commands"],
    229: ["divorce", "marriage", "women", "commands"],
    230: ["divorce", "marriage", "commands"],
    231: ["divorce", "women", "prohibitions", "taqwa"],
    232: ["divorce", "marriage", "women", "prohibitions"],
    233: ["parenting", "family", "women", "shura", "commands"],
    234: ["divorce", "women", "commands"],
    235: ["marriage", "women", "adab", "taqwa"],
    236: ["divorce", "women", "ihsan"],
    237: ["divorce", "women", "ihsan", "hilm"],
    238: ["salah", "commands"],
    239: ["salah", "conflict", "dhikr"],
    240: ["women", "inheritance", "commands"],
    241: ["divorce", "women", "taqwa"],
    242: ["knowledge"],
    # 243–245 · Fleeing death; a goodly loan
    243: ["death_reminder", "resurrection", "shukr", "history_lessons"],
    244: ["conflict", "commands"],
    245: ["zakat", "rizq", "glad_tidings"],
    # 246–252 · Talut, Jalut and Dawud
    246: ["story_bani_israil", "conflict", "leadership", "trial_test"],
    247: ["story_bani_israil", "leadership", "knowledge", "kibr"],
    248: ["story_bani_israil", "miracles", "angels", "anxiety_fear"],
    249: ["story_bani_israil", "trial_test", "sabr", "iman", "conflict"],
    250: ["story_bani_israil", "dua", "sabr", "conflict"],
    251: ["story_dawud", "story_bani_israil", "conflict", "environment"],
    252: ["revelation", "prophethood", "story_muhammad"],
    # 253–257 · Ranks of messengers, Ayat al-Kursi, no compulsion
    253: ["prophethood", "story_isa", "qadr"],
    254: ["o_believers", "zakat", "akhirah", "commands"],
    255: ["tawheed", "asma_ul_husna"],  # Ayat al-Kursi
    256: ["dawah", "tawheed", "iman", "hidayah"],  # La ikraha fid-deen
    257: ["wala_bara", "hidayah", "iman", "kufr"],
    # 258–260 · Three proofs of giving life
    258: ["story_ibrahim", "tawheed", "kibr", "leadership"],
    259: ["resurrection", "miracles", "iman"],
    260: ["story_ibrahim", "resurrection", "iman", "miracles"],
    # 261–274 · Spending in Allah's way and its parables
    261: ["zakat", "parables", "glad_tidings"],
    262: ["zakat", "ikhlas", "speech_ethics", "glad_tidings"],
    263: ["speech_ethics", "hilm", "zakat"],
    264: ["o_believers", "zakat", "ikhlas", "parables", "prohibitions"],
    265: ["zakat", "ikhlas", "parables", "glad_tidings"],
    266: ["parables", "zakat", "ikhlas"],
    267: ["o_believers", "zakat", "commands", "work_ethics"],
    268: ["shaytan", "wealth", "anxiety_fear", "hope_raja"],
    269: ["knowledge", "qadr"],
    270: ["zakat", "amanah"],
    271: ["zakat", "ikhlas", "social_justice"],
    272: ["hidayah", "zakat", "ikhlas"],
    273: ["social_justice", "zakat", "haya"],
    274: ["zakat", "glad_tidings"],
    # 275–281 · Riba and easing the debtor
    275: ["riba", "trade", "prohibitions", "debt", "jahannam"],
    276: ["riba", "zakat", "wealth"],
    277: ["iman", "salah", "zakat", "glad_tidings"],
    278: ["o_believers", "riba", "taqwa", "commands"],
    279: ["riba", "warnings", "tawbah", "adl"],
    280: ["debt", "ihsan", "zakat"],
    281: ["akhirah", "taqwa", "adl"],
    # 282–283 · Recording debts and trusts
    282: ["o_believers", "debt", "trade", "commands", "sidq", "adl"],
    283: ["debt", "amanah", "sidq", "taqwa"],
    # 284–286 · Accountability, the believers' creed and closing dua
    284: ["akhirah", "tawheed", "tazkiyah"],
    285: ["iman", "angels", "revelation", "prophethood", "dua"],
    286: ["dua", "trial_test", "tawakkul", "rahmah"],  # La yukallifullahu nafsan
}
