"""3 · Ali 'Imran · Family of Imran · آل عمران — 200 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–6 · The Ever-Living revealed the Book
    1: ["muqattaat"],
    2: ["tawheed", "asma_ul_husna"],
    3: ["revelation"],
    4: ["revelation", "hidayah", "kufr", "warnings"],
    5: ["asma_ul_husna", "taqwa"],
    6: ["human_creation", "tawheed", "asma_ul_husna"],
    # 7–9 · Precise and unspecific verses; the dua of the firm in knowledge
    7: ["revelation", "knowledge", "iman", "tazkiyah"],
    8: ["dua", "hidayah", "tazkiyah", "rahmah"],
    9: ["dua", "akhirah"],
    # 10–17 · Worldly allure vs. what is with Allah
    10: ["kufr", "dunya", "jahannam"],
    11: ["history_lessons", "kufr", "warnings"],
    12: ["kufr", "jahannam", "warnings"],
    13: ["battle_badr", "conflict", "tawakkul"],
    14: ["dunya", "wealth", "trial_test"],
    15: ["jannah", "taqwa", "glad_tidings"],
    16: ["dua", "iman", "tawbah"],
    17: ["sabr", "sidq", "taqwa", "zakat", "tawbah", "dhikr"],
    # 18–32 · The religion with Allah; disputes with the People of the Book
    18: ["tawheed", "angels", "knowledge", "adl", "asma_ul_husna"],
    19: ["iman", "ahl_al_kitab", "hasad"],
    20: ["dawah", "ahl_al_kitab", "iman", "hidayah"],
    21: ["kufr", "oppression", "prophethood", "warnings"],
    22: ["kufr", "warnings"],
    23: ["ahl_al_kitab", "revelation", "kufr"],
    24: ["ahl_al_kitab", "jahannam"],
    25: ["akhirah", "adl"],
    26: ["asma_ul_husna", "tawheed", "leadership", "qadr", "dua"],
    27: ["nature_signs", "rizq", "tawheed", "asma_ul_husna"],
    28: ["wala_bara", "iman", "taqwa", "prohibitions"],
    29: ["taqwa", "asma_ul_husna"],
    30: ["akhirah", "warnings", "rahmah"],
    31: ["love_of_allah", "story_muhammad", "rahmah", "commands"],
    32: ["story_muhammad", "commands", "kufr", "love_of_allah"],
    # 33–44 · The family of Imran, Maryam and Zakariya
    33: ["prophethood", "story_maryam", "family"],
    34: ["prophethood", "family"],
    35: ["story_maryam", "dua", "parenting"],
    36: ["story_maryam", "women", "dua", "shaytan"],
    37: ["story_maryam", "story_zakariya", "rizq", "miracles"],
    38: ["story_zakariya", "dua", "parenting"],
    39: ["story_zakariya", "story_yahya", "angels", "glad_tidings"],
    40: ["story_zakariya", "miracles", "qadr"],
    41: ["story_zakariya", "dhikr", "miracles"],
    42: ["story_maryam", "women", "angels"],
    43: ["story_maryam", "salah"],
    44: ["story_maryam", "revelation"],
    # 45–63 · Isa — his birth, miracles, disciples and raising
    45: ["story_isa", "story_maryam", "angels", "glad_tidings"],
    46: ["story_isa", "miracles"],
    47: ["story_maryam", "story_isa", "miracles", "qadr"],
    48: ["story_isa", "revelation", "knowledge"],
    49: ["story_isa", "miracles", "story_bani_israil"],
    50: ["story_isa", "revelation", "taqwa"],
    51: ["story_isa", "tawheed", "hidayah"],
    52: ["story_isa", "dawah", "iman"],
    53: ["story_isa", "dua", "iman"],
    54: ["story_isa", "qadr"],
    55: ["story_isa", "miracles", "akhirah"],
    56: ["kufr", "warnings"],
    57: ["iman", "glad_tidings", "love_of_allah"],
    58: ["revelation"],
    59: ["story_isa", "story_adam", "human_creation", "parables"],
    60: ["iman", "revelation"],
    61: ["ahl_al_kitab", "story_isa", "sidq", "prophets_household"],
    62: ["tawheed", "story_isa"],
    63: ["ahl_al_kitab"],
    # 64–80 · A common word; arguments about Ibrahim; trusts
    64: ["ahl_al_kitab", "tawheed", "shirk", "dawah"],
    65: ["ahl_al_kitab", "story_ibrahim", "knowledge"],
    66: ["ahl_al_kitab", "knowledge"],
    67: ["story_ibrahim", "ahl_al_kitab", "tawheed"],
    68: ["story_ibrahim", "wala_bara", "iman"],
    69: ["ahl_al_kitab", "hidayah"],
    70: ["ahl_al_kitab", "kufr", "revelation"],
    71: ["ahl_al_kitab", "sidq"],
    72: ["ahl_al_kitab", "nifaq"],
    73: ["ahl_al_kitab", "hidayah", "hasad", "qadr"],
    74: ["rahmah", "qadr"],
    75: ["amanah", "ahl_al_kitab", "sidq"],
    76: ["amanah", "taqwa", "love_of_allah"],
    77: ["amanah", "dunya", "akhirah", "warnings"],
    78: ["ahl_al_kitab", "revelation", "sidq"],
    79: ["prophethood", "tawheed", "knowledge"],
    80: ["prophethood", "shirk", "angels"],
    # 81–91 · The covenant of the prophets; Islam as the religion
    81: ["prophethood", "amanah"],
    82: ["kufr", "amanah"],
    83: ["tawheed", "iman"],
    84: ["iman", "prophethood", "revelation"],
    85: ["iman", "warnings"],
    86: ["hidayah", "kufr"],
    87: ["kufr", "warnings"],
    88: ["jahannam", "kufr"],
    89: ["tawbah", "rahmah"],
    90: ["kufr", "tawbah", "hidayah"],
    91: ["kufr", "death_reminder", "jahannam", "warnings"],
    # 92–101 · Spending what you love; the House in Makkah
    92: ["zakat", "taqwa", "wealth", "commands"],
    93: ["food_halal", "ahl_al_kitab", "story_yaqub"],
    94: ["sidq", "warnings"],
    95: ["story_ibrahim", "tawheed", "commands"],
    96: ["kaaba", "hidayah"],
    97: ["hajj", "kaaba", "commands", "story_ibrahim"],
    98: ["ahl_al_kitab", "kufr"],
    99: ["ahl_al_kitab", "hidayah"],
    100: ["o_believers", "ahl_al_kitab", "iman", "warnings"],
    101: ["hidayah", "iman", "tawakkul"],
    # 102–112 · Hold fast to the rope of Allah; the best nation
    102: ["o_believers", "taqwa", "commands", "death_reminder"],
    103: ["community", "commands", "shukr", "prohibitions"],
    104: ["dawah", "community", "commands"],
    105: ["community", "prohibitions", "warnings"],
    106: ["akhirah", "kufr"],
    107: ["jannah", "rahmah"],
    108: ["revelation", "adl"],
    109: ["tawheed", "akhirah"],
    110: ["community", "dawah", "iman", "ahl_al_kitab", "commands"],
    111: ["ahl_al_kitab", "conflict"],
    112: ["ahl_al_kitab", "kufr", "warnings"],
    # 113–120 · The upright among them; not taking enemies as intimates
    113: ["ahl_al_kitab", "quran_recitation", "salah", "iman"],
    114: ["ahl_al_kitab", "iman", "dawah", "ihsan"],
    115: ["ihsan", "glad_tidings"],
    116: ["kufr", "dunya", "jahannam"],
    117: ["parables", "kufr", "wealth"],
    118: ["o_believers", "wala_bara", "prohibitions"],
    119: ["wala_bara", "nifaq"],
    120: ["sabr", "taqwa", "hasad", "wala_bara"],
    # 121–129 · Uhud begins; remembering the help at Badr
    121: ["battle_uhud", "conflict"],
    122: ["battle_uhud", "tawakkul"],
    123: ["battle_badr", "shukr", "taqwa"],
    124: ["battle_badr", "angels"],
    125: ["battle_badr", "angels", "sabr", "taqwa"],
    126: ["battle_badr", "angels", "tawakkul", "anxiety_fear"],
    127: ["battle_badr", "conflict"],
    128: ["battle_uhud", "qadr", "story_muhammad"],
    129: ["tawheed", "rahmah", "qadr"],
    # 130–138 · Riba, obedience, and the qualities of the muttaqin
    130: ["o_believers", "riba", "prohibitions", "debt", "taqwa"],
    131: ["jahannam", "taqwa", "kufr"],
    132: ["commands", "story_muhammad", "rahmah"],
    133: ["tawbah", "jannah", "taqwa", "commands"],
    134: ["hilm", "zakat", "ihsan", "love_of_allah"],
    135: ["tawbah", "dhikr", "taqwa", "glad_tidings"],
    136: ["jannah", "tawbah", "glad_tidings"],
    137: ["history_lessons", "kufr"],
    138: ["revelation", "hidayah", "taqwa"],
    # 139–175 · Lessons of Uhud
    139: ["battle_uhud", "sabr", "grief_loss", "iman", "tawakkul"],
    140: ["battle_uhud", "trial_test", "conflict"],
    141: ["battle_uhud", "trial_test", "tazkiyah"],
    142: ["battle_uhud", "jannah", "trial_test", "sabr"],
    143: ["battle_uhud", "conflict", "death_reminder"],
    144: ["battle_uhud", "story_muhammad", "prophethood", "death_reminder", "shukr"],
    145: ["death_reminder", "qadr", "dunya", "akhirah"],
    146: ["prophethood", "sabr", "conflict", "love_of_allah"],
    147: ["dua", "tawbah", "sabr"],
    148: ["glad_tidings", "ihsan", "love_of_allah"],
    149: ["o_believers", "wala_bara", "warnings"],
    150: ["wala_bara", "tawakkul"],
    151: ["shirk", "jahannam", "conflict"],
    152: ["battle_uhud", "dunya", "trial_test", "rahmah"],
    153: ["battle_uhud", "grief_loss", "trial_test"],
    154: ["battle_uhud", "anxiety_fear", "qadr", "nifaq", "tazkiyah", "death_reminder"],
    155: ["battle_uhud", "shaytan", "rahmah"],
    156: ["o_believers", "death_reminder", "qadr", "kufr"],
    157: ["conflict", "death_reminder", "rahmah", "dunya"],
    158: ["death_reminder", "akhirah"],
    159: ["hilm", "shura", "tawakkul", "leadership", "story_muhammad", "love_of_allah"],
    160: ["tawakkul", "tawheed"],
    161: ["amanah", "prophethood", "akhirah"],
    162: ["akhirah", "jahannam"],
    163: ["akhirah", "adl"],
    164: ["story_muhammad", "revelation", "tazkiyah", "knowledge", "shukr"],
    165: ["battle_uhud", "trial_test"],
    166: ["battle_uhud", "trial_test", "iman"],
    167: ["battle_uhud", "nifaq", "conflict"],
    168: ["battle_uhud", "nifaq", "death_reminder"],
    169: ["conflict", "death_reminder", "glad_tidings", "battle_uhud"],
    170: ["death_reminder", "glad_tidings"],
    171: ["glad_tidings", "iman"],
    172: ["battle_uhud", "sabr", "ihsan", "glad_tidings"],
    173: ["tawakkul", "iman", "anxiety_fear", "battle_uhud", "tawheed"],
    174: ["battle_uhud", "tawakkul", "glad_tidings"],
    175: ["shaytan", "anxiety_fear", "taqwa", "iman"],
    # 176–189 · Respite for disbelievers, withholding, and tests
    176: ["kufr", "story_muhammad", "warnings"],
    177: ["kufr", "warnings"],
    178: ["kufr", "trial_test", "warnings"],
    179: ["trial_test", "iman", "prophethood"],
    180: ["wealth", "zakat", "warnings"],
    181: ["ahl_al_kitab", "kufr", "jahannam"],
    182: ["adl", "akhirah"],
    183: ["ahl_al_kitab", "prophethood", "miracles"],
    184: ["prophethood", "story_muhammad", "revelation"],
    185: ["death_reminder", "akhirah", "dunya", "jannah"],
    186: ["trial_test", "sabr", "taqwa"],
    187: ["ahl_al_kitab", "amanah", "revelation", "dunya"],
    188: ["ikhlas", "warnings"],
    189: ["tawheed"],
    # 190–200 · Those of understanding: reflection, dua and its answer
    190: ["nature_signs", "knowledge", "tawheed"],
    191: ["dhikr", "nature_signs", "purpose_of_life", "dua", "tawheed"],
    192: ["dua", "jahannam"],
    193: ["dua", "iman", "tawbah", "death_reminder"],
    194: ["dua", "akhirah"],
    195: ["women", "hijrah", "conflict", "jannah", "glad_tidings", "dua"],
    196: ["kufr", "dunya"],
    197: ["dunya", "jahannam"],
    198: ["jannah", "taqwa", "glad_tidings"],
    199: ["ahl_al_kitab", "iman", "glad_tidings"],
    200: ["o_believers", "sabr", "taqwa", "commands"],
}
