"""4 · An-Nisa · The Women · النساء — 176 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · One soul; rights of orphans and women
    1: ["o_mankind", "human_creation", "family", "taqwa", "commands", "tawheed"],
    2: ["orphans", "wealth", "prohibitions", "commands"],
    3: ["marriage", "adl", "orphans", "women", "commands"],
    4: ["marriage", "women", "commands"],
    5: ["wealth", "speech_ethics", "commands"],
    6: ["orphans", "wealth", "amanah", "commands"],
    7: ["inheritance", "women", "family"],
    8: ["inheritance", "orphans", "social_justice", "speech_ethics"],
    9: ["orphans", "taqwa", "adl", "speech_ethics"],
    10: ["orphans", "jahannam", "warnings"],
    # 11–14 · Shares of inheritance
    11: ["inheritance", "commands", "family"],
    12: ["inheritance", "commands", "marriage"],
    13: ["inheritance", "jannah", "glad_tidings"],
    14: ["jahannam", "warnings", "inheritance"],
    # 15–18 · Immorality and the conditions of repentance
    15: ["criminal_law", "haya", "women"],
    16: ["criminal_law", "haya", "tawbah"],
    17: ["tawbah", "rahmah"],
    18: ["tawbah", "death_reminder", "kufr", "warnings"],
    # 19–28 · Treating wives with kindness; whom one may marry
    19: ["o_believers", "marriage", "women", "adl", "ihsan", "commands"],
    20: ["marriage", "divorce", "women", "prohibitions"],
    21: ["marriage", "amanah"],
    22: ["marriage", "prohibitions", "family"],
    23: ["marriage", "prohibitions", "family"],
    24: ["marriage", "haya", "prohibitions", "commands"],
    25: ["marriage", "haya", "criminal_law", "sabr"],
    26: ["hidayah", "tawbah", "knowledge"],
    27: ["tawbah", "tazkiyah"],
    28: ["rahmah", "human_creation"],
    # 29–35 · Wealth, major sins, envy, and marital discord
    29: ["o_believers", "trade", "wealth", "prohibitions", "commands"],
    30: ["oppression", "jahannam", "warnings"],
    31: ["prohibitions", "rahmah", "glad_tidings"],
    32: ["hasad", "women", "dua", "work_ethics"],
    33: ["inheritance", "amanah"],
    34: ["marriage", "women", "family"],
    35: ["marriage", "family", "adl"],
    # 36–42 · Excellence to people; stinginess and showing off
    36: ["tawheed", "parents", "family", "orphans", "social_justice", "kibr", "commands"],
    37: ["wealth", "zakat", "warnings"],
    38: ["ikhlas", "zakat", "shaytan"],
    39: ["iman", "zakat"],
    40: ["adl", "glad_tidings", "rahmah"],
    41: ["akhirah", "story_muhammad", "prophethood"],
    42: ["akhirah", "kufr"],
    # 43 · Prayer, intoxication and tayammum
    43: ["o_believers", "salah", "taharah", "food_halal", "prohibitions"],
    # 44–57 · Some of the People of the Book; shirk unforgiven
    44: ["ahl_al_kitab", "hidayah"],
    45: ["wala_bara", "tawakkul"],
    46: ["ahl_al_kitab", "speech_ethics", "revelation", "kufr"],
    47: ["ahl_al_kitab", "revelation", "warnings"],
    48: ["shirk", "rahmah", "warnings"],
    49: ["tazkiyah", "kibr"],
    50: ["sidq", "ahl_al_kitab"],
    51: ["ahl_al_kitab", "shirk", "hidayah"],
    52: ["ahl_al_kitab", "kufr"],
    53: ["ahl_al_kitab", "wealth"],
    54: ["hasad", "story_ibrahim", "ahl_al_kitab"],
    55: ["jahannam", "iman", "kufr"],
    56: ["jahannam", "kufr", "warnings"],
    57: ["jannah", "iman", "glad_tidings"],
    # 58–70 · Trusts, justice and obeying Allah and the Messenger
    58: ["amanah", "adl", "leadership", "commands"],
    59: ["o_believers", "leadership", "commands", "shura", "story_muhammad"],
    60: ["nifaq", "shaytan", "hidayah"],
    61: ["nifaq", "revelation"],
    62: ["nifaq", "sidq"],
    63: ["nifaq", "dawah", "speech_ethics"],
    64: ["tawbah", "prophethood", "story_muhammad", "rahmah"],
    65: ["iman", "story_muhammad"],
    66: ["iman", "trial_test"],
    67: ["glad_tidings"],
    68: ["hidayah"],
    69: ["jannah", "prophethood", "glad_tidings"],
    70: ["rahmah"],
    # 71–91 · Fighting for the oppressed; those who hang back
    71: ["o_believers", "conflict", "commands"],
    72: ["nifaq", "conflict"],
    73: ["nifaq", "dunya"],
    74: ["conflict", "dunya", "akhirah", "glad_tidings"],
    75: ["conflict", "oppression", "dua", "social_justice"],
    76: ["conflict", "shaytan"],
    77: ["conflict", "dunya", "akhirah", "taqwa", "anxiety_fear"],
    78: ["death_reminder", "qadr"],
    79: ["qadr", "prophethood"],
    80: ["story_muhammad", "iman"],
    81: ["nifaq", "tawakkul"],
    82: ["quran_recitation", "revelation", "knowledge"],
    83: ["speech_ethics", "leadership", "knowledge", "rahmah"],
    84: ["conflict", "story_muhammad"],
    85: ["community", "ihsan"],
    86: ["adab", "speech_ethics", "commands"],
    87: ["tawheed", "akhirah", "sidq"],
    88: ["nifaq", "hidayah"],
    89: ["nifaq", "wala_bara", "hijrah", "conflict"],
    90: ["conflict", "amanah"],
    91: ["conflict", "nifaq"],
    # 92–96 · Killing a believer; those who strive
    92: ["criminal_law", "social_justice", "sawm", "commands"],
    93: ["criminal_law", "jahannam", "warnings"],
    94: ["o_believers", "conflict", "iman", "dunya"],
    95: ["conflict", "wealth", "glad_tidings"],
    96: ["rahmah", "glad_tidings"],
    # 97–100 · Emigration for the sake of Allah
    97: ["hijrah", "angels", "death_reminder", "oppression", "jahannam"],
    98: ["hijrah", "oppression"],
    99: ["rahmah", "hijrah"],
    100: ["hijrah", "rizq", "death_reminder", "glad_tidings"],
    # 101–104 · Prayer while travelling and in fear
    101: ["salah", "conflict"],
    102: ["salah", "conflict", "commands"],
    103: ["salah", "dhikr", "time", "commands"],
    104: ["conflict", "sabr", "hope_raja"],
    # 105–115 · Judging justly; defending the deceitful; secret talk
    105: ["revelation", "adl", "story_muhammad"],
    106: ["tawbah", "rahmah"],
    107: ["adl", "love_of_allah", "sidq"],
    108: ["taqwa", "speech_ethics"],
    109: ["akhirah", "adl"],
    110: ["tawbah", "rahmah", "hope_raja"],
    111: ["adl", "akhirah"],
    112: ["speech_ethics", "sidq", "oppression"],
    113: ["story_muhammad", "revelation", "knowledge", "rahmah"],
    114: ["speech_ethics", "zakat", "community", "ikhlas", "glad_tidings"],
    115: ["story_muhammad", "community", "hidayah", "jahannam"],
    # 116–126 · Shirk and Shaytan's vow; the religion of Ibrahim
    116: ["shirk", "warnings", "hidayah"],
    117: ["shirk", "shaytan"],
    118: ["shaytan"],
    119: ["shaytan", "wala_bara"],
    120: ["shaytan"],
    121: ["jahannam"],
    122: ["jannah", "iman", "glad_tidings"],
    123: ["ahl_al_kitab", "adl", "akhirah"],
    124: ["women", "iman", "jannah", "glad_tidings"],
    125: ["story_ibrahim", "ikhlas", "ihsan", "love_of_allah"],
    126: ["tawheed"],
    # 127–134 · Rulings on women, reconciliation and fairness between wives
    127: ["they_ask_you", "women", "orphans", "marriage", "adl"],
    128: ["marriage", "women", "ihsan", "taqwa"],
    129: ["marriage", "adl", "women"],
    130: ["divorce", "rizq"],
    131: ["taqwa", "tawheed"],
    132: ["tawheed", "tawakkul"],
    133: ["o_mankind", "qadr", "warnings"],
    134: ["dunya", "akhirah"],
    # 135–152 · Standing firm for justice; the hypocrites exposed
    135: ["o_believers", "adl", "sidq", "commands", "parents"],
    136: ["o_believers", "iman", "revelation", "angels", "commands"],
    137: ["kufr", "hidayah", "nifaq"],
    138: ["nifaq", "warnings"],
    139: ["nifaq", "wala_bara"],
    140: ["speech_ethics", "adab", "nifaq", "jahannam"],
    141: ["nifaq", "akhirah", "wala_bara"],
    142: ["nifaq", "salah", "ikhlas", "dhikr"],
    143: ["nifaq", "hidayah"],
    144: ["o_believers", "wala_bara", "prohibitions"],
    145: ["nifaq", "jahannam"],
    146: ["tawbah", "ikhlas", "iman", "glad_tidings"],
    147: ["shukr", "iman", "rahmah"],
    148: ["speech_ethics", "oppression", "love_of_allah"],
    149: ["hilm", "ihsan"],
    150: ["kufr", "prophethood"],
    151: ["kufr", "warnings"],
    152: ["iman", "prophethood", "glad_tidings"],
    # 153–162 · Bani Israil's covenant-breaking; Isa was not crucified
    153: ["ahl_al_kitab", "story_bani_israil", "story_musa", "shirk"],
    154: ["story_bani_israil", "amanah"],
    155: ["story_bani_israil", "amanah", "kufr", "tazkiyah"],
    156: ["story_bani_israil", "story_maryam", "speech_ethics", "kufr"],
    157: ["story_isa", "ahl_al_kitab", "miracles"],
    158: ["story_isa", "miracles"],
    159: ["story_isa", "ahl_al_kitab", "akhirah"],
    160: ["story_bani_israil", "food_halal", "oppression"],
    161: ["riba", "story_bani_israil", "wealth", "warnings"],
    162: ["ahl_al_kitab", "iman", "knowledge", "salah", "zakat", "glad_tidings"],
    # 163–176 · Revelation to all the prophets; the Messiah was a servant
    163: ["revelation", "prophethood"],
    164: ["prophethood", "story_musa"],
    165: ["prophethood", "adl"],
    166: ["revelation", "angels"],
    167: ["kufr", "hidayah"],
    168: ["kufr", "oppression", "hidayah"],
    169: ["jahannam"],
    170: ["o_mankind", "iman", "story_muhammad"],
    171: ["ahl_al_kitab", "story_isa", "tawheed", "shirk", "prohibitions"],
    172: ["story_isa", "angels", "kibr"],
    173: ["iman", "kibr", "glad_tidings", "warnings"],
    174: ["o_mankind", "revelation", "hidayah"],
    175: ["iman", "tawakkul", "hidayah", "rahmah"],
    176: ["they_ask_you", "inheritance", "family", "commands"],
}
