"""5 · Al-Ma'idah · The Table Spread · المائدة — 120 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–11 · Fulfil contracts; lawful food; wudu; justice even to enemies
    1: ["o_believers", "amanah", "food_halal", "hajj", "commands"],
    2: ["o_believers", "hajj", "community", "taqwa", "adl", "commands"],
    3: ["food_halal", "prohibitions", "revelation", "iman", "shirk"],
    4: ["they_ask_you", "food_halal", "animals", "dhikr"],
    5: ["food_halal", "marriage", "ahl_al_kitab", "haya"],
    6: ["o_believers", "taharah", "salah", "commands", "shukr"],
    7: ["amanah", "shukr", "taqwa"],
    8: ["o_believers", "adl", "taqwa", "commands"],
    9: ["iman", "glad_tidings"],
    10: ["kufr", "jahannam"],
    11: ["o_believers", "shukr", "tawakkul"],
    # 12–19 · Covenants of the Jews and Christians
    12: ["story_bani_israil", "amanah", "salah", "zakat", "glad_tidings"],
    13: ["story_bani_israil", "amanah", "tazkiyah", "hilm", "love_of_allah"],
    14: ["ahl_al_kitab", "amanah"],
    15: ["ahl_al_kitab", "story_muhammad", "revelation"],
    16: ["revelation", "hidayah"],
    17: ["shirk", "story_isa", "ahl_al_kitab", "tawheed"],
    18: ["ahl_al_kitab", "love_of_allah", "kibr"],
    19: ["ahl_al_kitab", "story_muhammad", "prophethood"],
    # 20–26 · Bani Israil refuse to enter the Holy Land
    20: ["story_musa", "story_bani_israil", "shukr"],
    21: ["story_musa", "story_bani_israil", "conflict"],
    22: ["story_musa", "story_bani_israil", "anxiety_fear"],
    23: ["story_musa", "story_bani_israil", "tawakkul", "iman"],
    24: ["story_bani_israil", "story_musa", "conflict"],
    25: ["story_musa", "story_harun", "dua"],
    26: ["story_bani_israil", "story_musa", "history_lessons"],
    # 27–34 · The two sons of Adam; the sanctity of life
    27: ["story_adam", "taqwa", "hasad"],
    28: ["story_adam", "hilm", "taqwa"],
    29: ["story_adam", "jahannam", "oppression"],
    30: ["story_adam", "criminal_law", "tazkiyah"],
    31: ["story_adam", "animals"],
    32: ["criminal_law", "story_bani_israil", "adl", "commands"],
    33: ["criminal_law", "environment", "warnings"],
    34: ["criminal_law", "tawbah"],
    # 35–40 · Seeking the means to Allah; theft
    35: ["o_believers", "taqwa", "conflict", "commands"],
    36: ["kufr", "akhirah", "warnings"],
    37: ["jahannam", "kufr"],
    38: ["criminal_law", "commands"],
    39: ["tawbah", "rahmah", "criminal_law"],
    40: ["tawheed", "qadr"],
    # 41–50 · Judging by what Allah revealed — Torah, Injil and Quran
    41: ["nifaq", "ahl_al_kitab", "story_muhammad", "tazkiyah"],
    42: ["ahl_al_kitab", "adl", "love_of_allah"],
    43: ["ahl_al_kitab", "revelation"],
    44: ["revelation", "ahl_al_kitab", "leadership", "adl"],
    45: ["criminal_law", "revelation", "hilm"],
    46: ["story_isa", "revelation", "hidayah"],
    47: ["ahl_al_kitab", "revelation", "leadership"],
    48: ["revelation", "commands", "community", "trial_test", "ihsan", "ahl_al_kitab"],
    49: ["revelation", "story_muhammad", "ahl_al_kitab", "leadership"],
    50: ["revelation", "leadership", "iman"],
    # 51–66 · Allies of the believers; mockers of the religion
    51: ["o_believers", "wala_bara", "ahl_al_kitab", "prohibitions"],
    52: ["nifaq", "wala_bara", "anxiety_fear"],
    53: ["nifaq", "iman"],
    54: ["o_believers", "love_of_allah", "iman", "kibr", "conflict"],
    55: ["wala_bara", "salah", "zakat"],
    56: ["wala_bara", "glad_tidings"],
    57: ["o_believers", "wala_bara", "ahl_al_kitab", "speech_ethics"],
    58: ["salah", "speech_ethics", "kufr"],
    59: ["ahl_al_kitab", "iman"],
    60: ["ahl_al_kitab", "history_lessons", "shirk"],
    61: ["nifaq", "ahl_al_kitab"],
    62: ["ahl_al_kitab", "oppression", "wealth"],
    63: ["dawah", "ahl_al_kitab", "knowledge"],
    64: ["ahl_al_kitab", "kufr", "asma_ul_husna", "environment", "conflict"],
    65: ["ahl_al_kitab", "iman", "taqwa", "jannah"],
    66: ["ahl_al_kitab", "revelation", "rizq"],
    # 67–86 · Convey the message; the Messiah was a messenger
    67: ["story_muhammad", "dawah", "revelation", "tawakkul"],
    68: ["ahl_al_kitab", "revelation"],
    69: ["ahl_al_kitab", "iman", "glad_tidings"],
    70: ["story_bani_israil", "amanah", "prophethood"],
    71: ["story_bani_israil", "hidayah", "tawbah"],
    72: ["shirk", "story_isa", "ahl_al_kitab", "jahannam"],
    73: ["shirk", "tawheed", "ahl_al_kitab", "warnings"],
    74: ["tawbah", "rahmah"],
    75: ["story_isa", "story_maryam", "prophethood", "tawheed"],
    76: ["shirk", "tawheed"],
    77: ["ahl_al_kitab", "hidayah", "prohibitions"],
    78: ["story_bani_israil", "kufr", "prophethood"],
    79: ["dawah", "story_bani_israil"],
    80: ["wala_bara", "ahl_al_kitab", "jahannam"],
    81: ["wala_bara", "iman", "ahl_al_kitab"],
    82: ["ahl_al_kitab", "kibr"],
    83: ["ahl_al_kitab", "quran_recitation", "iman", "dua"],
    84: ["iman", "ahl_al_kitab"],
    85: ["jannah", "ihsan", "glad_tidings"],
    86: ["kufr", "jahannam"],
    # 87–108 · Lawful things, oaths, intoxicants, ihram, testimony
    87: ["o_believers", "food_halal", "prohibitions", "love_of_allah"],
    88: ["food_halal", "rizq", "taqwa", "commands"],
    89: ["amanah", "social_justice", "sawm", "commands"],
    90: ["o_believers", "food_halal", "shaytan", "prohibitions", "commands"],
    91: ["shaytan", "food_halal", "dhikr", "salah"],
    92: ["story_muhammad", "commands", "dawah"],
    93: ["iman", "taqwa", "ihsan", "love_of_allah", "food_halal"],
    94: ["o_believers", "trial_test", "hajj", "taqwa"],
    95: ["o_believers", "hajj", "prohibitions", "kaaba"],
    96: ["hajj", "food_halal", "taqwa"],
    97: ["kaaba", "hajj"],
    98: ["rahmah", "warnings"],
    99: ["story_muhammad", "dawah", "taqwa"],
    100: ["taqwa", "knowledge"],
    101: ["o_believers", "adab", "prohibitions"],
    102: ["adab", "history_lessons"],
    103: ["shirk", "animals"],
    104: ["hidayah", "kufr", "knowledge"],
    105: ["o_believers", "hidayah", "akhirah"],
    106: ["o_believers", "inheritance", "death_reminder", "amanah", "sidq"],
    107: ["inheritance", "sidq", "amanah"],
    108: ["sidq", "taqwa"],
    # 109–120 · The Day the messengers are gathered; Isa and the table
    109: ["akhirah", "prophethood"],
    110: ["story_isa", "miracles", "akhirah"],
    111: ["story_isa", "iman"],
    112: ["story_isa", "miracles", "taqwa"],
    113: ["story_isa", "miracles", "iman"],
    114: ["story_isa", "dua", "rizq", "miracles"],
    115: ["story_isa", "miracles", "warnings"],
    116: ["story_isa", "shirk", "akhirah"],
    117: ["story_isa", "tawheed", "akhirah"],
    118: ["story_isa", "rahmah", "akhirah"],
    119: ["sidq", "jannah", "glad_tidings", "akhirah"],
    120: ["tawheed", "asma_ul_husna"],
}
