"""6 · Al-An'am · The Cattle · الأنعام — 165 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–11 · The Creator and those who deny His signs
    1: ["tawheed", "nature_signs", "shirk"],
    2: ["human_creation", "death_reminder", "resurrection"],
    3: ["tawheed", "taqwa"],
    4: ["kufr"],
    5: ["kufr", "warnings"],
    6: ["history_lessons", "warnings"],
    7: ["kufr", "revelation"],
    8: ["kufr", "angels", "prophethood"],
    9: ["prophethood", "angels"],
    10: ["prophethood", "history_lessons", "story_muhammad"],
    11: ["history_lessons"],
    # 12–32 · To whom belongs all; the Day the polytheists are questioned
    12: ["tawheed", "rahmah", "akhirah"],
    13: ["tawheed"],
    14: ["tawheed", "wala_bara", "rizq", "shirk"],
    15: ["akhirah", "taqwa"],
    16: ["akhirah", "rahmah"],
    17: ["qadr", "tawakkul", "trial_test"],
    18: ["asma_ul_husna", "tawheed"],
    19: ["tawheed", "shirk", "revelation", "dawah"],
    20: ["ahl_al_kitab", "story_muhammad", "kufr"],
    21: ["sidq", "kufr"],
    22: ["akhirah", "shirk"],
    23: ["akhirah", "shirk", "sidq"],
    24: ["akhirah", "sidq"],
    25: ["kufr", "tazkiyah", "revelation"],
    26: ["kufr"],
    27: ["akhirah", "jahannam", "kufr"],
    28: ["akhirah", "kufr"],
    29: ["resurrection", "kufr", "dunya"],
    30: ["akhirah", "kufr"],
    31: ["akhirah", "kufr", "warnings"],
    32: ["dunya", "akhirah", "taqwa"],
    # 33–41 · Consoling the Prophet; all creatures are communities
    33: ["story_muhammad", "grief_loss", "kufr"],
    34: ["prophethood", "sabr", "story_muhammad"],
    35: ["story_muhammad", "qadr", "hidayah", "miracles"],
    36: ["hidayah", "resurrection"],
    37: ["kufr", "miracles"],
    38: ["animals", "nature_signs", "resurrection"],
    39: ["kufr", "hidayah"],
    40: ["akhirah", "dua", "shirk"],
    41: ["dua", "shirk", "tawheed"],
    # 42–58 · Nations seized after ease; the Messenger's mandate
    42: ["history_lessons", "trial_test", "kibr"],
    43: ["tazkiyah", "shaytan", "history_lessons"],
    44: ["history_lessons", "trial_test", "dunya"],
    45: ["history_lessons"],
    46: ["tawheed", "shukr"],
    47: ["warnings", "oppression"],
    48: ["prophethood", "glad_tidings", "iman"],
    49: ["kufr", "warnings"],
    50: ["story_muhammad", "prophethood", "revelation", "knowledge"],
    51: ["dawah", "revelation", "akhirah", "taqwa"],
    52: ["dua", "ikhlas", "story_muhammad", "kibr"],
    53: ["trial_test", "shukr", "kibr"],
    54: ["tawbah", "rahmah", "hope_raja", "adab"],
    55: ["revelation"],
    56: ["shirk", "tawheed", "hidayah"],
    57: ["story_muhammad", "revelation"],
    58: ["qadr"],
    # 59–73 · Keys of the unseen; Allah alone rescues
    59: ["asma_ul_husna", "knowledge", "qadr", "tawheed"],
    60: ["death_reminder", "resurrection"],
    61: ["angels", "death_reminder"],
    62: ["akhirah"],
    63: ["dua", "anxiety_fear", "shukr"],
    64: ["shirk", "shukr"],
    65: ["warnings", "community", "qadr"],
    66: ["story_muhammad", "kufr"],
    67: ["akhirah", "warnings"],
    68: ["adab", "speech_ethics", "shaytan"],
    69: ["taqwa", "dawah"],
    70: ["dunya", "dawah", "jahannam", "kufr"],
    71: ["shirk", "hidayah", "shaytan"],
    72: ["salah", "taqwa", "akhirah", "commands"],
    73: ["nature_signs", "resurrection", "asma_ul_husna"],
    # 74–83 · Ibrahim reasons from the star, moon and sun
    74: ["story_ibrahim", "shirk", "parents"],
    75: ["story_ibrahim", "nature_signs", "iman"],
    76: ["story_ibrahim", "nature_signs", "tawheed"],
    77: ["story_ibrahim", "nature_signs", "hidayah"],
    78: ["story_ibrahim", "nature_signs", "shirk"],
    79: ["story_ibrahim", "tawheed", "ikhlas"],
    80: ["story_ibrahim", "tawakkul", "shirk"],
    81: ["story_ibrahim", "shirk", "anxiety_fear"],
    82: ["iman", "anxiety_fear", "hidayah"],
    83: ["story_ibrahim", "knowledge"],
    # 84–94 · The line of guided prophets; forging lies against Allah
    84: ["prophethood", "hidayah", "ihsan"],
    85: ["prophethood"],
    86: ["prophethood"],
    87: ["prophethood", "hidayah"],
    88: ["hidayah", "shirk"],
    89: ["prophethood", "revelation"],
    90: ["prophethood", "hidayah", "story_muhammad", "dawah", "ikhlas"],
    91: ["revelation", "story_musa", "ahl_al_kitab", "kufr"],
    92: ["revelation", "iman", "salah"],
    93: ["sidq", "death_reminder", "angels", "kibr", "jahannam"],
    94: ["akhirah", "shirk"],
    # 95–111 · Signs in grain, dawn, stars and rain; no son for Allah
    95: ["nature_signs", "tawheed"],
    96: ["nature_signs", "time"],
    97: ["nature_signs", "knowledge"],
    98: ["human_creation", "nature_signs"],
    99: ["nature_signs", "rizq", "iman"],
    100: ["shirk", "jinn", "tawheed"],
    101: ["tawheed", "shirk", "asma_ul_husna"],
    102: ["tawheed", "asma_ul_husna", "tawakkul"],
    103: ["tawheed", "asma_ul_husna"],
    104: ["hidayah", "revelation"],
    105: ["revelation", "kufr"],
    106: ["revelation", "tawheed", "commands"],
    107: ["qadr", "shirk", "story_muhammad"],
    108: ["speech_ethics", "dawah", "prohibitions", "shirk"],
    109: ["kufr", "miracles"],
    110: ["tazkiyah", "hidayah", "kufr"],
    111: ["kufr", "qadr", "angels"],
    # 112–127 · Devils of men and jinn; eating what Allah's name is on
    112: ["shaytan", "jinn", "prophethood", "speech_ethics"],
    113: ["kufr", "tazkiyah"],
    114: ["revelation", "ahl_al_kitab", "iman"],
    115: ["revelation", "adl"],
    116: ["hidayah", "knowledge"],
    117: ["hidayah"],
    118: ["food_halal", "dhikr", "commands"],
    119: ["food_halal", "knowledge"],
    120: ["tazkiyah", "prohibitions"],
    121: ["food_halal", "shaytan", "prohibitions", "shirk"],
    122: ["hidayah", "iman", "parables"],
    123: ["oppression", "leadership"],
    124: ["kufr", "kibr", "prophethood"],
    125: ["hidayah", "iman", "tazkiyah"],
    126: ["hidayah", "revelation"],
    127: ["jannah", "wala_bara", "glad_tidings"],
    # 128–135 · Jinn and men on the Day; degrees of deeds
    128: ["jinn", "akhirah", "jahannam", "wala_bara"],
    129: ["wala_bara", "oppression"],
    130: ["jinn", "prophethood", "akhirah", "dunya"],
    131: ["adl", "prophethood", "history_lessons"],
    132: ["akhirah", "adl"],
    133: ["rahmah", "qadr", "history_lessons"],
    134: ["akhirah", "warnings"],
    135: ["dawah", "warnings"],
    # 136–150 · Pagan rules on crops, cattle and children refuted
    136: ["shirk", "rizq"],
    137: ["shirk", "parenting", "oppression"],
    138: ["shirk", "food_halal", "animals"],
    139: ["shirk", "food_halal", "women"],
    140: ["parenting", "shirk", "knowledge"],
    141: ["nature_signs", "zakat", "rizq", "wealth", "love_of_allah"],
    142: ["animals", "food_halal", "shaytan", "rizq"],
    143: ["food_halal", "animals", "knowledge"],
    144: ["food_halal", "animals", "sidq"],
    145: ["food_halal", "prohibitions", "rahmah"],
    146: ["food_halal", "story_bani_israil", "oppression"],
    147: ["rahmah", "warnings"],
    148: ["shirk", "qadr", "knowledge"],
    149: ["qadr", "hidayah"],
    150: ["shirk", "sidq"],
    # 151–153 · The ten commandments of the straight path
    151: ["commands", "prohibitions", "shirk", "parents", "parenting", "haya", "criminal_law"],
    152: ["orphans", "trade", "adl", "amanah", "commands"],
    153: ["hidayah", "commands", "taqwa"],
    # 154–165 · The Torah and the Quran; my prayer and my death for Allah
    154: ["story_musa", "revelation", "hidayah", "rahmah"],
    155: ["revelation", "commands", "taqwa", "rahmah"],
    156: ["revelation", "ahl_al_kitab"],
    157: ["revelation", "hidayah", "warnings"],
    158: ["akhirah", "iman"],
    159: ["community", "warnings"],
    160: ["akhirah", "glad_tidings", "adl", "rahmah"],
    161: ["hidayah", "story_ibrahim", "tawheed"],
    162: ["ikhlas", "tawheed", "salah", "purpose_of_life", "commands"],
    163: ["tawheed", "iman"],
    164: ["tawheed", "akhirah", "adl"],
    165: ["purpose_of_life", "trial_test"],
}
