"""7 · Al-A'raf · The Heights · الأعراف — 206 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–9 · The Book, destroyed cities, and the scales
    1: ["muqattaat"],
    2: ["revelation", "story_muhammad", "dawah"],
    3: ["revelation", "wala_bara", "commands"],
    4: ["history_lessons", "warnings"],
    5: ["history_lessons"],
    6: ["akhirah", "prophethood"],
    7: ["akhirah"],
    8: ["akhirah", "glad_tidings"],
    9: ["akhirah", "warnings"],
    # 10–25 · Adam, Iblis's vow and the fall
    10: ["rizq", "shukr"],
    11: ["story_adam", "angels", "shaytan", "human_creation"],
    12: ["story_adam", "shaytan", "kibr"],
    13: ["story_adam", "shaytan", "kibr"],
    14: ["shaytan", "story_adam"],
    15: ["shaytan", "story_adam"],
    16: ["shaytan", "hidayah", "story_adam"],
    17: ["shaytan", "shukr", "story_adam"],
    18: ["shaytan", "jahannam", "story_adam"],
    19: ["story_adam", "jannah", "trial_test"],
    20: ["story_adam", "shaytan", "haya"],
    21: ["story_adam", "shaytan", "sidq"],
    22: ["story_adam", "shaytan", "haya"],
    23: ["story_adam", "dua", "tawbah", "rahmah"],
    24: ["story_adam", "dunya"],
    25: ["story_adam", "death_reminder", "resurrection"],
    # 26–36 · O children of Adam: clothing, adornment and Shaytan's temptation
    26: ["haya", "taqwa", "shukr"],
    27: ["shaytan", "story_adam", "haya", "wala_bara"],
    28: ["haya", "knowledge"],
    29: ["adl", "ikhlas", "salah", "resurrection", "commands"],
    30: ["hidayah", "shaytan", "wala_bara"],
    31: ["food_halal", "haya", "health", "commands", "love_of_allah"],
    32: ["food_halal", "rizq"],
    33: ["prohibitions", "haya", "oppression", "shirk", "knowledge"],
    34: ["qadr", "time", "history_lessons"],
    35: ["prophethood", "taqwa", "glad_tidings"],
    36: ["kibr", "kufr", "jahannam"],
    # 37–53 · The people of the Fire, of Paradise, and of the Heights
    37: ["sidq", "death_reminder", "angels", "shirk"],
    38: ["jahannam", "akhirah", "leadership"],
    39: ["jahannam", "akhirah"],
    40: ["kibr", "kufr", "jannah", "parables"],
    41: ["jahannam"],
    42: ["iman", "jannah", "glad_tidings"],
    43: ["jannah", "hidayah", "shukr"],
    44: ["jannah", "jahannam", "akhirah"],
    45: ["kufr", "akhirah"],
    46: ["akhirah", "jannah"],
    47: ["akhirah", "dua"],
    48: ["akhirah", "kibr"],
    49: ["akhirah", "jannah", "rahmah"],
    50: ["jahannam", "jannah"],
    51: ["dunya", "kufr", "akhirah"],
    52: ["revelation", "hidayah", "rahmah"],
    53: ["akhirah", "kufr"],
    # 54–58 · The Lord of the Throne; call on Him in humility; rain revives
    54: ["tawheed", "nature_signs", "asma_ul_husna"],
    55: ["dua", "love_of_allah", "commands"],
    56: ["environment", "dua", "rahmah", "ihsan", "commands"],
    57: ["nature_signs", "resurrection", "rahmah"],
    58: ["nature_signs", "parables", "shukr"],
    # 59–64 · Nuh
    59: ["story_nuh", "tawheed", "dawah"],
    60: ["story_nuh", "kibr"],
    61: ["story_nuh", "prophethood"],
    62: ["story_nuh", "dawah", "prophethood"],
    63: ["story_nuh", "prophethood", "taqwa"],
    64: ["story_nuh", "history_lessons"],
    # 65–72 · Hud and 'Ad
    65: ["story_hud", "tawheed", "dawah", "taqwa"],
    66: ["story_hud", "kibr", "kufr"],
    67: ["story_hud", "prophethood"],
    68: ["story_hud", "dawah", "amanah"],
    69: ["story_hud", "shukr", "prophethood"],
    70: ["story_hud", "shirk", "tawheed"],
    71: ["story_hud", "shirk"],
    72: ["story_hud", "history_lessons", "rahmah"],
    # 73–79 · Salih and Thamud
    73: ["story_salih", "tawheed", "miracles", "animals"],
    74: ["story_salih", "shukr", "environment"],
    75: ["story_salih", "kibr", "oppression", "iman"],
    76: ["story_salih", "kibr", "kufr"],
    77: ["story_salih", "kibr", "kufr"],
    78: ["story_salih", "history_lessons"],
    79: ["story_salih", "dawah"],
    # 80–84 · Lut
    80: ["story_lut", "haya"],
    81: ["story_lut", "haya"],
    82: ["story_lut", "haya"],
    83: ["story_lut", "family", "women"],
    84: ["story_lut", "history_lessons"],
    # 85–93 · Shu'ayb and Madyan
    85: ["story_shuayb", "tawheed", "trade", "environment"],
    86: ["story_shuayb", "oppression", "history_lessons"],
    87: ["story_shuayb", "sabr"],
    88: ["story_shuayb", "kibr", "oppression"],
    89: ["story_shuayb", "tawakkul", "dua"],
    90: ["story_shuayb", "kufr"],
    91: ["story_shuayb", "history_lessons"],
    92: ["story_shuayb", "history_lessons"],
    93: ["story_shuayb", "dawah", "grief_loss"],
    # 94–102 · The pattern of towns seized after ease
    94: ["history_lessons", "trial_test", "kibr"],
    95: ["history_lessons", "trial_test"],
    96: ["taqwa", "iman", "rizq", "glad_tidings", "history_lessons"],
    97: ["warnings", "history_lessons"],
    98: ["warnings", "history_lessons"],
    99: ["taqwa", "warnings"],
    100: ["tazkiyah", "warnings", "history_lessons"],
    101: ["history_lessons", "tazkiyah", "kufr"],
    102: ["amanah", "history_lessons"],
    # 103–137 · Musa, Pharaoh and the magicians
    103: ["story_musa", "oppression", "history_lessons"],
    104: ["story_musa", "prophethood"],
    105: ["story_musa", "story_bani_israil", "sidq"],
    106: ["story_musa", "miracles"],
    107: ["story_musa", "miracles"],
    108: ["story_musa", "miracles"],
    109: ["story_musa", "kufr"],
    110: ["story_musa"],
    111: ["story_musa"],
    112: ["story_musa"],
    113: ["story_musa", "dunya"],
    114: ["story_musa", "dunya"],
    115: ["story_musa"],
    116: ["story_musa", "shaytan"],
    117: ["story_musa", "miracles"],
    118: ["story_musa", "miracles"],
    119: ["story_musa", "kibr"],
    120: ["story_musa", "iman", "salah"],
    121: ["story_musa", "iman"],
    122: ["story_musa", "story_harun", "iman"],
    123: ["story_musa", "oppression"],
    124: ["story_musa", "oppression"],
    125: ["story_musa", "iman", "death_reminder"],
    126: ["story_musa", "dua", "sabr", "iman"],
    127: ["story_musa", "oppression", "story_bani_israil"],
    128: ["story_musa", "sabr", "tawakkul", "taqwa"],
    129: ["story_musa", "story_bani_israil", "hope_raja", "trial_test"],
    130: ["story_musa", "trial_test", "history_lessons"],
    131: ["story_musa", "shukr", "kufr"],
    132: ["story_musa", "kufr"],
    133: ["story_musa", "miracles", "history_lessons"],
    134: ["story_musa", "amanah"],
    135: ["story_musa", "amanah"],
    136: ["story_musa", "history_lessons"],
    137: ["story_bani_israil", "story_musa", "sabr", "oppression"],
    # 138–156 · The calf, the tablets and the seventy
    138: ["story_bani_israil", "story_musa", "shirk"],
    139: ["story_bani_israil", "shirk"],
    140: ["story_musa", "tawheed", "shukr"],
    141: ["story_bani_israil", "oppression", "trial_test"],
    142: ["story_musa", "story_harun", "leadership"],
    143: ["story_musa", "tawbah", "iman", "miracles"],
    144: ["story_musa", "revelation", "shukr"],
    145: ["story_musa", "revelation"],
    146: ["kibr", "hidayah", "kufr"],
    147: ["kufr", "akhirah"],
    148: ["story_bani_israil", "shirk", "story_musa"],
    149: ["story_bani_israil", "tawbah", "dua"],
    150: ["story_musa", "story_harun", "grief_loss", "family"],
    151: ["story_musa", "dua", "rahmah"],
    152: ["story_bani_israil", "shirk", "warnings"],
    153: ["tawbah", "rahmah", "iman"],
    154: ["story_musa", "revelation", "hidayah", "taqwa"],
    155: ["story_musa", "dua", "trial_test", "tawbah"],
    156: ["rahmah", "dua", "tawbah", "hope_raja", "zakat", "taqwa"],
    # 157–158 · The unlettered Prophet foretold in the Torah and Injil
    157: ["story_muhammad", "revelation", "ahl_al_kitab", "dawah", "food_halal"],
    158: ["o_mankind", "story_muhammad", "iman", "hidayah"],
    # 159–171 · Bani Israil: springs, the gate, the Sabbath town
    159: ["story_bani_israil", "hidayah", "adl"],
    160: ["story_bani_israil", "story_musa", "miracles", "rizq"],
    161: ["story_bani_israil", "tawbah", "kibr"],
    162: ["story_bani_israil", "history_lessons"],
    163: ["story_bani_israil", "trial_test"],
    164: ["story_bani_israil", "dawah", "taqwa"],
    165: ["story_bani_israil", "dawah", "history_lessons"],
    166: ["story_bani_israil", "history_lessons"],
    167: ["story_bani_israil", "warnings", "rahmah"],
    168: ["story_bani_israil", "trial_test", "tawbah"],
    169: ["story_bani_israil", "dunya", "revelation", "amanah"],
    170: ["revelation", "salah", "glad_tidings"],
    171: ["story_bani_israil", "revelation", "taqwa"],
    # 172–186 · The primordial covenant; the one who cast off the signs
    172: ["tawheed", "human_creation", "amanah"],
    173: ["shirk", "akhirah"],
    174: ["revelation", "tawbah"],
    175: ["knowledge", "shaytan", "hidayah"],
    176: ["parables", "tazkiyah", "dunya"],
    177: ["parables", "kufr"],
    178: ["hidayah"],
    179: ["jahannam", "tazkiyah", "dunya"],
    180: ["asma_ul_husna", "dua", "dhikr", "commands"],
    181: ["hidayah", "adl", "community"],
    182: ["kufr", "warnings"],
    183: ["warnings", "qadr"],
    184: ["story_muhammad", "knowledge"],
    185: ["nature_signs", "death_reminder", "knowledge"],
    186: ["hidayah"],
    # 187–198 · The Hour; the helplessness of false gods
    187: ["they_ask_you", "akhirah", "knowledge"],
    188: ["story_muhammad", "qadr", "knowledge", "prophethood"],
    189: ["human_creation", "marriage", "parenting", "dua"],
    190: ["shirk", "parenting"],
    191: ["shirk"],
    192: ["shirk"],
    193: ["dawah", "hidayah"],
    194: ["shirk"],
    195: ["shirk", "tawakkul"],
    196: ["wala_bara", "tawakkul", "revelation"],
    197: ["shirk"],
    198: ["shirk", "hidayah"],
    # 199–206 · Forgive, seek refuge, listen to the Quran, remember Allah
    199: ["hilm", "dawah", "adab", "commands"],
    200: ["shaytan", "dhikr", "commands"],
    201: ["taqwa", "shaytan", "dhikr"],
    202: ["shaytan", "hidayah"],
    203: ["revelation", "story_muhammad", "miracles", "hidayah"],
    204: ["quran_recitation", "commands", "rahmah"],
    205: ["dhikr", "commands", "dunya"],
    206: ["sajdah_tilawah", "angels", "kibr", "salah"],
}
