"""8 · Al-Anfal · The Spoils of War · الأنفال — 75 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–4 · Spoils belong to Allah; the qualities of true believers
    1: ["they_ask_you", "battle_badr", "taqwa", "community", "commands"],
    2: ["iman", "taqwa", "tawakkul", "dhikr", "quran_recitation"],
    3: ["iman", "salah", "zakat"],
    4: ["iman", "glad_tidings"],
    # 5–19 · Badr: reluctance, angels, rain and victory from Allah
    5: ["battle_badr", "conflict"],
    6: ["battle_badr", "anxiety_fear"],
    7: ["battle_badr", "qadr"],
    8: ["battle_badr", "qadr"],
    9: ["battle_badr", "dua", "angels"],
    10: ["battle_badr", "angels", "tawakkul", "anxiety_fear"],
    11: ["battle_badr", "anxiety_fear", "taharah", "shaytan"],
    12: ["battle_badr", "angels", "conflict"],
    13: ["battle_badr", "warnings"],
    14: ["jahannam", "kufr"],
    15: ["o_believers", "conflict", "prohibitions"],
    16: ["conflict", "jahannam", "warnings"],
    17: ["battle_badr", "qadr", "trial_test", "miracles"],
    18: ["battle_badr", "qadr"],
    19: ["battle_badr", "conflict", "warnings"],
    # 20–29 · Respond to Allah and the Messenger; trusts and trials
    20: ["o_believers", "story_muhammad", "commands"],
    21: ["hidayah", "prohibitions"],
    22: ["kufr", "knowledge"],
    23: ["hidayah", "kufr"],
    24: ["o_believers", "commands", "tazkiyah", "akhirah", "iman"],
    25: ["trial_test", "community", "warnings"],
    26: ["shukr", "hijrah", "oppression"],
    27: ["o_believers", "amanah", "prohibitions"],
    28: ["trial_test", "wealth", "parenting"],
    29: ["o_believers", "taqwa", "hidayah", "rahmah"],
    # 30–40 · Quraysh's plots and obstruction from the Sacred Mosque
    30: ["story_muhammad", "hijrah", "qadr"],
    31: ["kufr", "revelation"],
    32: ["kufr"],
    33: ["tawbah", "story_muhammad", "rahmah"],
    34: ["kaaba", "taqwa", "oppression"],
    35: ["kaaba", "salah", "kufr"],
    36: ["kufr", "wealth", "jahannam"],
    37: ["jahannam", "kufr"],
    38: ["tawbah", "kufr", "history_lessons"],
    39: ["conflict", "commands"],
    40: ["wala_bara", "tawakkul"],
    # 41–54 · The fifth of the spoils; the day of criterion; Satan deserts his allies
    41: ["battle_badr", "wealth", "social_justice", "orphans", "commands"],
    42: ["battle_badr", "qadr"],
    43: ["battle_badr", "qadr", "anxiety_fear"],
    44: ["battle_badr", "qadr"],
    45: ["o_believers", "conflict", "sabr", "dhikr", "commands"],
    46: ["sabr", "community", "conflict", "commands"],
    47: ["battle_badr", "kibr", "ikhlas", "prohibitions"],
    48: ["battle_badr", "shaytan"],
    49: ["nifaq", "tawakkul", "battle_badr"],
    50: ["death_reminder", "angels", "kufr", "jahannam"],
    51: ["adl"],
    52: ["history_lessons", "kufr"],
    53: ["tazkiyah", "shukr", "history_lessons"],
    54: ["history_lessons", "kufr"],
    # 55–66 · Treaties, preparedness, peace and steadfastness
    55: ["kufr"],
    56: ["amanah", "conflict"],
    57: ["conflict"],
    58: ["amanah", "conflict", "love_of_allah"],
    59: ["kufr", "warnings"],
    60: ["conflict", "zakat", "commands"],
    61: ["conflict", "tawakkul", "commands"],
    62: ["tawakkul", "conflict"],
    63: ["community"],
    64: ["tawakkul", "story_muhammad"],
    65: ["conflict", "sabr", "commands", "story_muhammad"],
    66: ["conflict", "sabr", "rahmah"],
    # 67–71 · The captives of Badr
    67: ["battle_badr", "conflict", "dunya", "akhirah"],
    68: ["battle_badr", "qadr", "warnings"],
    69: ["battle_badr", "wealth", "taqwa"],
    70: ["battle_badr", "story_muhammad", "tawbah", "hope_raja"],
    71: ["amanah", "conflict"],
    # 72–75 · Muhajirun, Ansar and the bonds of alliance
    72: ["hijrah", "sahabah", "wala_bara", "conflict", "amanah"],
    73: ["wala_bara", "kufr", "environment"],
    74: ["hijrah", "sahabah", "iman", "glad_tidings"],
    75: ["hijrah", "inheritance", "family", "sahabah"],
}
