"""9 · At-Tawbah · The Repentance · التوبة — 129 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–16 · Disassociation from the treaty-breaking polytheists
    1: ["wala_bara", "shirk", "amanah"],
    2: ["kufr", "warnings"],
    3: ["hajj", "wala_bara", "tawbah", "warnings"],
    4: ["amanah", "taqwa", "love_of_allah"],
    5: ["conflict", "shirk", "tawbah", "salah", "zakat"],
    6: ["dawah", "shirk", "ihsan"],
    7: ["amanah", "kaaba", "taqwa", "love_of_allah"],
    8: ["shirk", "amanah"],
    9: ["dunya", "kufr"],
    10: ["amanah", "oppression"],
    11: ["tawbah", "salah", "zakat", "community"],
    12: ["conflict", "amanah", "leadership"],
    13: ["conflict", "taqwa", "story_muhammad"],
    14: ["conflict", "commands"],
    15: ["conflict", "tawbah"],
    16: ["trial_test", "conflict", "wala_bara"],
    # 17–24 · Who maintains the mosques; loving Allah above all
    17: ["shirk", "kaaba", "jahannam"],
    18: ["salah", "zakat", "taqwa", "iman", "hidayah"],
    19: ["kaaba", "hajj", "iman", "conflict"],
    20: ["hijrah", "conflict", "iman", "glad_tidings"],
    21: ["jannah", "rahmah", "glad_tidings"],
    22: ["jannah"],
    23: ["o_believers", "wala_bara", "family", "prohibitions"],
    24: ["love_of_allah", "family", "wealth", "trade", "dunya", "conflict"],
    # 25–27 · Hunayn
    25: ["battle_hunayn", "kibr", "tawakkul"],
    26: ["battle_hunayn", "anxiety_fear", "angels"],
    27: ["battle_hunayn", "tawbah", "rahmah"],
    # 28–37 · The Sacred Mosque, the People of the Book, hoarding, sacred months
    28: ["o_believers", "kaaba", "shirk", "rizq", "tawakkul"],
    29: ["conflict", "ahl_al_kitab", "commands"],
    30: ["ahl_al_kitab", "shirk", "story_isa"],
    31: ["ahl_al_kitab", "shirk", "tawheed", "story_isa"],
    32: ["kufr", "revelation", "hidayah"],
    33: ["story_muhammad", "hidayah", "shirk"],
    34: ["o_believers", "ahl_al_kitab", "wealth", "zakat", "warnings"],
    35: ["wealth", "jahannam", "zakat"],
    36: ["time", "conflict", "taqwa"],
    37: ["time", "kufr", "hidayah"],
    # 38–72 · Tabuk: the call to go forth and the hypocrites' excuses
    38: ["o_believers", "expedition_tabuk", "conflict", "dunya", "akhirah"],
    39: ["expedition_tabuk", "conflict", "warnings"],
    40: ["hijrah", "story_muhammad", "sahabah", "tawakkul", "anxiety_fear", "angels"],
    41: ["expedition_tabuk", "conflict", "wealth", "commands"],
    42: ["expedition_tabuk", "nifaq", "sidq"],
    43: ["expedition_tabuk", "story_muhammad", "nifaq", "sidq"],
    44: ["expedition_tabuk", "iman", "conflict"],
    45: ["expedition_tabuk", "nifaq"],
    46: ["expedition_tabuk", "nifaq"],
    47: ["expedition_tabuk", "nifaq", "trial_test"],
    48: ["nifaq"],
    49: ["expedition_tabuk", "nifaq", "trial_test", "jahannam"],
    50: ["nifaq", "hasad"],
    51: ["qadr", "tawakkul", "tawheed"],
    52: ["tawakkul", "conflict", "nifaq"],
    53: ["nifaq", "zakat"],
    54: ["nifaq", "salah", "zakat", "kufr"],
    55: ["nifaq", "dunya", "trial_test"],
    56: ["nifaq", "anxiety_fear"],
    57: ["nifaq", "anxiety_fear"],
    58: ["nifaq", "zakat"],
    59: ["tawakkul", "rizq", "iman"],
    60: ["zakat", "social_justice", "debt", "commands"],
    61: ["story_muhammad", "nifaq", "speech_ethics"],
    62: ["nifaq", "sidq"],
    63: ["jahannam", "nifaq"],
    64: ["nifaq", "revelation"],
    65: ["nifaq", "speech_ethics", "kufr"],
    66: ["nifaq", "kufr"],
    67: ["nifaq", "dawah", "wealth"],
    68: ["nifaq", "jahannam"],
    69: ["history_lessons", "dunya", "kufr"],
    70: ["history_lessons", "prophethood"],
    71: ["community", "wala_bara", "women", "dawah", "salah", "zakat"],
    72: ["jannah", "women", "glad_tidings", "iman"],
    # 73–106 · Hypocrites exposed; those who stayed behind; the bedouins
    73: ["conflict", "nifaq", "story_muhammad"],
    74: ["nifaq", "kufr", "tawbah"],
    75: ["nifaq", "amanah", "zakat"],
    76: ["nifaq", "wealth", "amanah"],
    77: ["nifaq", "amanah", "sidq"],
    78: ["nifaq", "taqwa", "speech_ethics"],
    79: ["nifaq", "speech_ethics", "zakat"],
    80: ["nifaq", "tawbah", "hidayah"],
    81: ["expedition_tabuk", "nifaq", "jahannam"],
    82: ["nifaq", "warnings"],
    83: ["expedition_tabuk", "nifaq"],
    84: ["nifaq", "death_reminder", "salah"],
    85: ["nifaq", "dunya", "trial_test"],
    86: ["expedition_tabuk", "nifaq", "wealth"],
    87: ["nifaq", "tazkiyah"],
    88: ["conflict", "iman", "glad_tidings", "story_muhammad"],
    89: ["jannah", "glad_tidings"],
    90: ["expedition_tabuk", "nifaq", "sidq"],
    91: ["health", "ikhlas", "ihsan", "rahmah"],
    92: ["sahabah", "grief_loss", "iman", "expedition_tabuk"],
    93: ["nifaq", "tazkiyah", "wealth"],
    94: ["nifaq", "akhirah"],
    95: ["nifaq", "jahannam"],
    96: ["nifaq"],
    97: ["nifaq", "kufr", "knowledge"],
    98: ["nifaq", "zakat"],
    99: ["iman", "zakat", "rahmah"],
    100: ["sahabah", "hijrah", "ihsan", "jannah", "glad_tidings"],
    101: ["nifaq", "warnings"],
    102: ["tawbah", "hope_raja"],
    103: ["zakat", "tazkiyah", "dua", "tawbah", "anxiety_fear"],
    104: ["tawbah", "zakat", "rahmah"],
    105: ["taqwa", "akhirah"],
    106: ["tawbah", "qadr"],
    # 107–110 · The mosque of harm vs. the mosque founded on taqwa
    107: ["nifaq", "community", "sidq"],
    108: ["taharah", "taqwa", "love_of_allah", "salah"],
    109: ["taqwa", "parables", "hidayah"],
    110: ["nifaq", "tazkiyah"],
    # 111–118 · The believers' bargain; forgiveness of the three who stayed behind
    111: ["conflict", "jannah", "revelation", "amanah", "glad_tidings"],
    112: ["tawbah", "dhikr", "salah", "dawah", "iman", "glad_tidings"],
    113: ["shirk", "dua", "family"],
    114: ["story_ibrahim", "parents", "wala_bara", "hilm"],
    115: ["hidayah"],
    116: ["tawheed", "death_reminder", "wala_bara"],
    117: ["expedition_tabuk", "tawbah", "sahabah", "rahmah"],
    118: ["expedition_tabuk", "tawbah", "sahabah", "anxiety_fear", "rahmah"],
    # 119–129 · Be with the truthful; seeking knowledge; the Messenger's care
    119: ["o_believers", "taqwa", "sidq", "commands"],
    120: ["expedition_tabuk", "conflict", "ihsan", "glad_tidings"],
    121: ["conflict", "zakat", "glad_tidings"],
    122: ["knowledge", "dawah", "conflict"],
    123: ["o_believers", "conflict", "taqwa"],
    124: ["nifaq", "iman", "revelation"],
    125: ["nifaq", "tazkiyah", "kufr"],
    126: ["trial_test", "tawbah", "nifaq"],
    127: ["nifaq", "tazkiyah"],
    128: ["story_muhammad", "rahmah"],
    129: ["tawakkul", "tawheed"],
}
