"""10 · Yunus · Jonah · يونس — 109 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · A human messenger; the Lord of the Throne; signs of sun and moon
    1: ["muqattaat", "revelation"],
    2: ["revelation", "prophethood", "kufr", "glad_tidings"],
    3: ["tawheed", "nature_signs"],
    4: ["resurrection", "human_creation", "adl", "jahannam"],
    5: ["nature_signs", "time", "knowledge"],
    6: ["nature_signs", "taqwa"],
    7: ["dunya", "akhirah", "kufr"],
    8: ["jahannam"],
    9: ["iman", "hidayah", "jannah"],
    10: ["jannah", "dhikr"],
    # 11–24 · Man's ingratitude after distress; the parable of worldly life
    11: ["qadr", "rahmah"],
    12: ["dua", "shukr", "trial_test"],
    13: ["history_lessons", "oppression"],
    14: ["trial_test", "purpose_of_life", "history_lessons"],
    15: ["revelation", "story_muhammad", "akhirah"],
    16: ["revelation", "story_muhammad"],
    17: ["sidq", "kufr"],
    18: ["shirk"],
    19: ["community", "qadr"],
    20: ["miracles", "kufr"],
    21: ["shukr", "kufr", "rahmah"],
    22: ["dua", "ikhlas", "nature_signs", "anxiety_fear", "shukr"],
    23: ["o_mankind", "oppression", "dunya", "shukr"],
    24: ["parables", "dunya", "nature_signs"],
    # 25–36 · The Home of Peace; who provides, who guides?
    25: ["jannah", "hidayah"],
    26: ["jannah", "ihsan", "glad_tidings"],
    27: ["jahannam", "adl", "warnings"],
    28: ["akhirah", "shirk"],
    29: ["akhirah", "shirk"],
    30: ["akhirah"],
    31: ["tawheed", "rizq", "nature_signs", "taqwa"],
    32: ["tawheed", "hidayah", "asma_ul_husna"],
    33: ["kufr", "qadr"],
    34: ["tawheed", "shirk", "resurrection", "human_creation"],
    35: ["hidayah", "shirk"],
    36: ["knowledge", "shirk"],
    # 37–56 · The challenge of the Quran; every nation has a term
    37: ["revelation"],
    38: ["revelation"],
    39: ["kufr", "knowledge", "history_lessons"],
    40: ["iman", "kufr"],
    41: ["dawah", "story_muhammad"],
    42: ["hidayah", "kufr"],
    43: ["hidayah"],
    44: ["adl", "oppression"],
    45: ["akhirah", "time", "dunya"],
    46: ["story_muhammad", "akhirah"],
    47: ["prophethood", "adl", "akhirah"],
    48: ["akhirah", "kufr"],
    49: ["qadr", "time", "story_muhammad"],
    50: ["warnings"],
    51: ["kufr", "warnings"],
    52: ["jahannam", "adl"],
    53: ["akhirah"],
    54: ["akhirah", "adl"],
    55: ["tawheed", "akhirah"],
    56: ["death_reminder", "resurrection"],
    # 57–70 · Healing for the hearts; the allies of Allah
    57: ["o_mankind", "revelation", "quran_recitation", "health", "tazkiyah", "hidayah"],
    58: ["rahmah", "dunya", "shukr"],
    59: ["food_halal", "rizq", "sidq"],
    60: ["shukr", "akhirah"],
    61: ["taqwa", "knowledge"],
    62: ["wala_bara", "taqwa", "anxiety_fear", "glad_tidings"],
    63: ["iman", "taqwa", "wala_bara"],
    64: ["glad_tidings", "dunya", "akhirah"],
    65: ["story_muhammad", "grief_loss", "tawakkul", "speech_ethics"],
    66: ["tawheed", "shirk"],
    67: ["nature_signs"],
    68: ["shirk", "tawheed"],
    69: ["sidq", "warnings"],
    70: ["dunya", "jahannam", "kufr"],
    # 71–74 · Nuh
    71: ["story_nuh", "tawakkul", "dawah"],
    72: ["story_nuh", "ikhlas", "dawah"],
    73: ["story_nuh", "history_lessons"],
    74: ["prophethood", "tazkiyah", "history_lessons"],
    # 75–93 · Musa, Harun and Pharaoh's belief too late
    75: ["story_musa", "story_harun", "kibr"],
    76: ["story_musa", "kufr"],
    77: ["story_musa"],
    78: ["story_musa", "kibr", "kufr"],
    79: ["story_musa"],
    80: ["story_musa"],
    81: ["story_musa", "environment"],
    82: ["story_musa", "sidq"],
    83: ["story_musa", "oppression", "anxiety_fear", "iman"],
    84: ["story_musa", "tawakkul", "iman"],
    85: ["story_bani_israil", "tawakkul", "dua"],
    86: ["story_bani_israil", "dua", "rahmah"],
    87: ["story_musa", "story_harun", "salah", "glad_tidings"],
    88: ["story_musa", "dua", "wealth", "dunya"],
    89: ["story_musa", "dua", "hidayah"],
    90: ["story_musa", "tawbah", "death_reminder"],
    91: ["story_musa", "tawbah"],
    92: ["story_musa", "history_lessons", "miracles"],
    93: ["story_bani_israil", "rizq", "community"],
    # 94–103 · The people of Yunus; faith cannot be compelled
    94: ["revelation", "ahl_al_kitab", "iman"],
    95: ["kufr", "warnings"],
    96: ["kufr", "qadr"],
    97: ["kufr"],
    98: ["story_yunus", "tawbah", "iman", "rahmah"],
    99: ["dawah", "qadr", "iman"],
    100: ["iman", "qadr", "knowledge"],
    101: ["nature_signs", "kufr"],
    102: ["history_lessons", "warnings"],
    103: ["iman", "glad_tidings"],
    # 104–109 · My religion is Allah alone
    104: ["o_mankind", "tawheed", "death_reminder"],
    105: ["tawheed", "shirk", "commands"],
    106: ["shirk", "dua", "prohibitions"],
    107: ["tawakkul", "tawheed", "qadr", "asma_ul_husna"],
    108: ["o_mankind", "hidayah", "revelation"],
    109: ["sabr", "revelation", "commands"],
}
