"""11 · Hud · Hud · هود — 123 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–24 · A perfected Book; man in ease and hardship; two parties
    1: ["muqattaat", "revelation"],
    2: ["tawheed", "prophethood", "dawah"],
    3: ["tawbah", "rizq", "glad_tidings", "akhirah"],
    4: ["akhirah"],
    5: ["taqwa", "kufr"],
    6: ["rizq", "tawakkul", "tawheed", "animals"],
    7: ["nature_signs", "trial_test", "purpose_of_life", "resurrection", "kufr"],
    8: ["kufr", "warnings"],
    9: ["human_creation", "shukr", "hope_raja"],
    10: ["human_creation", "kibr", "shukr"],
    11: ["sabr", "glad_tidings"],
    12: ["story_muhammad", "revelation", "miracles"],
    13: ["revelation"],
    14: ["revelation", "tawheed"],
    15: ["dunya", "akhirah"],
    16: ["dunya", "jahannam"],
    17: ["revelation", "story_musa", "iman", "jahannam"],
    18: ["sidq", "akhirah", "oppression"],
    19: ["kufr", "akhirah"],
    20: ["kufr", "jahannam"],
    21: ["kufr", "akhirah"],
    22: ["akhirah"],
    23: ["iman", "kibr", "jannah"],
    24: ["parables", "iman", "kufr"],
    # 25–49 · Nuh, the ark and his son
    25: ["story_nuh", "dawah"],
    26: ["story_nuh", "tawheed"],
    27: ["story_nuh", "kibr", "prophethood"],
    28: ["story_nuh", "dawah", "rahmah"],
    29: ["story_nuh", "ikhlas", "kibr"],
    30: ["story_nuh"],
    31: ["story_nuh", "prophethood", "kibr"],
    32: ["story_nuh", "kufr"],
    33: ["story_nuh", "qadr"],
    34: ["story_nuh", "hidayah", "dawah"],
    35: ["story_muhammad", "revelation"],
    36: ["story_nuh", "grief_loss"],
    37: ["story_nuh"],
    38: ["story_nuh", "speech_ethics"],
    39: ["story_nuh", "warnings"],
    40: ["story_nuh", "animals", "family", "miracles"],
    41: ["story_nuh", "dhikr", "tawakkul"],
    42: ["story_nuh", "parenting", "family"],
    43: ["story_nuh", "parenting", "qadr", "kufr"],
    44: ["story_nuh", "nature_signs", "history_lessons"],
    45: ["story_nuh", "dua", "parenting"],
    46: ["story_nuh", "family", "iman", "knowledge"],
    47: ["story_nuh", "dua", "tawbah"],
    48: ["story_nuh", "glad_tidings"],
    49: ["revelation", "sabr", "taqwa", "story_muhammad"],
    # 50–60 · Hud and 'Ad
    50: ["story_hud", "tawheed"],
    51: ["story_hud", "ikhlas", "dawah"],
    52: ["story_hud", "tawbah", "rizq"],
    53: ["story_hud", "kufr", "shirk"],
    54: ["story_hud", "shirk"],
    55: ["story_hud", "tawakkul"],
    56: ["story_hud", "tawakkul", "qadr"],
    57: ["story_hud", "dawah"],
    58: ["story_hud", "rahmah"],
    59: ["story_hud", "kufr", "oppression"],
    60: ["story_hud", "history_lessons"],
    # 61–68 · Salih and Thamud
    61: ["story_salih", "tawheed", "tawbah", "human_creation", "dua"],
    62: ["story_salih", "shirk"],
    63: ["story_salih", "dawah"],
    64: ["story_salih", "miracles", "animals"],
    65: ["story_salih", "warnings"],
    66: ["story_salih", "rahmah"],
    67: ["story_salih", "history_lessons"],
    68: ["story_salih", "history_lessons"],
    # 69–76 · Ibrahim's guests and the glad tidings of Ishaq
    69: ["story_ibrahim", "angels", "adab", "glad_tidings"],
    70: ["story_ibrahim", "angels", "story_lut"],
    71: ["story_ishaq", "story_ibrahim", "glad_tidings", "women"],
    72: ["story_ishaq", "story_ibrahim", "miracles", "women"],
    73: ["story_ibrahim", "rahmah", "family"],
    74: ["story_ibrahim", "story_lut"],
    75: ["story_ibrahim", "hilm", "tawbah"],
    76: ["story_ibrahim", "qadr"],
    # 77–83 · Lut
    77: ["story_lut", "angels", "anxiety_fear"],
    78: ["story_lut", "haya", "adab"],
    79: ["story_lut", "haya"],
    80: ["story_lut"],
    81: ["story_lut", "angels", "family"],
    82: ["story_lut", "history_lessons"],
    83: ["story_lut", "warnings"],
    # 84–95 · Shu'ayb and Madyan
    84: ["story_shuayb", "tawheed", "trade"],
    85: ["story_shuayb", "trade", "adl", "environment"],
    86: ["story_shuayb", "rizq", "iman"],
    87: ["story_shuayb", "salah", "wealth", "shirk"],
    88: ["story_shuayb", "tawakkul", "dawah", "tawheed"],
    89: ["story_shuayb", "history_lessons", "warnings"],
    90: ["story_shuayb", "tawbah", "rahmah", "love_of_allah"],
    91: ["story_shuayb", "kibr"],
    92: ["story_shuayb", "family", "taqwa"],
    93: ["story_shuayb", "warnings"],
    94: ["story_shuayb", "history_lessons", "rahmah"],
    95: ["story_shuayb", "history_lessons"],
    # 96–99 · Musa and Pharaoh
    96: ["story_musa", "prophethood"],
    97: ["story_musa", "leadership", "oppression"],
    98: ["story_musa", "leadership", "jahannam", "akhirah"],
    99: ["story_musa", "history_lessons"],
    # 100–111 · The news of the towns; the wretched and the prosperous
    100: ["history_lessons", "revelation"],
    101: ["history_lessons", "shirk", "adl"],
    102: ["history_lessons", "oppression", "warnings"],
    103: ["akhirah", "taqwa"],
    104: ["akhirah", "time"],
    105: ["akhirah"],
    106: ["jahannam"],
    107: ["jahannam", "qadr"],
    108: ["jannah", "glad_tidings"],
    109: ["shirk", "story_muhammad"],
    110: ["story_musa", "revelation", "community"],
    111: ["akhirah", "adl"],
    # 112–123 · Stand firm, pray, be patient; why the stories are told
    112: ["hidayah", "commands", "prohibitions"],
    113: ["wala_bara", "oppression", "prohibitions", "jahannam"],
    114: ["salah", "tawbah", "time", "commands"],
    115: ["sabr", "ihsan", "commands"],
    116: ["dawah", "environment", "history_lessons", "dunya"],
    117: ["history_lessons", "adl"],
    118: ["community", "qadr"],
    119: ["rahmah", "jahannam", "jinn", "purpose_of_life", "qadr"],
    120: ["prophethood", "story_muhammad", "revelation"],
    121: ["dawah", "warnings"],
    122: ["warnings"],
    123: ["tawheed", "tawakkul", "knowledge"],
}
