"""12 · Yusuf · Joseph · يوسف — 111 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–3 · The best of stories
    1: ["muqattaat", "revelation"],
    2: ["revelation", "knowledge"],
    3: ["revelation", "story_yusuf"],
    # 4–20 · The dream, the brothers' envy and the well
    4: ["story_yusuf", "story_yaqub"],
    5: ["story_yusuf", "story_yaqub", "shaytan", "hasad", "parenting"],
    6: ["story_yusuf", "story_yaqub", "prophethood", "knowledge"],
    7: ["story_yusuf", "knowledge"],
    8: ["story_yusuf", "hasad", "family"],
    9: ["story_yusuf", "hasad"],
    10: ["story_yusuf", "hasad"],
    11: ["story_yusuf", "story_yaqub", "amanah", "sidq"],
    12: ["story_yusuf", "story_yaqub", "sidq"],
    13: ["story_yusuf", "story_yaqub", "anxiety_fear", "grief_loss"],
    14: ["story_yusuf", "sidq"],
    15: ["story_yusuf", "trial_test", "hope_raja"],
    16: ["story_yusuf", "sidq"],
    17: ["story_yusuf", "sidq"],
    18: ["story_yusuf", "story_yaqub", "sabr", "tawakkul", "grief_loss"],
    19: ["story_yusuf"],
    20: ["story_yusuf", "wealth"],
    # 21–35 · In the house of al-'Aziz: temptation and chastity
    21: ["story_yusuf", "qadr", "knowledge"],
    22: ["story_yusuf", "knowledge", "ihsan"],
    23: ["story_yusuf", "haya", "amanah", "tazkiyah"],
    24: ["story_yusuf", "haya", "tazkiyah", "ikhlas"],
    25: ["story_yusuf", "haya", "sidq"],
    26: ["story_yusuf", "sidq", "adl"],
    27: ["story_yusuf", "sidq", "adl"],
    28: ["story_yusuf", "sidq"],
    29: ["story_yusuf", "tawbah"],
    30: ["story_yusuf", "speech_ethics", "women"],
    31: ["story_yusuf", "women", "haya"],
    32: ["story_yusuf", "haya", "oppression"],
    33: ["story_yusuf", "dua", "haya", "sabr"],
    34: ["story_yusuf", "dua"],
    35: ["story_yusuf", "oppression"],
    # 36–42 · Da'wah in prison; the two dreams
    36: ["story_yusuf", "knowledge", "ihsan"],
    37: ["story_yusuf", "knowledge", "dawah"],
    38: ["story_yusuf", "tawheed", "shukr", "prophethood"],
    39: ["story_yusuf", "tawheed", "dawah", "asma_ul_husna"],
    40: ["story_yusuf", "tawheed", "shirk"],
    41: ["story_yusuf", "knowledge", "qadr"],
    42: ["story_yusuf", "shaytan"],
    # 43–57 · The king's dream; Yusuf vindicated and placed over the storehouses
    43: ["story_yusuf"],
    44: ["story_yusuf", "knowledge"],
    45: ["story_yusuf"],
    46: ["story_yusuf", "sidq"],
    47: ["story_yusuf", "work_ethics", "rizq", "knowledge"],
    48: ["story_yusuf", "rizq"],
    49: ["story_yusuf", "nature_signs", "rizq"],
    50: ["story_yusuf", "sabr", "adl"],
    51: ["story_yusuf", "sidq", "women", "tawbah"],
    52: ["story_yusuf", "amanah"],
    53: ["story_yusuf", "tazkiyah", "rahmah"],
    54: ["story_yusuf", "leadership", "amanah"],
    55: ["story_yusuf", "leadership", "knowledge", "work_ethics", "amanah"],
    56: ["story_yusuf", "rahmah", "ihsan"],
    57: ["akhirah", "iman", "taqwa"],
    # 58–82 · The brothers return; Binyamin and the king's cup
    58: ["story_yusuf", "family"],
    59: ["story_yusuf", "trade"],
    60: ["story_yusuf"],
    61: ["story_yusuf", "family"],
    62: ["story_yusuf", "ihsan"],
    63: ["story_yusuf", "story_yaqub"],
    64: ["story_yusuf", "story_yaqub", "tawakkul", "amanah", "tawheed"],
    65: ["story_yusuf", "rizq"],
    66: ["story_yusuf", "story_yaqub", "amanah"],
    67: ["story_yaqub", "story_yusuf", "tawakkul", "qadr"],
    68: ["story_yaqub", "story_yusuf", "qadr", "knowledge"],
    69: ["story_yusuf", "family", "grief_loss"],
    70: ["story_yusuf"],
    71: ["story_yusuf"],
    72: ["story_yusuf"],
    73: ["story_yusuf", "sidq"],
    74: ["story_yusuf"],
    75: ["story_yusuf", "criminal_law"],
    76: ["story_yusuf", "qadr", "knowledge"],
    77: ["story_yusuf", "hilm", "speech_ethics"],
    78: ["story_yusuf", "family"],
    79: ["story_yusuf", "adl"],
    80: ["story_yusuf", "amanah"],
    81: ["story_yusuf", "sidq"],
    82: ["story_yusuf", "sidq"],
    # 83–98 · Yaqub's grief and hope; the reunion and forgiveness
    83: ["story_yaqub", "story_yusuf", "sabr", "hope_raja"],
    84: ["story_yaqub", "story_yusuf", "grief_loss", "sabr"],
    85: ["story_yaqub", "story_yusuf", "grief_loss"],
    86: ["story_yaqub", "story_yusuf", "grief_loss", "sabr", "dua"],
    87: ["story_yaqub", "story_yusuf", "hope_raja", "tawakkul"],
    88: ["story_yusuf", "zakat"],
    89: ["story_yusuf", "family"],
    90: ["story_yusuf", "taqwa", "sabr", "ihsan", "glad_tidings"],
    91: ["story_yusuf", "tawbah", "family"],
    92: ["story_yusuf", "hilm", "rahmah"],
    93: ["story_yusuf", "miracles", "family"],
    94: ["story_yaqub", "story_yusuf", "miracles"],
    95: ["story_yaqub", "story_yusuf"],
    96: ["story_yaqub", "story_yusuf", "miracles", "glad_tidings"],
    97: ["story_yusuf", "tawbah", "family"],
    98: ["story_yaqub", "tawbah", "rahmah"],
    # 99–101 · The dream fulfilled; Yusuf's dua
    99: ["story_yusuf", "parents", "family"],
    100: ["story_yusuf", "parents", "shaytan", "qadr", "shukr"],
    101: ["story_yusuf", "dua", "shukr", "death_reminder"],
    # 102–111 · The lesson in their stories
    102: ["revelation", "story_muhammad", "story_yusuf"],
    103: ["iman", "dawah"],
    104: ["dawah", "ikhlas", "revelation"],
    105: ["nature_signs", "kufr"],
    106: ["shirk", "iman"],
    107: ["akhirah", "warnings"],
    108: ["dawah", "knowledge", "tawheed", "story_muhammad"],
    109: ["prophethood", "history_lessons", "akhirah", "taqwa"],
    110: ["prophethood", "hope_raja", "history_lessons"],
    111: ["history_lessons", "revelation", "knowledge", "hidayah"],
}
