"""15 · Al-Hijr · The Rocky Tract · الحجر — 99 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–15 · The Quran preserved; mockers of the messengers
    1: ["muqattaat", "revelation"],
    2: ["kufr", "iman"],
    3: ["dunya", "kufr", "warnings"],
    4: ["history_lessons", "qadr"],
    5: ["qadr", "time", "history_lessons"],
    6: ["kufr", "story_muhammad", "speech_ethics"],
    7: ["kufr", "angels", "miracles"],
    8: ["angels", "kufr"],
    9: ["revelation"],
    10: ["prophethood", "history_lessons"],
    11: ["prophethood", "speech_ethics"],
    12: ["kufr", "tazkiyah"],
    13: ["kufr", "history_lessons"],
    14: ["kufr", "miracles"],
    15: ["kufr"],
    # 16–25 · Signs in the sky and earth; Allah gives life and death
    16: ["nature_signs"],
    17: ["nature_signs", "shaytan"],
    18: ["shaytan", "jinn"],
    19: ["nature_signs"],
    20: ["rizq", "nature_signs"],
    21: ["rizq", "qadr"],
    22: ["nature_signs", "rizq"],
    23: ["death_reminder", "resurrection", "asma_ul_husna"],
    24: ["qadr"],
    25: ["akhirah", "resurrection"],
    # 26–44 · Creation of man and jinn; Iblis refuses
    26: ["human_creation", "story_adam"],
    27: ["jinn"],
    28: ["story_adam", "angels", "human_creation"],
    29: ["story_adam", "angels", "human_creation"],
    30: ["story_adam", "angels"],
    31: ["story_adam", "shaytan", "kibr"],
    32: ["story_adam", "shaytan"],
    33: ["story_adam", "shaytan", "kibr"],
    34: ["story_adam", "shaytan"],
    35: ["shaytan", "akhirah"],
    36: ["shaytan", "story_adam"],
    37: ["shaytan"],
    38: ["shaytan", "akhirah"],
    39: ["shaytan", "hidayah"],
    40: ["shaytan", "ikhlas"],
    41: ["hidayah"],
    42: ["shaytan", "iman"],
    43: ["jahannam", "shaytan"],
    44: ["jahannam"],
    # 45–50 · The righteous in gardens; mercy and punishment
    45: ["jannah", "taqwa"],
    46: ["jannah"],
    47: ["jannah", "community", "hasad"],
    48: ["jannah"],
    49: ["rahmah", "hope_raja", "asma_ul_husna"],
    50: ["warnings", "jahannam"],
    # 51–77 · Ibrahim's guests and the people of Lut
    51: ["story_ibrahim", "angels"],
    52: ["story_ibrahim", "angels", "anxiety_fear"],
    53: ["story_ibrahim", "story_ishaq", "glad_tidings"],
    54: ["story_ibrahim", "story_ishaq"],
    55: ["story_ibrahim", "hope_raja"],
    56: ["story_ibrahim", "hope_raja", "rahmah"],
    57: ["story_ibrahim", "angels"],
    58: ["story_lut", "angels"],
    59: ["story_lut", "family"],
    60: ["story_lut", "women", "qadr"],
    61: ["story_lut", "angels"],
    62: ["story_lut"],
    63: ["story_lut", "angels"],
    64: ["story_lut", "sidq"],
    65: ["story_lut", "family"],
    66: ["story_lut", "qadr"],
    67: ["story_lut", "haya"],
    68: ["story_lut", "adab"],
    69: ["story_lut", "taqwa"],
    70: ["story_lut"],
    71: ["story_lut", "marriage"],
    72: ["story_lut", "oaths"],
    73: ["story_lut", "history_lessons"],
    74: ["story_lut", "history_lessons"],
    75: ["history_lessons", "knowledge"],
    76: ["history_lessons"],
    77: ["history_lessons", "iman"],
    # 78–84 · The people of the thicket and of al-Hijr
    78: ["story_shuayb", "oppression"],
    79: ["story_shuayb", "history_lessons"],
    80: ["story_salih", "kufr"],
    81: ["story_salih", "kufr"],
    82: ["story_salih", "dunya"],
    83: ["story_salih", "history_lessons"],
    84: ["story_salih", "history_lessons"],
    # 85–99 · The seven oft-repeated; glorify your Lord until certainty comes
    85: ["nature_signs", "akhirah", "hilm", "commands"],
    86: ["asma_ul_husna"],
    87: ["revelation", "quran_recitation", "story_muhammad"],
    88: ["dunya", "kibr", "adab", "story_muhammad"],
    89: ["story_muhammad", "dawah"],
    90: ["ahl_al_kitab", "revelation"],
    91: ["revelation", "kufr"],
    92: ["akhirah", "oaths"],
    93: ["akhirah"],
    94: ["dawah", "commands", "story_muhammad"],
    95: ["tawakkul", "story_muhammad"],
    96: ["shirk", "warnings"],
    97: ["story_muhammad", "anxiety_fear", "grief_loss"],
    98: ["dhikr", "salah", "commands", "anxiety_fear"],
    99: ["purpose_of_life", "death_reminder", "commands"],
}
