"""16 · An-Nahl · The Bee · النحل — 128 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–4 · The command is coming; man a clear adversary
    1: ["akhirah", "shirk"],
    2: ["angels", "revelation", "tawheed", "taqwa"],
    3: ["nature_signs", "shirk"],
    4: ["human_creation", "kufr"],
    # 5–18 · Blessings of cattle, rain, stars and seas
    5: ["animals", "rizq", "shukr"],
    6: ["animals"],
    7: ["animals", "rahmah"],
    8: ["animals", "nature_signs"],
    9: ["hidayah", "qadr"],
    10: ["nature_signs", "rizq"],
    11: ["nature_signs", "rizq", "knowledge"],
    12: ["nature_signs", "knowledge"],
    13: ["nature_signs"],
    14: ["nature_signs", "rizq", "shukr"],
    15: ["nature_signs", "hidayah"],
    16: ["nature_signs", "hidayah"],
    17: ["tawheed", "shirk"],
    18: ["shukr", "rahmah", "nature_signs"],
    # 19–40 · The arrogant and the righteous at death; every nation had a messenger
    19: ["taqwa", "knowledge"],
    20: ["shirk"],
    21: ["shirk", "resurrection"],
    22: ["tawheed", "kibr", "akhirah"],
    23: ["kibr", "love_of_allah", "taqwa"],
    24: ["kufr", "revelation"],
    25: ["akhirah", "hidayah", "warnings"],
    26: ["history_lessons", "warnings"],
    27: ["akhirah", "shirk", "knowledge"],
    28: ["death_reminder", "angels", "oppression"],
    29: ["jahannam", "kibr"],
    30: ["taqwa", "ihsan", "dunya", "akhirah", "jannah"],
    31: ["jannah", "taqwa"],
    32: ["death_reminder", "angels", "jannah"],
    33: ["angels", "kufr", "history_lessons"],
    34: ["history_lessons", "warnings"],
    35: ["shirk", "qadr", "prophethood"],
    36: ["prophethood", "tawheed", "shirk", "hidayah", "history_lessons"],
    37: ["hidayah", "story_muhammad"],
    38: ["resurrection", "kufr"],
    39: ["resurrection", "akhirah"],
    40: ["qadr"],
    # 41–50 · Emigrants rewarded; all creation prostrates
    41: ["hijrah", "oppression", "glad_tidings"],
    42: ["sabr", "tawakkul"],
    43: ["prophethood", "knowledge"],
    44: ["revelation", "story_muhammad", "knowledge"],
    45: ["warnings", "taqwa"],
    46: ["warnings"],
    47: ["warnings", "rahmah"],
    48: ["nature_signs", "tawheed", "kibr"],
    49: ["nature_signs", "angels", "kibr"],
    50: ["sajdah_tilawah", "angels", "taqwa"],
    # 51–64 · One God; the pagans' daughters and buried girls
    51: ["tawheed", "shirk", "taqwa"],
    52: ["tawheed", "taqwa"],
    53: ["shukr", "tawheed", "dua"],
    54: ["shirk", "shukr"],
    55: ["shukr", "kufr", "warnings"],
    56: ["shirk", "rizq"],
    57: ["shirk", "women"],
    58: ["women", "parenting", "grief_loss"],
    59: ["women", "parenting", "oppression"],
    60: ["akhirah", "asma_ul_husna"],
    61: ["rahmah", "qadr", "time"],
    62: ["shirk", "jahannam"],
    63: ["shaytan", "history_lessons", "wala_bara"],
    64: ["revelation", "hidayah", "rahmah"],
    # 65–83 · Lessons in milk, fruit, the bee, old age and shelter
    65: ["nature_signs", "resurrection"],
    66: ["animals", "nature_signs", "food_halal"],
    67: ["nature_signs", "food_halal", "rizq"],
    68: ["animals", "nature_signs"],
    69: ["animals", "health", "nature_signs"],
    70: ["human_creation", "death_reminder", "knowledge", "time"],
    71: ["rizq", "shirk"],
    72: ["marriage", "family", "rizq", "shukr"],
    73: ["shirk", "rizq"],
    74: ["shirk", "knowledge"],
    75: ["parables", "shirk", "zakat"],
    76: ["parables", "adl", "shirk"],
    77: ["akhirah", "knowledge", "qadr"],
    78: ["human_creation", "knowledge", "shukr"],
    79: ["nature_signs", "animals", "iman"],
    80: ["animals", "rizq", "shukr"],
    81: ["shukr", "nature_signs"],
    82: ["dawah", "story_muhammad"],
    83: ["shukr", "kufr"],
    # 84–89 · Every nation's witness on the Day
    84: ["akhirah", "kufr"],
    85: ["akhirah", "jahannam"],
    86: ["akhirah", "shirk"],
    87: ["akhirah", "shirk"],
    88: ["kufr", "jahannam", "environment"],
    89: ["akhirah", "revelation", "story_muhammad", "hidayah", "glad_tidings"],
    # 90–97 · Justice, excellence and keeping oaths; a good life
    90: ["adl", "ihsan", "family", "haya", "commands", "prohibitions"],
    91: ["amanah", "commands"],
    92: ["amanah", "parables", "trial_test"],
    93: ["qadr", "hidayah", "akhirah"],
    94: ["amanah", "prohibitions", "warnings"],
    95: ["amanah", "dunya"],
    96: ["dunya", "sabr", "glad_tidings"],
    97: ["women", "iman", "glad_tidings"],
    # 98–111 · Seeking refuge before recitation; faith under compulsion
    98: ["quran_recitation", "shaytan", "dhikr", "commands"],
    99: ["shaytan", "iman", "tawakkul"],
    100: ["shaytan", "shirk", "wala_bara"],
    101: ["revelation", "kufr"],
    102: ["revelation", "angels", "hidayah", "glad_tidings"],
    103: ["revelation", "kufr"],
    104: ["kufr", "hidayah"],
    105: ["sidq", "kufr"],
    106: ["kufr", "iman", "oppression"],
    107: ["dunya", "kufr", "hidayah"],
    108: ["kufr", "tazkiyah", "dunya"],
    109: ["akhirah"],
    110: ["hijrah", "sabr", "oppression", "conflict", "rahmah"],
    111: ["akhirah", "adl"],
    # 112–119 · The ungrateful town; lawful and unlawful food
    112: ["parables", "shukr", "history_lessons", "rizq"],
    113: ["history_lessons", "kufr"],
    114: ["food_halal", "shukr", "commands"],
    115: ["food_halal", "prohibitions", "rahmah"],
    116: ["food_halal", "sidq", "prohibitions"],
    117: ["dunya", "warnings"],
    118: ["food_halal", "story_bani_israil", "adl"],
    119: ["tawbah", "rahmah"],
    # 120–128 · Ibrahim a nation in himself; invite with wisdom; be patient
    120: ["story_ibrahim", "tawheed", "leadership"],
    121: ["story_ibrahim", "shukr", "hidayah"],
    122: ["story_ibrahim", "glad_tidings"],
    123: ["story_ibrahim", "story_muhammad", "tawheed"],
    124: ["story_bani_israil", "akhirah"],
    125: ["dawah", "knowledge", "speech_ethics", "commands"],
    126: ["criminal_law", "sabr", "hilm"],
    127: ["sabr", "story_muhammad", "grief_loss", "anxiety_fear"],
    128: ["taqwa", "ihsan"],
}
