"""17 · Al-Isra · The Night Journey · الإسراء — 111 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–8 · The Night Journey; Bani Israil's two corruptions
    1: ["isra_miraj", "story_muhammad", "kaaba", "miracles", "tawheed"],
    2: ["story_musa", "revelation", "story_bani_israil", "tawakkul"],
    3: ["story_nuh", "shukr"],
    4: ["story_bani_israil", "environment", "kibr"],
    5: ["story_bani_israil", "history_lessons"],
    6: ["story_bani_israil", "history_lessons"],
    7: ["story_bani_israil", "history_lessons", "ihsan"],
    8: ["story_bani_israil", "rahmah", "tawbah", "jahannam"],
    # 9–22 · The Quran guides; each soul's record; seekers of this world and the next
    9: ["revelation", "hidayah", "glad_tidings"],
    10: ["akhirah", "warnings"],
    11: ["human_creation", "dua"],
    12: ["nature_signs", "time"],
    13: ["akhirah", "qadr"],
    14: ["akhirah"],
    15: ["hidayah", "adl", "prophethood"],
    16: ["history_lessons", "dunya"],
    17: ["history_lessons"],
    18: ["dunya", "jahannam"],
    19: ["akhirah", "iman", "work_ethics"],
    20: ["rizq", "rahmah"],
    21: ["rizq", "akhirah"],
    22: ["shirk", "prohibitions"],
    # 23–39 · The commandments: parents, spending, life, chastity, orphans, measure
    23: ["parents", "tawheed", "speech_ethics", "commands"],
    24: ["parents", "dua", "kibr", "rahmah"],
    25: ["parents", "tawbah", "ikhlas"],
    26: ["family", "zakat", "social_justice", "wealth", "prohibitions"],
    27: ["wealth", "shaytan", "prohibitions"],
    28: ["speech_ethics", "social_justice"],
    29: ["wealth", "commands"],
    30: ["rizq", "qadr"],
    31: ["parenting", "rizq", "prohibitions"],
    32: ["haya", "prohibitions"],
    33: ["criminal_law", "adl", "prohibitions"],
    34: ["orphans", "amanah", "commands"],
    35: ["trade", "adl", "commands"],
    36: ["knowledge", "prohibitions", "commands"],
    37: ["kibr", "prohibitions"],
    38: ["prohibitions"],
    39: ["shirk", "jahannam"],
    # 40–60 · Refuting partners; resurrection questioned; say what is best
    40: ["shirk", "angels"],
    41: ["revelation", "kufr"],
    42: ["tawheed", "shirk"],
    43: ["tawheed"],
    44: ["tawheed", "nature_signs", "dhikr"],
    45: ["quran_recitation", "kufr", "akhirah"],
    46: ["kufr", "tazkiyah", "tawheed"],
    47: ["kufr", "story_muhammad"],
    48: ["kufr", "hidayah"],
    49: ["resurrection", "kufr"],
    50: ["resurrection"],
    51: ["resurrection", "human_creation"],
    52: ["resurrection", "time"],
    53: ["speech_ethics", "shaytan", "community"],
    54: ["rahmah", "qadr", "story_muhammad"],
    55: ["prophethood", "story_dawud", "revelation"],
    56: ["shirk", "dua"],
    57: ["hope_raja", "taqwa", "shirk"],
    58: ["history_lessons", "akhirah", "warnings"],
    59: ["story_salih", "miracles", "warnings"],
    60: ["isra_miraj", "trial_test", "jahannam"],
    # 61–72 · Iblis vows to mislead; the honour of the children of Adam
    61: ["story_adam", "shaytan", "kibr"],
    62: ["shaytan", "story_adam"],
    63: ["shaytan", "jahannam"],
    64: ["shaytan"],
    65: ["shaytan", "iman", "tawakkul"],
    66: ["nature_signs", "rizq", "rahmah"],
    67: ["dua", "shukr", "anxiety_fear"],
    68: ["warnings"],
    69: ["warnings"],
    70: ["human_creation", "shukr", "rizq"],
    71: ["akhirah", "adl"],
    72: ["hidayah", "akhirah"],
    # 73–87 · Pressure on the Prophet; prayer times and night prayer; the soul
    73: ["story_muhammad", "revelation"],
    74: ["story_muhammad"],
    75: ["story_muhammad", "warnings"],
    76: ["story_muhammad", "hijrah", "oppression"],
    77: ["prophethood", "history_lessons"],
    78: ["salah", "time", "quran_recitation", "commands"],
    79: ["salah", "akhirah", "story_muhammad"],
    80: ["dua", "commands"],
    81: ["revelation", "hidayah"],
    82: ["revelation", "health", "rahmah"],
    83: ["kufr", "shukr", "hope_raja"],
    84: ["hidayah"],
    85: ["they_ask_you", "knowledge", "human_creation"],
    86: ["revelation", "story_muhammad"],
    87: ["rahmah", "revelation"],
    # 88–100 · The inimitable Quran; demands for miracles; a human messenger
    88: ["revelation", "jinn"],
    89: ["revelation", "parables", "kufr"],
    90: ["kufr", "miracles"],
    91: ["kufr", "miracles"],
    92: ["kufr", "miracles"],
    93: ["kufr", "miracles", "prophethood"],
    94: ["prophethood", "kufr"],
    95: ["prophethood", "angels"],
    96: ["story_muhammad", "tawakkul"],
    97: ["hidayah", "jahannam", "akhirah"],
    98: ["resurrection", "kufr", "jahannam"],
    99: ["resurrection", "nature_signs", "kufr"],
    100: ["wealth", "human_creation", "rahmah"],
    # 101–111 · Musa's nine signs; the Quran revealed in stages; call upon Allah or Ar-Rahman
    101: ["story_musa", "miracles", "story_bani_israil"],
    102: ["story_musa", "miracles"],
    103: ["story_musa", "history_lessons"],
    104: ["story_bani_israil", "akhirah"],
    105: ["revelation", "story_muhammad", "prophethood"],
    106: ["revelation", "quran_recitation"],
    107: ["quran_recitation", "knowledge", "iman"],
    108: ["dhikr", "iman"],
    109: ["sajdah_tilawah", "quran_recitation", "kibr", "taqwa"],
    110: ["asma_ul_husna", "dua", "salah", "dhikr"],
    111: ["tawheed", "dhikr", "shirk"],
}
