"""18 · Al-Kahf · The Cave · الكهف — 110 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–8 · A straight Book; the earth's adornment is a test
    1: ["revelation", "dhikr"],
    2: ["revelation", "glad_tidings", "warnings"],
    3: ["jannah"],
    4: ["shirk", "warnings"],
    5: ["shirk", "sidq", "knowledge"],
    6: ["story_muhammad", "grief_loss"],
    7: ["dunya", "trial_test", "purpose_of_life"],
    8: ["dunya"],
    # 9–26 · The People of the Cave
    9: ["story_ashab_al_kahf", "miracles"],
    10: ["story_ashab_al_kahf", "dua", "rahmah", "hidayah", "tawakkul", "hope_raja"],
    11: ["story_ashab_al_kahf", "miracles"],
    12: ["story_ashab_al_kahf", "resurrection", "time"],
    13: ["story_ashab_al_kahf", "iman", "hidayah", "taqwa", "tawakkul"],
    14: ["story_ashab_al_kahf", "tawheed", "iman"],
    15: ["story_ashab_al_kahf", "shirk", "sidq"],
    16: ["story_ashab_al_kahf", "tawakkul", "rahmah"],
    17: ["story_ashab_al_kahf", "nature_signs", "hidayah"],
    18: ["story_ashab_al_kahf", "miracles", "animals"],
    19: ["story_ashab_al_kahf", "food_halal", "time"],
    20: ["story_ashab_al_kahf", "oppression"],
    21: ["story_ashab_al_kahf", "resurrection", "akhirah"],
    22: ["story_ashab_al_kahf", "knowledge", "adab"],
    23: ["adab", "qadr", "commands"],
    24: ["qadr", "dhikr", "hidayah"],
    25: ["story_ashab_al_kahf", "time"],
    26: ["story_ashab_al_kahf", "knowledge", "tawheed", "asma_ul_husna"],
    # 27–31 · Stay with those who remember Him; the choice to believe
    27: ["quran_recitation", "revelation", "commands"],
    28: ["dhikr", "sabr", "dunya", "commands", "community"],
    29: ["iman", "kufr", "jahannam", "dawah"],
    30: ["iman", "ihsan", "glad_tidings"],
    31: ["jannah"],
    # 32–44 · The parable of the two gardens
    32: ["parables", "wealth", "dunya"],
    33: ["parables", "wealth"],
    34: ["parables", "kibr", "wealth"],
    35: ["parables", "kibr", "dunya"],
    36: ["parables", "kufr", "akhirah"],
    37: ["parables", "human_creation", "kufr"],
    38: ["parables", "tawheed"],
    39: ["parables", "dhikr", "qadr", "shukr"],
    40: ["parables", "hope_raja", "tawakkul"],
    41: ["parables"],
    42: ["parables", "shirk", "wealth"],
    43: ["parables", "tawakkul"],
    44: ["tawheed"],
    # 45–59 · Worldly life like rain on vegetation; the book of deeds
    45: ["parables", "dunya", "nature_signs"],
    46: ["dunya", "wealth", "akhirah", "ihsan"],
    47: ["akhirah"],
    48: ["akhirah", "resurrection"],
    49: ["akhirah", "adl"],
    50: ["story_adam", "shaytan", "jinn", "wala_bara"],
    51: ["tawheed", "shaytan"],
    52: ["akhirah", "shirk"],
    53: ["jahannam"],
    54: ["parables", "revelation", "human_creation"],
    55: ["kufr", "history_lessons", "tawbah"],
    56: ["prophethood", "kufr", "speech_ethics"],
    57: ["kufr", "tazkiyah", "hidayah"],
    58: ["rahmah", "warnings"],
    59: ["history_lessons", "oppression"],
    # 60–82 · Musa and Khidr
    60: ["story_musa", "knowledge"],
    61: ["story_musa"],
    62: ["story_musa"],
    63: ["story_musa", "shaytan"],
    64: ["story_musa"],
    65: ["story_musa", "knowledge", "rahmah"],
    66: ["story_musa", "knowledge", "adab"],
    67: ["story_musa", "sabr"],
    68: ["story_musa", "sabr", "knowledge"],
    69: ["story_musa", "sabr"],
    70: ["story_musa", "adab"],
    71: ["story_musa", "qadr"],
    72: ["story_musa", "sabr"],
    73: ["story_musa"],
    74: ["story_musa", "qadr"],
    75: ["story_musa", "sabr"],
    76: ["story_musa"],
    77: ["story_musa", "ihsan"],
    78: ["story_musa", "knowledge"],
    79: ["story_musa", "qadr", "oppression"],
    80: ["story_musa", "qadr", "parents"],
    81: ["story_musa", "qadr", "rahmah", "parents"],
    82: ["story_musa", "orphans", "rahmah", "qadr", "parents"],
    # 83–98 · Dhul-Qarnayn
    83: ["they_ask_you", "story_dhulqarnayn"],
    84: ["story_dhulqarnayn", "leadership"],
    85: ["story_dhulqarnayn"],
    86: ["story_dhulqarnayn", "adl", "leadership"],
    87: ["story_dhulqarnayn", "adl"],
    88: ["story_dhulqarnayn", "iman", "ihsan"],
    89: ["story_dhulqarnayn"],
    90: ["story_dhulqarnayn", "nature_signs"],
    91: ["story_dhulqarnayn", "knowledge"],
    92: ["story_dhulqarnayn"],
    93: ["story_dhulqarnayn"],
    94: ["story_dhulqarnayn", "environment", "wealth"],
    95: ["story_dhulqarnayn", "ikhlas", "work_ethics"],
    96: ["story_dhulqarnayn", "work_ethics", "knowledge"],
    97: ["story_dhulqarnayn"],
    98: ["story_dhulqarnayn", "rahmah", "akhirah", "shukr"],
    # 99–110 · The greatest losers; the ocean as ink; do righteous deeds sincerely
    99: ["akhirah", "resurrection", "story_dhulqarnayn"],
    100: ["jahannam", "kufr"],
    101: ["kufr", "dhikr", "tazkiyah"],
    102: ["wala_bara", "kufr", "jahannam"],
    103: ["akhirah", "warnings"],
    104: ["dunya", "warnings"],
    105: ["kufr", "akhirah"],
    106: ["jahannam", "kufr"],
    107: ["jannah", "iman", "glad_tidings"],
    108: ["jannah"],
    109: ["asma_ul_husna", "knowledge", "parables", "tawheed"],
    110: ["ikhlas", "tawheed", "prophethood", "shirk", "commands"],
}
