"""19 · Maryam · Mary · مريم — 98 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–15 · Zakariya's quiet dua and the birth of Yahya
    1: ["muqattaat"],
    2: ["story_zakariya", "rahmah"],
    3: ["story_zakariya", "dua"],
    4: ["story_zakariya", "dua", "hope_raja"],
    5: ["story_zakariya", "dua", "family"],
    6: ["story_zakariya", "dua", "family"],
    7: ["story_zakariya", "story_yahya", "glad_tidings"],
    8: ["story_zakariya", "miracles"],
    9: ["story_zakariya", "human_creation", "qadr"],
    10: ["story_zakariya", "miracles"],
    11: ["story_zakariya", "dhikr"],
    12: ["story_yahya", "revelation", "knowledge"],
    13: ["story_yahya", "taqwa", "rahmah"],
    14: ["story_yahya", "parents", "kibr"],
    15: ["story_yahya", "death_reminder", "resurrection"],
    # 16–40 · Maryam and the birth of Isa
    16: ["story_maryam", "women"],
    17: ["story_maryam", "angels", "haya"],
    18: ["story_maryam", "haya", "dua"],
    19: ["story_maryam", "angels", "glad_tidings", "story_isa"],
    20: ["story_maryam", "haya", "miracles"],
    21: ["story_maryam", "story_isa", "miracles", "qadr"],
    22: ["story_maryam", "story_isa"],
    23: ["story_maryam", "grief_loss", "anxiety_fear"],
    24: ["story_maryam", "grief_loss", "rizq", "miracles"],
    25: ["story_maryam", "rizq", "work_ethics"],
    26: ["story_maryam", "sawm", "speech_ethics"],
    27: ["story_maryam", "story_isa"],
    28: ["story_maryam", "speech_ethics", "family"],
    29: ["story_maryam", "story_isa"],
    30: ["story_isa", "miracles", "prophethood", "revelation"],
    31: ["story_isa", "salah", "zakat"],
    32: ["story_isa", "parents", "kibr"],
    33: ["story_isa", "death_reminder", "resurrection"],
    34: ["story_isa", "ahl_al_kitab"],
    35: ["tawheed", "shirk", "qadr"],
    36: ["story_isa", "tawheed", "hidayah"],
    37: ["ahl_al_kitab", "akhirah", "warnings"],
    38: ["akhirah", "hidayah"],
    39: ["akhirah", "dunya", "warnings"],
    40: ["death_reminder", "akhirah"],
    # 41–50 · Ibrahim's gentle da'wah to his father
    41: ["story_ibrahim", "sidq", "prophethood"],
    42: ["story_ibrahim", "parents", "shirk", "dawah"],
    43: ["story_ibrahim", "parents", "knowledge", "dawah"],
    44: ["story_ibrahim", "parents", "shaytan"],
    45: ["story_ibrahim", "parents", "warnings"],
    46: ["story_ibrahim", "parents", "oppression"],
    47: ["story_ibrahim", "parents", "hilm", "dua"],
    48: ["story_ibrahim", "dua", "wala_bara"],
    49: ["story_ibrahim", "story_ishaq", "story_yaqub", "prophethood"],
    50: ["story_ibrahim", "rahmah"],
    # 51–58 · Musa, Harun, Ismail and Idris; the prophets fell weeping
    51: ["story_musa", "prophethood", "ikhlas"],
    52: ["story_musa", "revelation"],
    53: ["story_musa", "story_harun", "rahmah"],
    54: ["story_ismail", "amanah", "prophethood"],
    55: ["story_ismail", "salah", "zakat", "family"],
    56: ["story_idris", "sidq", "prophethood"],
    57: ["story_idris"],
    58: ["sajdah_tilawah", "prophethood", "quran_recitation"],
    # 59–72 · Successors who neglected prayer; all will pass over Hell
    59: ["salah", "tazkiyah", "warnings"],
    60: ["tawbah", "iman", "jannah"],
    61: ["jannah", "glad_tidings"],
    62: ["jannah", "speech_ethics"],
    63: ["jannah", "taqwa"],
    64: ["angels", "revelation"],
    65: ["tawheed", "sabr", "commands"],
    66: ["resurrection", "kufr"],
    67: ["resurrection", "human_creation"],
    68: ["akhirah", "shaytan", "jahannam", "oaths"],
    69: ["akhirah", "kibr"],
    70: ["jahannam"],
    71: ["akhirah", "jahannam", "qadr"],
    72: ["taqwa", "jahannam"],
    # 73–87 · Worldly boasting; false gods; the delegation of the righteous
    73: ["kufr", "dunya", "kibr"],
    74: ["history_lessons", "dunya"],
    75: ["warnings", "hidayah"],
    76: ["hidayah", "ihsan", "glad_tidings"],
    77: ["kufr", "wealth", "kibr"],
    78: ["kufr"],
    79: ["warnings"],
    80: ["akhirah", "death_reminder"],
    81: ["shirk"],
    82: ["shirk", "akhirah"],
    83: ["shaytan", "kufr"],
    84: ["time"],
    85: ["akhirah", "taqwa", "jannah"],
    86: ["akhirah", "jahannam"],
    87: ["akhirah"],
    # 88–98 · The monstrous claim that Ar-Rahman has a son
    88: ["shirk", "ahl_al_kitab"],
    89: ["shirk"],
    90: ["shirk", "nature_signs"],
    91: ["shirk"],
    92: ["tawheed", "shirk"],
    93: ["tawheed", "akhirah"],
    94: ["asma_ul_husna", "knowledge", "akhirah"],
    95: ["akhirah"],
    96: ["iman", "love_of_allah", "glad_tidings"],
    97: ["revelation", "dawah", "glad_tidings"],
    98: ["history_lessons"],
}
