"""20 · Taha · Ta-Ha · طه — 135 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–8 · A reminder, not a burden; the Most Merciful above the Throne
    1: ["muqattaat"],
    2: ["revelation", "story_muhammad"],
    3: ["revelation", "taqwa"],
    4: ["revelation", "nature_signs"],
    5: ["asma_ul_husna", "tawheed"],
    6: ["tawheed"],
    7: ["taqwa", "asma_ul_husna"],
    8: ["tawheed", "asma_ul_husna"],
    # 9–48 · Musa at the fire: called, given signs, and sent with Harun
    9: ["story_musa"],
    10: ["story_musa", "family", "hidayah"],
    11: ["story_musa"],
    12: ["story_musa", "adab"],
    13: ["story_musa", "prophethood", "revelation"],
    14: ["story_musa", "tawheed", "salah", "dhikr", "commands"],
    15: ["story_musa", "akhirah"],
    16: ["story_musa", "akhirah", "tazkiyah"],
    17: ["story_musa"],
    18: ["story_musa", "animals"],
    19: ["story_musa", "miracles"],
    20: ["story_musa", "miracles"],
    21: ["story_musa", "miracles", "anxiety_fear"],
    22: ["story_musa", "miracles"],
    23: ["story_musa", "miracles"],
    24: ["story_musa", "oppression"],
    25: ["story_musa", "dua", "anxiety_fear"],
    26: ["story_musa", "dua"],
    27: ["story_musa", "dua", "speech_ethics"],
    28: ["story_musa", "dua"],
    29: ["story_musa", "story_harun", "dua", "family"],
    30: ["story_musa", "story_harun"],
    31: ["story_musa", "story_harun", "dua"],
    32: ["story_musa", "story_harun"],
    33: ["story_musa", "dhikr"],
    34: ["story_musa", "dhikr"],
    35: ["story_musa"],
    36: ["story_musa", "dua"],
    37: ["story_musa", "rahmah"],
    38: ["story_musa", "parenting", "women"],
    39: ["story_musa", "love_of_allah", "qadr"],
    40: ["story_musa", "parenting", "trial_test", "family"],
    41: ["story_musa", "prophethood"],
    42: ["story_musa", "story_harun", "dhikr", "dawah"],
    43: ["story_musa", "story_harun", "oppression"],
    44: ["story_musa", "story_harun", "dawah", "speech_ethics"],
    45: ["story_musa", "story_harun", "anxiety_fear"],
    46: ["story_musa", "story_harun", "tawakkul", "anxiety_fear"],
    47: ["story_musa", "story_harun", "dawah", "story_bani_israil"],
    48: ["story_musa", "warnings"],
    # 49–76 · Before Pharaoh; the magicians believe
    49: ["story_musa"],
    50: ["story_musa", "tawheed", "hidayah", "nature_signs"],
    51: ["story_musa", "history_lessons"],
    52: ["story_musa", "knowledge", "asma_ul_husna"],
    53: ["story_musa", "nature_signs", "rizq"],
    54: ["nature_signs", "animals", "knowledge"],
    55: ["human_creation", "death_reminder", "resurrection"],
    56: ["story_musa", "kufr", "kibr"],
    57: ["story_musa"],
    58: ["story_musa"],
    59: ["story_musa"],
    60: ["story_musa"],
    61: ["story_musa", "dawah", "sidq"],
    62: ["story_musa"],
    63: ["story_musa", "story_harun"],
    64: ["story_musa"],
    65: ["story_musa"],
    66: ["story_musa", "shaytan"],
    67: ["story_musa", "anxiety_fear"],
    68: ["story_musa", "tawakkul"],
    69: ["story_musa", "miracles"],
    70: ["story_musa", "story_harun", "iman", "salah"],
    71: ["story_musa", "oppression"],
    72: ["story_musa", "iman", "dunya", "sabr"],
    73: ["story_musa", "iman", "tawbah", "akhirah"],
    74: ["jahannam"],
    75: ["iman", "jannah"],
    76: ["jannah", "tazkiyah"],
    # 77–98 · The crossing, the calf and the Samiri
    77: ["story_musa", "miracles", "story_bani_israil"],
    78: ["story_musa", "history_lessons"],
    79: ["story_musa", "leadership", "hidayah"],
    80: ["story_bani_israil", "shukr", "rizq"],
    81: ["story_bani_israil", "food_halal", "warnings"],
    82: ["tawbah", "rahmah", "iman", "hidayah"],
    83: ["story_musa"],
    84: ["story_musa", "ikhlas"],
    85: ["story_musa", "story_bani_israil", "trial_test", "shirk"],
    86: ["story_musa", "story_bani_israil", "grief_loss", "amanah"],
    87: ["story_bani_israil", "shirk"],
    88: ["story_bani_israil", "shirk"],
    89: ["shirk", "tawheed"],
    90: ["story_harun", "story_bani_israil", "trial_test", "dawah"],
    91: ["story_bani_israil", "shirk"],
    92: ["story_musa", "story_harun"],
    93: ["story_musa", "story_harun"],
    94: ["story_harun", "story_musa", "community", "family"],
    95: ["story_musa"],
    96: ["story_musa", "tazkiyah"],
    97: ["story_musa", "shirk", "warnings"],
    98: ["tawheed", "knowledge"],
    # 99–114 · The Horn, the levelled mountains, and the humbled faces
    99: ["revelation", "story_muhammad", "history_lessons"],
    100: ["revelation", "akhirah", "warnings"],
    101: ["akhirah"],
    102: ["resurrection", "akhirah"],
    103: ["akhirah", "time", "dunya"],
    104: ["akhirah", "time"],
    105: ["they_ask_you", "akhirah", "nature_signs"],
    106: ["akhirah"],
    107: ["akhirah"],
    108: ["akhirah"],
    109: ["akhirah"],
    110: ["knowledge", "asma_ul_husna"],
    111: ["akhirah", "asma_ul_husna", "oppression"],
    112: ["iman", "adl", "glad_tidings"],
    113: ["revelation", "taqwa", "dhikr"],
    114: ["knowledge", "dua", "quran_recitation", "asma_ul_husna"],
    # 115–127 · Adam's forgetting; turning away from the Reminder
    115: ["story_adam", "amanah"],
    116: ["story_adam", "angels", "shaytan"],
    117: ["story_adam", "shaytan", "jannah"],
    118: ["story_adam", "jannah"],
    119: ["story_adam", "jannah"],
    120: ["story_adam", "shaytan"],
    121: ["story_adam", "haya", "trial_test"],
    122: ["story_adam", "tawbah", "hidayah"],
    123: ["story_adam", "hidayah", "glad_tidings"],
    124: ["dhikr", "akhirah", "warnings", "anxiety_fear"],
    125: ["akhirah"],
    126: ["akhirah", "dhikr"],
    127: ["kufr", "akhirah", "warnings"],
    # 128–135 · Be patient, glorify your Lord, enjoin prayer on your family
    128: ["history_lessons", "knowledge"],
    129: ["qadr", "time"],
    130: ["salah", "sabr", "dhikr", "time", "commands"],
    131: ["dunya", "trial_test", "rizq"],
    132: ["salah", "family", "sabr", "rizq", "commands"],
    133: ["miracles", "revelation", "kufr"],
    134: ["prophethood", "adl"],
    135: ["hidayah", "warnings"],
}
