"""21 · Al-Anbya · The Prophets · الأنبياء — 112 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–15 · The reckoning draws near while they play
    1: ["akhirah", "dunya", "warnings"],
    2: ["revelation", "dunya", "kufr"],
    3: ["tazkiyah", "kufr", "prophethood"],
    4: ["taqwa", "knowledge"],
    5: ["revelation", "kufr", "miracles"],
    6: ["history_lessons", "kufr"],
    7: ["prophethood", "knowledge"],
    8: ["prophethood", "death_reminder"],
    9: ["prophethood", "history_lessons"],
    10: ["revelation", "knowledge"],
    11: ["history_lessons", "oppression"],
    12: ["history_lessons"],
    13: ["history_lessons", "dunya"],
    14: ["history_lessons"],
    15: ["history_lessons"],
    # 16–33 · Creation is not play; one God; every living thing from water
    16: ["purpose_of_life", "nature_signs"],
    17: ["purpose_of_life", "tawheed"],
    18: ["hidayah", "warnings"],
    19: ["tawheed", "angels", "kibr"],
    20: ["angels", "dhikr"],
    21: ["shirk", "resurrection"],
    22: ["tawheed", "shirk"],
    23: ["tawheed", "akhirah", "qadr"],
    24: ["shirk", "revelation", "knowledge"],
    25: ["prophethood", "tawheed", "revelation"],
    26: ["shirk", "angels"],
    27: ["angels"],
    28: ["angels", "akhirah", "taqwa"],
    29: ["shirk", "jahannam"],
    30: ["nature_signs", "iman"],
    31: ["nature_signs", "hidayah"],
    32: ["nature_signs", "kufr"],
    33: ["nature_signs"],
    # 34–50 · Every soul tastes death; the scales of justice
    34: ["death_reminder", "story_muhammad"],
    35: ["death_reminder", "trial_test", "akhirah"],
    36: ["kufr", "speech_ethics", "story_muhammad"],
    37: ["human_creation", "warnings"],
    38: ["kufr", "akhirah"],
    39: ["jahannam", "kufr"],
    40: ["akhirah", "warnings"],
    41: ["prophethood", "history_lessons", "speech_ethics"],
    42: ["kufr", "dhikr"],
    43: ["shirk"],
    44: ["dunya", "history_lessons", "kufr"],
    45: ["revelation", "dawah", "kufr"],
    46: ["warnings"],
    47: ["akhirah", "adl"],
    48: ["story_musa", "story_harun", "revelation", "taqwa"],
    49: ["taqwa", "akhirah"],
    50: ["revelation"],
    # 51–73 · Ibrahim breaks the idols and the fire is made cool
    51: ["story_ibrahim", "knowledge"],
    52: ["story_ibrahim", "shirk", "parents"],
    53: ["story_ibrahim", "shirk"],
    54: ["story_ibrahim", "shirk"],
    55: ["story_ibrahim"],
    56: ["story_ibrahim", "tawheed"],
    57: ["story_ibrahim", "shirk"],
    58: ["story_ibrahim", "shirk"],
    59: ["story_ibrahim"],
    60: ["story_ibrahim"],
    61: ["story_ibrahim"],
    62: ["story_ibrahim"],
    63: ["story_ibrahim", "knowledge"],
    64: ["story_ibrahim", "shirk"],
    65: ["story_ibrahim", "shirk"],
    66: ["story_ibrahim", "shirk", "tawheed"],
    67: ["story_ibrahim", "shirk", "knowledge"],
    68: ["story_ibrahim", "oppression"],
    69: ["story_ibrahim", "miracles", "tawakkul"],
    70: ["story_ibrahim", "history_lessons"],
    71: ["story_ibrahim", "story_lut"],
    72: ["story_ibrahim", "story_ishaq", "story_yaqub"],
    73: ["prophethood", "leadership", "salah", "zakat", "ihsan"],
    # 74–91 · Lut, Nuh, Dawud and Sulayman, Ayyub, Yunus, Zakariya, Maryam
    74: ["story_lut", "knowledge", "haya"],
    75: ["story_lut", "rahmah"],
    76: ["story_nuh", "dua"],
    77: ["story_nuh", "history_lessons"],
    78: ["story_dawud", "story_sulayman", "adl", "animals"],
    79: ["story_sulayman", "story_dawud", "knowledge", "dhikr", "nature_signs"],
    80: ["story_dawud", "work_ethics", "shukr"],
    81: ["story_sulayman", "miracles", "nature_signs"],
    82: ["story_sulayman", "jinn", "shaytan"],
    83: ["story_ayyub", "dua", "health", "rahmah"],
    84: ["story_ayyub", "rahmah", "family", "health"],
    85: ["story_ismail", "story_idris", "story_dhulkifl", "sabr"],
    86: ["rahmah", "prophethood"],
    87: ["story_yunus", "dua", "tawbah", "tawheed", "anxiety_fear"],
    88: ["story_yunus", "dua", "anxiety_fear", "glad_tidings"],
    89: ["story_zakariya", "dua", "family"],
    90: ["story_zakariya", "story_yahya", "dua", "hope_raja", "kibr"],
    91: ["story_maryam", "story_isa", "haya", "miracles"],
    # 92–112 · One religion; Ya'juj and Ma'juj; a mercy to the worlds
    92: ["tawheed", "community"],
    93: ["community", "akhirah"],
    94: ["iman", "glad_tidings"],
    95: ["history_lessons"],
    96: ["akhirah", "story_dhulqarnayn"],
    97: ["akhirah", "kufr"],
    98: ["shirk", "jahannam"],
    99: ["shirk", "jahannam"],
    100: ["jahannam"],
    101: ["jannah", "glad_tidings"],
    102: ["jannah"],
    103: ["jannah", "akhirah", "angels", "anxiety_fear"],
    104: ["akhirah", "resurrection", "nature_signs"],
    105: ["revelation", "glad_tidings", "story_dawud"],
    106: ["revelation"],
    107: ["story_muhammad", "rahmah", "prophethood"],
    108: ["tawheed", "revelation"],
    109: ["dawah", "akhirah"],
    110: ["knowledge", "taqwa"],
    111: ["trial_test", "dunya"],
    112: ["dua", "asma_ul_husna", "adl"],
}
