"""22 · Al-Hajj · The Pilgrimage · الحج — 78 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · The convulsion of the Hour; proofs of resurrection from the womb and the rain
    1: ["o_mankind", "akhirah", "taqwa", "commands"],
    2: ["akhirah", "warnings"],
    3: ["shaytan", "knowledge", "kufr"],
    4: ["shaytan", "jahannam"],
    5: ["o_mankind", "resurrection", "human_creation", "nature_signs", "death_reminder"],
    6: ["resurrection", "asma_ul_husna"],
    7: ["akhirah", "resurrection"],
    8: ["knowledge", "hidayah", "kufr"],
    9: ["kibr", "jahannam"],
    10: ["adl"],
    # 11–24 · Worship on an edge; two disputing parties
    11: ["iman", "trial_test", "warnings"],
    12: ["shirk"],
    13: ["shirk", "wala_bara"],
    14: ["iman", "jannah"],
    15: ["story_muhammad", "kufr"],
    16: ["revelation", "hidayah"],
    17: ["ahl_al_kitab", "shirk", "akhirah"],
    18: ["sajdah_tilawah", "nature_signs", "tawheed", "animals"],
    19: ["jahannam", "kufr"],
    20: ["jahannam"],
    21: ["jahannam"],
    22: ["jahannam"],
    23: ["jannah", "iman"],
    24: ["hidayah", "speech_ethics", "jannah"],
    # 25–37 · The Sacred House, the call to Hajj and the sacrifices
    25: ["kaaba", "kufr", "oppression", "warnings"],
    26: ["story_ibrahim", "kaaba", "tawheed", "taharah", "hajj"],
    27: ["hajj", "story_ibrahim", "commands"],
    28: ["hajj", "dhikr", "social_justice", "animals"],
    29: ["hajj", "amanah", "kaaba"],
    30: ["hajj", "shirk", "sidq", "prohibitions"],
    31: ["tawheed", "shirk", "parables"],
    32: ["hajj", "taqwa", "tazkiyah"],
    33: ["hajj", "kaaba", "animals"],
    34: ["hajj", "tawheed", "dhikr", "kibr", "glad_tidings"],
    35: ["taqwa", "sabr", "salah", "zakat", "dhikr"],
    36: ["hajj", "animals", "social_justice", "shukr"],
    37: ["hajj", "ikhlas", "taqwa", "ihsan"],
    # 38–48 · Permission to fight the oppressors; ruined towns and blinded hearts
    38: ["iman", "amanah", "love_of_allah"],
    39: ["conflict", "oppression"],
    40: ["conflict", "oppression", "hijrah"],
    41: ["leadership", "salah", "zakat", "dawah"],
    42: ["history_lessons", "prophethood"],
    43: ["history_lessons"],
    44: ["history_lessons"],
    45: ["history_lessons", "oppression"],
    46: ["history_lessons", "knowledge", "tazkiyah"],
    47: ["time", "akhirah", "warnings"],
    48: ["history_lessons", "oppression"],
    # 49–60 · Shaytan's insinuations tested; the emigrants provided for
    49: ["o_mankind", "dawah", "story_muhammad"],
    50: ["iman", "glad_tidings", "rizq"],
    51: ["jahannam", "kufr"],
    52: ["prophethood", "shaytan", "revelation"],
    53: ["shaytan", "trial_test", "tazkiyah"],
    54: ["knowledge", "iman", "hidayah"],
    55: ["kufr", "akhirah"],
    56: ["akhirah", "jannah"],
    57: ["kufr", "jahannam"],
    58: ["hijrah", "death_reminder", "rizq", "glad_tidings"],
    59: ["hijrah", "jannah"],
    60: ["criminal_law", "oppression", "hilm"],
    # 61–76 · Signs of His power; the parable of the fly
    61: ["nature_signs"],
    62: ["tawheed", "shirk", "asma_ul_husna"],
    63: ["nature_signs", "asma_ul_husna"],
    64: ["tawheed", "asma_ul_husna"],
    65: ["nature_signs", "rahmah"],
    66: ["death_reminder", "resurrection", "shukr"],
    67: ["hajj", "dawah", "hidayah"],
    68: ["dawah"],
    69: ["akhirah"],
    70: ["knowledge", "qadr"],
    71: ["shirk", "knowledge"],
    72: ["kufr", "quran_recitation", "jahannam"],
    73: ["o_mankind", "parables", "shirk", "animals"],
    74: ["tawheed", "asma_ul_husna"],
    75: ["prophethood", "angels"],
    76: ["knowledge", "akhirah"],
    # 77–78 · Bow, prostrate and strive; the religion of Ibrahim
    77: ["o_believers", "sajdah_tilawah", "salah", "ihsan", "commands"],
    78: ["conflict", "tawakkul", "story_ibrahim", "salah", "zakat", "commands"],
}
