"""23 · Al-Mu'minun · The Believers · المؤمنون — 118 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–11 · The successful believers
    1: ["iman", "glad_tidings"],
    2: ["salah", "taqwa"],
    3: ["speech_ethics", "iman"],
    4: ["zakat", "iman"],
    5: ["haya", "iman"],
    6: ["haya", "marriage"],
    7: ["haya", "prohibitions"],
    8: ["amanah", "sidq"],
    9: ["salah", "iman"],
    10: ["jannah", "glad_tidings"],
    11: ["jannah", "glad_tidings"],
    # 12–22 · Stages of human creation; rain, olive and cattle
    12: ["human_creation"],
    13: ["human_creation"],
    14: ["human_creation", "asma_ul_husna", "nature_signs"],
    15: ["death_reminder"],
    16: ["resurrection"],
    17: ["nature_signs"],
    18: ["nature_signs", "rizq"],
    19: ["nature_signs", "rizq"],
    20: ["nature_signs", "rizq"],
    21: ["animals", "rizq"],
    22: ["animals", "nature_signs"],
    # 23–50 · Nuh, a later messenger, Musa and Harun, Isa and Maryam
    23: ["story_nuh", "tawheed", "taqwa"],
    24: ["story_nuh", "kibr", "prophethood"],
    25: ["story_nuh", "kufr"],
    26: ["story_nuh", "dua"],
    27: ["story_nuh", "animals", "family"],
    28: ["story_nuh", "dhikr", "shukr"],
    29: ["story_nuh", "dua"],
    30: ["trial_test", "history_lessons"],
    31: ["history_lessons"],
    32: ["prophethood", "tawheed", "taqwa"],
    33: ["kibr", "dunya", "prophethood", "kufr"],
    34: ["kufr", "prophethood"],
    35: ["resurrection", "kufr"],
    36: ["resurrection", "kufr"],
    37: ["dunya", "resurrection", "kufr"],
    38: ["kufr", "sidq"],
    39: ["dua", "prophethood"],
    40: ["warnings"],
    41: ["history_lessons"],
    42: ["history_lessons"],
    43: ["qadr", "time", "history_lessons"],
    44: ["prophethood", "history_lessons"],
    45: ["story_musa", "story_harun", "miracles"],
    46: ["story_musa", "kibr"],
    47: ["story_musa", "kibr", "oppression"],
    48: ["story_musa", "history_lessons"],
    49: ["story_musa", "revelation", "hidayah"],
    50: ["story_isa", "story_maryam", "miracles"],
    # 51–77 · One religion divided; those who hasten to good
    51: ["prophethood", "food_halal", "ihsan", "commands"],
    52: ["tawheed", "community", "taqwa"],
    53: ["community", "warnings"],
    54: ["warnings"],
    55: ["dunya", "wealth", "trial_test"],
    56: ["dunya", "trial_test"],
    57: ["taqwa", "iman"],
    58: ["iman"],
    59: ["tawheed", "iman"],
    60: ["zakat", "taqwa", "ikhlas", "akhirah"],
    61: ["ihsan", "iman"],
    62: ["adl", "akhirah"],
    63: ["kufr", "tazkiyah"],
    64: ["warnings", "dua"],
    65: ["akhirah", "warnings"],
    66: ["kufr", "quran_recitation"],
    67: ["kibr", "speech_ethics"],
    68: ["quran_recitation", "knowledge"],
    69: ["story_muhammad", "kufr"],
    70: ["story_muhammad", "kufr"],
    71: ["hidayah", "revelation", "tazkiyah"],
    72: ["story_muhammad", "ikhlas", "rizq"],
    73: ["dawah", "hidayah"],
    74: ["akhirah", "hidayah"],
    75: ["kufr", "rahmah"],
    76: ["trial_test", "kibr", "dua"],
    77: ["warnings", "hope_raja"],
    # 78–92 · Who owns the earth and the Throne? They admit: Allah
    78: ["human_creation", "shukr"],
    79: ["resurrection"],
    80: ["death_reminder", "nature_signs", "knowledge"],
    81: ["kufr"],
    82: ["resurrection", "kufr"],
    83: ["resurrection", "kufr"],
    84: ["tawheed"],
    85: ["tawheed", "dhikr"],
    86: ["tawheed"],
    87: ["tawheed", "taqwa"],
    88: ["tawheed", "tawakkul"],
    89: ["tawheed"],
    90: ["kufr", "sidq"],
    91: ["tawheed", "shirk"],
    92: ["tawheed", "knowledge", "shirk"],
    # 93–118 · Repel evil with good; the barzakh; how long did you stay?
    93: ["dua", "story_muhammad"],
    94: ["dua"],
    95: ["qadr"],
    96: ["hilm", "dawah", "ihsan"],
    97: ["dua", "shaytan"],
    98: ["dua", "shaytan"],
    99: ["death_reminder", "tawbah"],
    100: ["death_reminder", "resurrection"],
    101: ["resurrection", "akhirah", "family"],
    102: ["akhirah", "glad_tidings"],
    103: ["akhirah", "jahannam"],
    104: ["jahannam"],
    105: ["jahannam", "kufr"],
    106: ["jahannam", "hidayah"],
    107: ["jahannam", "dua"],
    108: ["jahannam"],
    109: ["iman", "dua", "rahmah"],
    110: ["speech_ethics", "kufr", "dhikr"],
    111: ["sabr", "glad_tidings"],
    112: ["akhirah", "time"],
    113: ["akhirah", "time"],
    114: ["dunya", "time"],
    115: ["purpose_of_life", "akhirah"],
    116: ["tawheed", "asma_ul_husna"],
    117: ["shirk", "akhirah"],
    118: ["dua", "tawbah", "rahmah"],
}
