"""24 · An-Nur · The Light · النور — 64 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · Punishment for zina, false accusation and li'an
    1: ["revelation", "commands"],
    2: ["criminal_law", "haya", "commands", "prohibitions"],
    3: ["marriage", "haya", "prohibitions"],
    4: ["criminal_law", "speech_ethics", "women", "haya"],
    5: ["tawbah", "rahmah"],
    6: ["marriage", "criminal_law", "sidq"],
    7: ["marriage", "sidq"],
    8: ["marriage", "sidq", "women"],
    9: ["marriage", "sidq"],
    10: ["rahmah", "tawbah"],
    # 11–26 · The slander against Aisha and its lessons
    11: ["incident_ifk", "speech_ethics", "trial_test"],
    12: ["incident_ifk", "speech_ethics", "iman", "community"],
    13: ["incident_ifk", "speech_ethics", "sidq"],
    14: ["incident_ifk", "rahmah"],
    15: ["incident_ifk", "speech_ethics", "knowledge"],
    16: ["incident_ifk", "speech_ethics", "dhikr"],
    17: ["incident_ifk", "warnings", "iman"],
    18: ["revelation", "knowledge"],
    19: ["haya", "speech_ethics", "warnings", "community"],
    20: ["incident_ifk", "rahmah"],
    21: ["o_believers", "shaytan", "tazkiyah", "haya"],
    22: ["incident_ifk", "hilm", "zakat", "family", "rahmah"],
    23: ["incident_ifk", "speech_ethics", "women", "warnings"],
    24: ["akhirah", "speech_ethics"],
    25: ["akhirah", "adl"],
    26: ["incident_ifk", "haya", "glad_tidings"],
    # 27–34 · Seeking permission, lowering the gaze, hijab and marriage
    27: ["o_believers", "adab", "commands"],
    28: ["adab", "tazkiyah", "commands"],
    29: ["adab"],
    30: ["haya", "commands", "tazkiyah"],
    31: ["haya", "women", "family", "tawbah", "commands"],
    32: ["marriage", "rizq", "commands"],
    33: ["marriage", "haya", "social_justice", "oppression", "prohibitions"],
    34: ["revelation", "history_lessons", "taqwa"],
    # 35–46 · Ayat an-Nur: light upon light; the mirage and the darkness
    35: ["asma_ul_husna", "parables", "hidayah", "tawheed"],  # Ayat an-Nur
    36: ["salah", "dhikr"],
    37: ["dhikr", "salah", "zakat", "dunya", "trade"],
    38: ["glad_tidings", "rizq"],
    39: ["parables", "kufr", "akhirah"],
    40: ["parables", "kufr", "hidayah"],
    41: ["nature_signs", "dhikr", "animals"],
    42: ["tawheed", "akhirah"],
    43: ["nature_signs"],
    44: ["nature_signs", "time"],
    45: ["animals", "nature_signs", "qadr"],
    46: ["revelation", "hidayah"],
    # 47–57 · Hypocrites vs. "we hear and we obey"; the promise of succession
    47: ["nifaq"],
    48: ["nifaq", "adl"],
    49: ["nifaq"],
    50: ["nifaq", "tazkiyah"],
    51: ["iman", "story_muhammad", "adl"],
    52: ["iman", "taqwa", "glad_tidings"],
    53: ["nifaq", "amanah"],
    54: ["story_muhammad", "commands", "dawah", "hidayah"],
    55: ["iman", "leadership", "glad_tidings", "tawheed", "anxiety_fear"],
    56: ["salah", "zakat", "story_muhammad", "commands"],
    57: ["kufr", "jahannam"],
    # 58–64 · Household etiquette, eating together, manners with the Messenger
    58: ["o_believers", "adab", "family", "haya", "commands"],
    59: ["adab", "parenting", "commands"],
    60: ["women", "haya"],
    61: ["family", "adab", "health", "commands"],
    62: ["iman", "adab", "story_muhammad", "leadership"],
    63: ["adab", "story_muhammad", "warnings"],
    64: ["tawheed", "knowledge", "akhirah"],
}
