"""25 · Al-Furqan · The Criterion · الفرقان — 77 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–20 · The Criterion sent down; the disbelievers' objections to a human messenger
    1: ["revelation", "story_muhammad", "dawah"],
    2: ["tawheed", "shirk", "qadr", "nature_signs"],
    3: ["shirk", "resurrection"],
    4: ["revelation", "kufr", "sidq"],
    5: ["revelation", "kufr"],
    6: ["revelation", "knowledge", "rahmah"],
    7: ["prophethood", "kufr", "angels"],
    8: ["prophethood", "kufr", "miracles"],
    9: ["kufr", "hidayah"],
    10: ["jannah", "qadr"],
    11: ["akhirah", "kufr", "jahannam"],
    12: ["jahannam"],
    13: ["jahannam"],
    14: ["jahannam"],
    15: ["jannah", "taqwa", "glad_tidings"],
    16: ["jannah", "glad_tidings"],
    17: ["akhirah", "shirk"],
    18: ["akhirah", "shirk", "dunya"],
    19: ["akhirah", "shirk", "oppression"],
    20: ["prophethood", "trial_test", "sabr"],
    # 21–34 · The Day angels descend; regret over a bad friend; the Quran abandoned
    21: ["kibr", "kufr", "angels"],
    22: ["akhirah", "angels", "kufr"],
    23: ["akhirah", "kufr"],
    24: ["jannah"],
    25: ["akhirah", "angels", "nature_signs"],
    26: ["akhirah", "asma_ul_husna", "kufr"],
    27: ["akhirah", "wala_bara", "story_muhammad"],
    28: ["akhirah", "wala_bara", "community"],
    29: ["shaytan", "dhikr", "wala_bara"],
    30: ["quran_recitation", "story_muhammad", "revelation"],
    31: ["prophethood", "hidayah", "tawakkul"],
    32: ["revelation", "story_muhammad"],
    33: ["revelation"],
    34: ["jahannam", "hidayah"],
    # 35–44 · Destroyed nations; taking desire as a god
    35: ["story_musa", "story_harun", "revelation"],
    36: ["story_musa", "history_lessons"],
    37: ["story_nuh", "history_lessons"],
    38: ["history_lessons"],
    39: ["history_lessons", "parables"],
    40: ["story_lut", "history_lessons", "resurrection"],
    41: ["story_muhammad", "speech_ethics", "kufr"],
    42: ["shirk", "hidayah"],
    43: ["tazkiyah", "shirk", "hidayah"],
    44: ["kufr", "knowledge"],
    # 45–62 · Shadow, night, rain and the two seas; strive with the Quran
    45: ["nature_signs"],
    46: ["nature_signs"],
    47: ["nature_signs", "time"],
    48: ["nature_signs", "rahmah"],
    49: ["nature_signs", "resurrection", "animals"],
    50: ["nature_signs", "kufr"],
    51: ["prophethood"],
    52: ["dawah", "revelation", "conflict"],
    53: ["nature_signs"],
    54: ["human_creation", "family", "marriage"],
    55: ["shirk", "kufr", "shaytan"],
    56: ["prophethood", "story_muhammad"],
    57: ["dawah", "ikhlas"],
    58: ["tawakkul", "dhikr", "asma_ul_husna"],
    59: ["nature_signs", "asma_ul_husna", "tawheed"],
    60: ["sajdah_tilawah", "kufr", "asma_ul_husna"],
    61: ["nature_signs"],
    62: ["nature_signs", "dhikr", "shukr", "time"],
    # 63–77 · The servants of the Most Merciful
    63: ["hilm", "kibr", "speech_ethics", "taqwa"],
    64: ["salah", "dhikr"],
    65: ["dua", "jahannam"],
    66: ["jahannam"],
    67: ["wealth", "iman"],
    68: ["shirk", "criminal_law", "haya", "prohibitions", "warnings"],
    69: ["jahannam", "warnings"],
    70: ["tawbah", "iman", "rahmah", "glad_tidings"],
    71: ["tawbah"],
    72: ["sidq", "speech_ethics"],
    73: ["quran_recitation", "iman"],
    74: ["dua", "family", "marriage", "parenting"],
    75: ["jannah", "sabr"],
    76: ["jannah"],
    77: ["dua", "kufr", "warnings"],
}
