"""26 · Ash-Shu'ara · The Poets · الشعراء — 227 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–9 · Grief over deniers; signs in the earth
    1: ["muqattaat"],
    2: ["revelation"],
    3: ["story_muhammad", "grief_loss"],
    4: ["qadr", "miracles"],
    5: ["revelation", "kufr"],
    6: ["kufr", "warnings"],
    7: ["nature_signs"],
    8: ["nature_signs", "kufr"],
    9: ["asma_ul_husna", "rahmah"],
    # 10–68 · Musa and Pharaoh
    10: ["story_musa", "oppression"],
    11: ["story_musa", "taqwa"],
    12: ["story_musa", "anxiety_fear"],
    13: ["story_musa", "story_harun", "anxiety_fear", "speech_ethics"],
    14: ["story_musa", "anxiety_fear"],
    15: ["story_musa", "story_harun", "tawakkul"],
    16: ["story_musa", "story_harun", "prophethood"],
    17: ["story_musa", "story_bani_israil"],
    18: ["story_musa"],
    19: ["story_musa"],
    20: ["story_musa", "tawbah"],
    21: ["story_musa", "prophethood", "knowledge"],
    22: ["story_musa", "story_bani_israil", "oppression"],
    23: ["story_musa", "tawheed"],
    24: ["story_musa", "tawheed"],
    25: ["story_musa"],
    26: ["story_musa", "tawheed"],
    27: ["story_musa", "speech_ethics"],
    28: ["story_musa", "tawheed", "knowledge"],
    29: ["story_musa", "kibr", "oppression"],
    30: ["story_musa", "miracles"],
    31: ["story_musa"],
    32: ["story_musa", "miracles"],
    33: ["story_musa", "miracles"],
    34: ["story_musa"],
    35: ["story_musa"],
    36: ["story_musa"],
    37: ["story_musa"],
    38: ["story_musa"],
    39: ["story_musa"],
    40: ["story_musa"],
    41: ["story_musa", "dunya"],
    42: ["story_musa"],
    43: ["story_musa"],
    44: ["story_musa", "shaytan"],
    45: ["story_musa", "miracles"],
    46: ["story_musa", "iman"],
    47: ["story_musa", "iman"],
    48: ["story_musa", "story_harun", "iman"],
    49: ["story_musa", "oppression"],
    50: ["story_musa", "sabr", "iman"],
    51: ["story_musa", "tawbah", "hope_raja"],
    52: ["story_musa", "story_bani_israil"],
    53: ["story_musa"],
    54: ["story_musa", "kibr"],
    55: ["story_musa"],
    56: ["story_musa"],
    57: ["story_musa", "history_lessons"],
    58: ["story_musa", "history_lessons"],
    59: ["story_bani_israil", "story_musa"],
    60: ["story_musa"],
    61: ["story_musa", "anxiety_fear"],
    62: ["story_musa", "tawakkul", "hidayah"],
    63: ["story_musa", "miracles"],
    64: ["story_musa"],
    65: ["story_musa", "miracles"],
    66: ["story_musa", "history_lessons"],
    67: ["history_lessons", "kufr"],
    68: ["asma_ul_husna", "rahmah"],
    # 69–104 · Ibrahim; the sound heart on the Day
    69: ["story_ibrahim"],
    70: ["story_ibrahim", "shirk", "parents"],
    71: ["story_ibrahim", "shirk"],
    72: ["story_ibrahim", "shirk", "dua"],
    73: ["story_ibrahim", "shirk"],
    74: ["story_ibrahim", "shirk", "hidayah"],
    75: ["story_ibrahim", "shirk"],
    76: ["story_ibrahim"],
    77: ["story_ibrahim", "wala_bara", "tawheed"],
    78: ["story_ibrahim", "human_creation", "hidayah"],
    79: ["story_ibrahim", "rizq"],
    80: ["story_ibrahim", "health"],
    81: ["story_ibrahim", "death_reminder", "resurrection"],
    82: ["story_ibrahim", "tawbah", "hope_raja", "akhirah"],
    83: ["story_ibrahim", "dua", "knowledge"],
    84: ["story_ibrahim", "dua"],
    85: ["story_ibrahim", "dua", "jannah"],
    86: ["story_ibrahim", "dua", "parents"],
    87: ["story_ibrahim", "dua", "akhirah"],
    88: ["akhirah", "wealth", "dunya"],
    89: ["akhirah", "tazkiyah"],
    90: ["jannah", "taqwa"],
    91: ["jahannam"],
    92: ["akhirah", "shirk"],
    93: ["shirk"],
    94: ["jahannam", "shirk"],
    95: ["shaytan", "jahannam"],
    96: ["jahannam"],
    97: ["jahannam", "shirk"],
    98: ["shirk"],
    99: ["jahannam", "leadership"],
    100: ["akhirah"],
    101: ["akhirah", "wala_bara"],
    102: ["akhirah", "iman"],
    103: ["history_lessons", "kufr"],
    104: ["asma_ul_husna", "rahmah"],
    # 105–122 · Nuh
    105: ["story_nuh", "kufr"],
    106: ["story_nuh", "taqwa"],
    107: ["story_nuh", "amanah", "prophethood"],
    108: ["story_nuh", "taqwa"],
    109: ["story_nuh", "ikhlas", "dawah"],
    110: ["story_nuh", "taqwa"],
    111: ["story_nuh", "kibr"],
    112: ["story_nuh"],
    113: ["story_nuh", "akhirah"],
    114: ["story_nuh", "iman"],
    115: ["story_nuh", "dawah"],
    116: ["story_nuh", "oppression"],
    117: ["story_nuh", "dua"],
    118: ["story_nuh", "dua"],
    119: ["story_nuh"],
    120: ["story_nuh", "history_lessons"],
    121: ["history_lessons", "kufr"],
    122: ["asma_ul_husna", "rahmah"],
    # 123–140 · Hud and 'Ad
    123: ["story_hud", "kufr"],
    124: ["story_hud", "taqwa"],
    125: ["story_hud", "amanah", "prophethood"],
    126: ["story_hud", "taqwa"],
    127: ["story_hud", "ikhlas"],
    128: ["story_hud", "dunya"],
    129: ["story_hud", "dunya", "death_reminder"],
    130: ["story_hud", "oppression"],
    131: ["story_hud", "taqwa"],
    132: ["story_hud", "taqwa", "shukr"],
    133: ["story_hud", "animals", "rizq"],
    134: ["story_hud", "rizq"],
    135: ["story_hud", "warnings"],
    136: ["story_hud", "kibr"],
    137: ["story_hud"],
    138: ["story_hud"],
    139: ["story_hud", "history_lessons"],
    140: ["asma_ul_husna", "rahmah"],
    # 141–159 · Salih and Thamud
    141: ["story_salih", "kufr"],
    142: ["story_salih", "taqwa"],
    143: ["story_salih", "amanah", "prophethood"],
    144: ["story_salih", "taqwa"],
    145: ["story_salih", "ikhlas"],
    146: ["story_salih", "dunya"],
    147: ["story_salih", "rizq"],
    148: ["story_salih", "rizq"],
    149: ["story_salih", "dunya"],
    150: ["story_salih", "taqwa"],
    151: ["story_salih", "leadership"],
    152: ["story_salih", "environment"],
    153: ["story_salih", "kufr"],
    154: ["story_salih", "miracles"],
    155: ["story_salih", "miracles", "animals"],
    156: ["story_salih", "warnings"],
    157: ["story_salih", "animals"],
    158: ["story_salih", "history_lessons"],
    159: ["asma_ul_husna", "rahmah"],
    # 160–175 · Lut
    160: ["story_lut", "kufr"],
    161: ["story_lut", "taqwa"],
    162: ["story_lut", "amanah", "prophethood"],
    163: ["story_lut", "taqwa"],
    164: ["story_lut", "ikhlas"],
    165: ["story_lut", "haya"],
    166: ["story_lut", "haya", "marriage"],
    167: ["story_lut", "oppression"],
    168: ["story_lut", "haya"],
    169: ["story_lut", "dua", "family"],
    170: ["story_lut", "family"],
    171: ["story_lut", "women"],
    172: ["story_lut", "history_lessons"],
    173: ["story_lut", "history_lessons"],
    174: ["history_lessons", "kufr"],
    175: ["asma_ul_husna", "rahmah"],
    # 176–191 · Shu'ayb and the people of the thicket
    176: ["story_shuayb", "kufr"],
    177: ["story_shuayb", "taqwa"],
    178: ["story_shuayb", "amanah", "prophethood"],
    179: ["story_shuayb", "taqwa"],
    180: ["story_shuayb", "ikhlas"],
    181: ["story_shuayb", "trade"],
    182: ["story_shuayb", "trade", "adl"],
    183: ["story_shuayb", "trade", "environment"],
    184: ["story_shuayb", "taqwa", "human_creation"],
    185: ["story_shuayb", "kufr"],
    186: ["story_shuayb", "kufr"],
    187: ["story_shuayb", "kufr"],
    188: ["story_shuayb"],
    189: ["story_shuayb", "history_lessons"],
    190: ["history_lessons", "kufr"],
    191: ["asma_ul_husna", "rahmah"],
    # 192–227 · The Trustworthy Spirit brought the Quran; the poets
    192: ["revelation"],
    193: ["revelation", "angels"],
    194: ["revelation", "story_muhammad"],
    195: ["revelation"],
    196: ["revelation", "ahl_al_kitab"],
    197: ["revelation", "ahl_al_kitab", "knowledge"],
    198: ["revelation"],
    199: ["revelation", "kufr"],
    200: ["kufr", "tazkiyah"],
    201: ["kufr", "warnings"],
    202: ["warnings"],
    203: ["akhirah"],
    204: ["warnings"],
    205: ["dunya"],
    206: ["dunya", "warnings"],
    207: ["dunya"],
    208: ["history_lessons", "prophethood"],
    209: ["adl"],
    210: ["revelation", "shaytan"],
    211: ["revelation", "shaytan"],
    212: ["shaytan", "jinn"],
    213: ["shirk", "prohibitions"],
    214: ["dawah", "family", "story_muhammad"],
    215: ["kibr", "adab", "story_muhammad"],
    216: ["dawah", "wala_bara"],
    217: ["tawakkul", "asma_ul_husna"],
    218: ["salah", "taqwa"],
    219: ["salah"],
    220: ["asma_ul_husna"],
    221: ["shaytan"],
    222: ["shaytan", "sidq"],
    223: ["shaytan", "sidq"],
    224: ["speech_ethics", "hidayah"],
    225: ["speech_ethics"],
    226: ["speech_ethics", "sidq"],
    227: ["iman", "dhikr", "oppression", "speech_ethics"],
}
