"""27 · An-Naml · The Ant · النمل — 93 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–6 · Guidance for believers certain of the Hereafter
    1: ["muqattaat", "revelation"],
    2: ["revelation", "hidayah", "glad_tidings"],
    3: ["iman", "salah", "zakat", "akhirah"],
    4: ["akhirah", "kufr", "hidayah"],
    5: ["akhirah", "warnings"],
    6: ["revelation", "story_muhammad"],
    # 7–14 · Musa at the fire and the nine signs
    7: ["story_musa", "family"],
    8: ["story_musa", "dhikr"],
    9: ["story_musa", "asma_ul_husna"],
    10: ["story_musa", "miracles", "anxiety_fear"],
    11: ["tawbah", "rahmah"],
    12: ["story_musa", "miracles"],
    13: ["story_musa", "kufr"],
    14: ["story_musa", "kibr", "oppression", "kufr"],
    # 15–44 · Sulayman, the ant, the hoopoe and the Queen of Saba
    15: ["story_dawud", "story_sulayman", "knowledge", "shukr"],
    16: ["story_sulayman", "story_dawud", "animals", "knowledge"],
    17: ["story_sulayman", "jinn", "animals", "leadership"],
    18: ["story_sulayman", "animals"],
    19: ["story_sulayman", "dua", "shukr", "parents"],
    20: ["story_sulayman", "animals", "leadership"],
    21: ["story_sulayman", "leadership", "adl"],
    22: ["story_sulayman", "animals", "knowledge"],
    23: ["story_sulayman", "women", "leadership"],
    24: ["story_sulayman", "shirk", "shaytan"],
    25: ["story_sulayman", "tawheed", "knowledge"],
    26: ["story_sulayman", "sajdah_tilawah", "tawheed"],
    27: ["story_sulayman", "sidq"],
    28: ["story_sulayman", "dawah"],
    29: ["story_sulayman", "women"],
    30: ["story_sulayman", "dawah", "rahmah"],
    31: ["story_sulayman", "dawah", "kibr"],
    32: ["story_sulayman", "shura", "women", "leadership"],
    33: ["story_sulayman", "shura", "leadership"],
    34: ["story_sulayman", "leadership", "oppression"],
    35: ["story_sulayman", "leadership"],
    36: ["story_sulayman", "wealth", "dunya"],
    37: ["story_sulayman", "conflict"],
    38: ["story_sulayman", "jinn"],
    39: ["story_sulayman", "jinn", "amanah"],
    40: ["story_sulayman", "knowledge", "shukr", "trial_test", "miracles"],
    41: ["story_sulayman", "hidayah"],
    42: ["story_sulayman", "knowledge", "iman"],
    43: ["story_sulayman", "shirk", "women"],
    44: ["story_sulayman", "women", "tawbah", "iman"],
    # 45–53 · Salih and the nine plotters
    45: ["story_salih", "tawheed", "community"],
    46: ["story_salih", "tawbah", "rahmah"],
    47: ["story_salih", "trial_test"],
    48: ["story_salih", "environment"],
    49: ["story_salih", "oppression", "sidq"],
    50: ["story_salih", "qadr"],
    51: ["story_salih", "history_lessons"],
    52: ["story_salih", "history_lessons"],
    53: ["story_salih", "iman", "taqwa"],
    # 54–58 · Lut
    54: ["story_lut", "haya"],
    55: ["story_lut", "haya"],
    56: ["story_lut", "oppression"],
    57: ["story_lut", "family", "women"],
    58: ["story_lut", "history_lessons"],
    # 59–66 · "Is there a deity with Allah?"
    59: ["dhikr", "tawheed", "shirk"],
    60: ["tawheed", "shirk", "nature_signs"],
    61: ["tawheed", "shirk", "nature_signs"],
    62: ["dua", "anxiety_fear", "tawheed", "shirk"],
    63: ["tawheed", "nature_signs", "hidayah", "shirk"],
    64: ["tawheed", "resurrection", "rizq", "shirk"],
    65: ["knowledge", "tawheed", "resurrection"],
    66: ["akhirah", "kufr"],
    # 67–81 · Doubts about resurrection; rely on Allah
    67: ["resurrection", "kufr"],
    68: ["resurrection", "kufr"],
    69: ["history_lessons"],
    70: ["story_muhammad", "grief_loss"],
    71: ["akhirah", "kufr"],
    72: ["akhirah", "warnings"],
    73: ["rahmah", "shukr"],
    74: ["taqwa", "knowledge"],
    75: ["knowledge", "qadr"],
    76: ["revelation", "story_bani_israil", "ahl_al_kitab"],
    77: ["revelation", "hidayah", "rahmah"],
    78: ["akhirah", "adl"],
    79: ["tawakkul", "story_muhammad"],
    80: ["hidayah", "dawah"],
    81: ["hidayah", "iman"],
    # 82–93 · The beast from the earth, the Horn, and the Lord of this city
    82: ["akhirah", "iman"],
    83: ["akhirah", "kufr"],
    84: ["akhirah", "kufr"],
    85: ["akhirah"],
    86: ["nature_signs", "iman"],
    87: ["resurrection", "akhirah"],
    88: ["akhirah", "nature_signs"],
    89: ["akhirah", "glad_tidings", "anxiety_fear"],
    90: ["jahannam", "adl"],
    91: ["kaaba", "tawheed", "iman", "commands"],
    92: ["quran_recitation", "hidayah", "dawah"],
    93: ["dhikr", "taqwa"],
}
