"""28 · Al-Qasas · The Stories · القصص — 88 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–13 · Pharaoh's tyranny; Musa cast into the river and returned to his mother
    1: ["muqattaat"],
    2: ["revelation"],
    3: ["story_musa", "revelation"],
    4: ["story_musa", "oppression", "kibr"],
    5: ["story_bani_israil", "oppression", "leadership"],
    6: ["story_bani_israil", "story_musa", "oppression"],
    7: ["story_musa", "parenting", "women", "tawakkul"],
    8: ["story_musa", "qadr"],
    9: ["story_musa", "women", "parenting"],
    10: ["story_musa", "parenting", "anxiety_fear", "iman"],
    11: ["story_musa", "family"],
    12: ["story_musa", "qadr"],
    13: ["story_musa", "parenting", "grief_loss"],
    # 14–28 · The killing, the flight to Madyan, marriage and work
    14: ["story_musa", "knowledge", "ihsan"],
    15: ["story_musa", "shaytan", "criminal_law"],
    16: ["story_musa", "tawbah", "dua", "rahmah"],
    17: ["story_musa", "shukr", "wala_bara"],
    18: ["story_musa", "anxiety_fear"],
    19: ["story_musa", "oppression"],
    20: ["story_musa"],
    21: ["story_musa", "dua", "anxiety_fear"],
    22: ["story_musa", "dua", "hidayah"],
    23: ["story_musa", "women", "ihsan"],
    24: ["story_musa", "dua", "rizq"],
    25: ["story_musa", "haya", "women"],
    26: ["story_musa", "work_ethics", "amanah"],
    27: ["story_musa", "marriage", "work_ethics"],
    28: ["story_musa", "amanah"],
    # 29–43 · The call at the mount; Pharaoh's tower and drowning
    29: ["story_musa", "family"],
    30: ["story_musa", "revelation", "tawheed"],
    31: ["story_musa", "miracles", "anxiety_fear"],
    32: ["story_musa", "miracles"],
    33: ["story_musa", "anxiety_fear"],
    34: ["story_musa", "story_harun", "speech_ethics"],
    35: ["story_musa", "story_harun", "tawakkul"],
    36: ["story_musa", "kufr"],
    37: ["story_musa", "hidayah"],
    38: ["story_musa", "shirk", "kibr"],
    39: ["story_musa", "kibr", "akhirah"],
    40: ["story_musa", "history_lessons"],
    41: ["story_musa", "leadership", "jahannam"],
    42: ["story_musa", "akhirah"],
    43: ["story_musa", "revelation", "hidayah"],
    # 44–59 · A mercy sent to an unwarned people; believers among the People of the Book
    44: ["story_muhammad", "revelation"],
    45: ["story_muhammad", "revelation"],
    46: ["story_muhammad", "rahmah", "dawah"],
    47: ["prophethood", "adl"],
    48: ["kufr", "revelation", "story_musa"],
    49: ["revelation", "hidayah"],
    50: ["tazkiyah", "hidayah"],
    51: ["revelation"],
    52: ["ahl_al_kitab", "iman"],
    53: ["ahl_al_kitab", "iman", "quran_recitation"],
    54: ["ahl_al_kitab", "sabr", "hilm", "zakat", "glad_tidings"],
    55: ["speech_ethics", "hilm", "adab"],
    56: ["hidayah", "story_muhammad", "qadr"],
    57: ["kaaba", "rizq", "anxiety_fear"],
    58: ["history_lessons", "dunya"],
    59: ["history_lessons", "adl", "prophethood"],
    # 60–75 · What is with Allah is better; night and day as mercy
    60: ["dunya", "akhirah"],
    61: ["dunya", "akhirah"],
    62: ["akhirah", "shirk"],
    63: ["akhirah", "leadership", "shirk"],
    64: ["akhirah", "shirk"],
    65: ["akhirah", "prophethood"],
    66: ["akhirah"],
    67: ["tawbah", "iman", "glad_tidings"],
    68: ["qadr", "tawheed"],
    69: ["taqwa", "knowledge"],
    70: ["tawheed", "dhikr", "akhirah"],
    71: ["nature_signs", "tawheed"],
    72: ["nature_signs", "tawheed"],
    73: ["nature_signs", "rahmah", "shukr", "work_ethics"],
    74: ["akhirah", "shirk"],
    75: ["akhirah", "prophethood"],
    # 76–84 · Qarun and his treasures
    76: ["story_musa", "wealth", "kibr", "love_of_allah"],
    77: ["akhirah", "dunya", "ihsan", "environment", "love_of_allah"],
    78: ["story_musa", "kibr", "wealth", "history_lessons"],
    79: ["story_musa", "dunya", "wealth"],
    80: ["story_musa", "knowledge", "sabr", "iman"],
    81: ["story_musa", "history_lessons"],
    82: ["story_musa", "rizq", "qadr"],
    83: ["akhirah", "kibr", "environment", "taqwa"],
    84: ["akhirah", "adl", "glad_tidings"],
    # 85–88 · The promised return; everything perishes except His Face
    85: ["story_muhammad", "hijrah", "revelation"],
    86: ["revelation", "rahmah", "wala_bara"],
    87: ["dawah", "shirk", "revelation"],
    88: ["tawheed", "death_reminder", "akhirah"],
}
