"""29 · Al-'Ankabut · The Spider · العنكبوت — 69 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–13 · Faith will be tested; parents who call to shirk
    1: ["muqattaat"],
    2: ["trial_test", "iman"],
    3: ["trial_test", "sidq", "history_lessons"],
    4: ["warnings"],
    5: ["akhirah", "hope_raja", "death_reminder"],
    6: ["tazkiyah"],
    7: ["iman", "glad_tidings", "rahmah"],
    8: ["parents", "shirk", "commands", "prohibitions"],
    9: ["iman", "jannah"],
    10: ["nifaq", "trial_test"],
    11: ["nifaq", "iman", "trial_test"],
    12: ["kufr", "akhirah"],
    13: ["akhirah", "warnings"],
    # 14–40 · Nuh, Ibrahim, Lut, Shu'ayb and the destroyed nations
    14: ["story_nuh", "history_lessons", "sabr"],
    15: ["story_nuh", "miracles"],
    16: ["story_ibrahim", "tawheed", "taqwa"],
    17: ["story_ibrahim", "shirk", "rizq", "shukr"],
    18: ["dawah", "history_lessons"],
    19: ["resurrection", "human_creation"],
    20: ["resurrection", "nature_signs", "knowledge"],
    21: ["rahmah", "akhirah"],
    22: ["tawakkul", "wala_bara"],
    23: ["kufr", "hope_raja", "akhirah"],
    24: ["story_ibrahim", "miracles", "oppression"],
    25: ["story_ibrahim", "shirk", "akhirah", "community"],
    26: ["story_lut", "story_ibrahim", "hijrah", "iman"],
    27: ["story_ibrahim", "story_ishaq", "story_yaqub", "prophethood"],
    28: ["story_lut", "haya"],
    29: ["story_lut", "haya", "oppression"],
    30: ["story_lut", "dua"],
    31: ["story_ibrahim", "angels", "story_lut"],
    32: ["story_ibrahim", "story_lut", "angels"],
    33: ["story_lut", "angels", "anxiety_fear"],
    34: ["story_lut", "history_lessons"],
    35: ["history_lessons", "knowledge"],
    36: ["story_shuayb", "tawheed", "akhirah", "environment"],
    37: ["story_shuayb", "history_lessons"],
    38: ["history_lessons", "shaytan"],
    39: ["story_musa", "kibr", "history_lessons"],
    40: ["history_lessons", "adl"],
    # 41–55 · The spider's house; prayer restrains immorality; arguing with the People of the Book
    41: ["parables", "shirk", "wala_bara", "animals"],
    42: ["shirk", "knowledge"],
    43: ["parables", "knowledge"],
    44: ["nature_signs", "iman"],
    45: ["salah", "quran_recitation", "dhikr", "tazkiyah", "commands"],
    46: ["ahl_al_kitab", "dawah", "speech_ethics", "tawheed"],
    47: ["revelation", "ahl_al_kitab", "iman"],
    48: ["story_muhammad", "revelation"],
    49: ["revelation", "knowledge", "quran_recitation"],
    50: ["miracles", "prophethood"],
    51: ["revelation", "rahmah"],
    52: ["kufr", "tawakkul"],
    53: ["warnings", "time"],
    54: ["jahannam"],
    55: ["jahannam"],
    # 56–69 · My earth is spacious; worldly life is play; those who strive are guided
    56: ["hijrah", "tawheed", "commands"],
    57: ["death_reminder", "akhirah"],
    58: ["jannah", "iman", "glad_tidings"],
    59: ["sabr", "tawakkul"],
    60: ["rizq", "animals", "tawakkul"],
    61: ["tawheed", "nature_signs"],
    62: ["rizq", "qadr"],
    63: ["tawheed", "nature_signs", "dhikr"],
    64: ["dunya", "akhirah"],
    65: ["dua", "ikhlas", "shirk"],
    66: ["shukr", "kufr"],
    67: ["kaaba", "shukr", "anxiety_fear"],
    68: ["sidq", "kufr", "jahannam"],
    69: ["tazkiyah", "hidayah", "ihsan"],
}
