"""30 · Ar-Rum · The Romans · الروم — 60 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · The Romans' defeat and promised victory; they know only this world
    1: ["muqattaat"],
    2: ["history_lessons", "qadr"],
    3: ["qadr", "history_lessons"],
    4: ["qadr", "time"],
    5: ["qadr", "rahmah"],
    6: ["qadr", "iman"],
    7: ["dunya", "akhirah"],
    8: ["nature_signs", "purpose_of_life", "akhirah", "knowledge"],
    9: ["history_lessons"],
    10: ["history_lessons", "kufr"],
    # 11–19 · The Hour separates people; glorify Allah morning and evening
    11: ["resurrection", "human_creation"],
    12: ["akhirah"],
    13: ["akhirah", "shirk"],
    14: ["akhirah"],
    15: ["jannah", "iman"],
    16: ["kufr", "akhirah"],
    17: ["dhikr", "salah", "time"],
    18: ["dhikr", "salah", "time"],
    19: ["resurrection", "nature_signs"],
    # 20–27 · "And of His signs…": creation, spouses, languages, sleep, lightning
    20: ["human_creation", "nature_signs"],
    21: ["marriage", "nature_signs", "family"],
    22: ["nature_signs", "human_creation", "knowledge"],
    23: ["nature_signs", "work_ethics"],
    24: ["nature_signs", "resurrection"],
    25: ["nature_signs", "resurrection"],
    26: ["tawheed"],
    27: ["resurrection", "asma_ul_husna"],
    # 28–40 · The fitrah of Allah; giving to kin; riba vs. zakah
    28: ["parables", "shirk"],
    29: ["tazkiyah", "hidayah", "shirk"],
    30: ["tawheed", "human_creation", "iman", "commands"],
    31: ["tawbah", "taqwa", "salah", "shirk", "commands"],
    32: ["community", "shirk", "prohibitions"],
    33: ["dua", "shirk", "shukr"],
    34: ["shukr", "warnings"],
    35: ["shirk"],
    36: ["shukr", "hope_raja", "human_creation"],
    37: ["rizq", "qadr"],
    38: ["family", "social_justice", "zakat", "ikhlas", "commands"],
    39: ["riba", "zakat", "ikhlas"],
    40: ["tawheed", "rizq", "death_reminder", "resurrection", "shirk"],
    # 41–53 · Corruption on land and sea; winds and rain as mercy
    41: ["environment", "tawbah", "history_lessons"],
    42: ["history_lessons", "shirk"],
    43: ["iman", "akhirah", "commands"],
    44: ["kufr", "iman"],
    45: ["iman", "rahmah", "love_of_allah"],
    46: ["nature_signs", "rahmah", "shukr"],
    47: ["prophethood", "history_lessons", "glad_tidings"],
    48: ["nature_signs", "rahmah"],
    49: ["hope_raja"],
    50: ["nature_signs", "resurrection", "rahmah"],
    51: ["kufr", "shukr"],
    52: ["hidayah", "dawah"],
    53: ["hidayah", "iman"],
    # 54–60 · Weakness, strength, weakness; be patient, the promise is true
    54: ["human_creation", "death_reminder", "time"],
    55: ["akhirah", "time"],
    56: ["akhirah", "knowledge", "iman"],
    57: ["akhirah"],
    58: ["revelation", "parables", "kufr"],
    59: ["tazkiyah", "kufr"],
    60: ["sabr", "iman", "story_muhammad"],
}
