"""33 · Al-Ahzab · The Combined Forces · الأحزاب — 73 ayaat (medinan)"""

STATUS = "deep"

TAGS = {
    # 1–8 · Rely on Allah; adoption and zihar abolished; the Prophet closer than oneself
    1: ["story_muhammad", "taqwa", "nifaq", "prohibitions"],
    2: ["revelation", "commands"],
    3: ["tawakkul", "commands"],
    4: ["family", "marriage", "sidq"],
    5: ["family", "adl", "commands"],
    6: ["story_muhammad", "prophets_household", "inheritance", "family"],
    7: ["prophethood", "amanah", "story_muhammad"],
    8: ["sidq", "kufr"],
    # 9–27 · The Confederates and the siege of Madinah
    9: ["o_believers", "battle_ahzab", "angels", "shukr"],
    10: ["battle_ahzab", "anxiety_fear", "trial_test"],
    11: ["battle_ahzab", "trial_test"],
    12: ["battle_ahzab", "nifaq"],
    13: ["battle_ahzab", "nifaq"],
    14: ["battle_ahzab", "nifaq"],
    15: ["battle_ahzab", "amanah", "nifaq"],
    16: ["battle_ahzab", "death_reminder", "qadr"],
    17: ["tawakkul", "qadr", "wala_bara"],
    18: ["battle_ahzab", "nifaq"],
    19: ["battle_ahzab", "nifaq", "speech_ethics", "anxiety_fear"],
    20: ["battle_ahzab", "nifaq"],
    21: ["story_muhammad", "battle_ahzab", "hope_raja", "dhikr", "akhirah"],  # Uswatun hasana
    22: ["battle_ahzab", "iman", "sidq"],
    23: ["battle_ahzab", "sidq", "amanah", "sahabah"],
    24: ["sidq", "nifaq", "tawbah"],
    25: ["battle_ahzab", "tawakkul", "conflict"],
    26: ["battle_ahzab", "ahl_al_kitab", "conflict"],
    27: ["battle_ahzab", "conflict"],
    # 28–35 · The Prophet's wives; Muslim men and women alike
    28: ["prophets_household", "dunya", "divorce"],
    29: ["prophets_household", "akhirah", "ihsan"],
    30: ["prophets_household", "warnings", "haya"],
    31: ["prophets_household", "glad_tidings"],
    32: ["prophets_household", "haya", "speech_ethics", "women"],
    33: ["prophets_household", "haya", "salah", "zakat", "tazkiyah", "women"],
    34: ["prophets_household", "quran_recitation", "knowledge"],
    35: ["women", "iman", "sidq", "sabr", "zakat", "dhikr", "glad_tidings"],
    # 36–48 · Zayd and Zaynab; the Seal of the Prophets; remember Allah much
    36: ["iman", "story_muhammad", "commands", "hidayah"],
    37: ["story_muhammad", "prophets_household", "marriage", "divorce", "family", "taqwa"],
    38: ["story_muhammad", "prophethood", "qadr"],
    39: ["prophethood", "dawah", "taqwa"],
    40: ["story_muhammad", "prophethood", "family"],
    41: ["o_believers", "dhikr", "commands"],
    42: ["dhikr", "time"],
    43: ["rahmah", "angels", "hidayah"],
    44: ["jannah", "akhirah"],
    45: ["story_muhammad", "prophethood", "dawah"],
    46: ["story_muhammad", "dawah", "hidayah"],
    47: ["glad_tidings", "iman"],
    48: ["nifaq", "tawakkul", "prohibitions"],
    # 49–59 · Marriage rulings, etiquette in the Prophet's house, salawat and the jilbab
    49: ["o_believers", "divorce", "women", "ihsan"],
    50: ["story_muhammad", "prophets_household", "marriage"],
    51: ["prophets_household", "marriage"],
    52: ["prophets_household", "marriage"],
    53: ["o_believers", "adab", "story_muhammad", "prophets_household", "haya"],
    54: ["taqwa", "knowledge"],
    55: ["women", "haya", "family"],
    56: ["story_muhammad", "o_believers", "dua", "angels", "commands"],
    57: ["story_muhammad", "warnings"],
    58: ["speech_ethics", "oppression", "women"],
    59: ["women", "haya", "prophets_household", "commands"],
    # 60–73 · Rumour-mongers warned; the Hour; the Trust borne by man
    60: ["nifaq", "speech_ethics", "warnings"],
    61: ["nifaq", "warnings"],
    62: ["history_lessons", "qadr"],
    63: ["they_ask_you", "akhirah", "knowledge"],
    64: ["kufr", "jahannam"],
    65: ["jahannam"],
    66: ["jahannam", "story_muhammad"],
    67: ["jahannam", "leadership", "hidayah"],
    68: ["jahannam"],
    69: ["o_believers", "story_musa", "speech_ethics"],
    70: ["o_believers", "taqwa", "sidq", "speech_ethics", "commands"],
    71: ["tawbah", "glad_tidings"],
    72: ["amanah", "human_creation", "purpose_of_life"],
    73: ["nifaq", "shirk", "tawbah", "women"],
}
