"""36 · Ya-Sin · Ya Sin · يس — 83 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–12 · By the wise Quran; the record of what they left behind
    1: ["muqattaat"],
    2: ["revelation", "oaths"],
    3: ["story_muhammad", "prophethood"],
    4: ["story_muhammad", "hidayah"],
    5: ["revelation", "asma_ul_husna"],
    6: ["dawah", "revelation"],
    7: ["kufr", "qadr"],
    8: ["kufr"],
    9: ["kufr", "hidayah"],
    10: ["kufr", "dawah"],
    11: ["dawah", "taqwa", "glad_tidings"],
    12: ["resurrection", "akhirah", "qadr"],
    # 13–32 · The people of the town and the man who came running
    13: ["parables", "prophethood", "history_lessons"],
    14: ["prophethood", "history_lessons"],
    15: ["prophethood", "kufr"],
    16: ["prophethood"],
    17: ["dawah"],
    18: ["kufr", "oppression"],
    19: ["kufr", "dawah"],
    20: ["dawah", "iman"],
    21: ["dawah", "ikhlas", "hidayah"],
    22: ["tawheed", "dawah"],
    23: ["shirk", "akhirah"],
    24: ["shirk", "hidayah"],
    25: ["iman", "dawah"],
    26: ["jannah", "dawah"],
    27: ["jannah", "rahmah"],
    28: ["history_lessons"],
    29: ["history_lessons"],
    30: ["prophethood", "speech_ethics", "kufr"],
    31: ["history_lessons"],
    32: ["akhirah"],
    # 33–47 · Signs: the dead earth, night, sun and moon in orbit, the laden ship
    33: ["nature_signs", "resurrection", "rizq"],
    34: ["nature_signs"],
    35: ["nature_signs", "shukr"],
    36: ["nature_signs", "tawheed"],
    37: ["nature_signs"],
    38: ["nature_signs", "qadr"],
    39: ["nature_signs", "time"],
    40: ["nature_signs"],
    41: ["nature_signs", "story_nuh"],
    42: ["nature_signs"],
    43: ["qadr", "warnings"],
    44: ["rahmah"],
    45: ["taqwa", "warnings"],
    46: ["kufr"],
    47: ["zakat", "kufr", "social_justice"],
    # 48–68 · The single blast; people of Paradise and the criminals set apart
    48: ["akhirah", "kufr"],
    49: ["akhirah"],
    50: ["akhirah"],
    51: ["resurrection", "akhirah"],
    52: ["resurrection", "death_reminder"],
    53: ["resurrection", "akhirah"],
    54: ["akhirah", "adl"],
    55: ["jannah"],
    56: ["jannah", "marriage"],
    57: ["jannah"],
    58: ["jannah", "rahmah"],
    59: ["akhirah"],
    60: ["shaytan", "tawheed", "amanah"],
    61: ["tawheed", "hidayah"],
    62: ["shaytan", "knowledge"],
    63: ["jahannam"],
    64: ["jahannam", "kufr"],
    65: ["akhirah"],
    66: ["qadr", "warnings"],
    67: ["qadr", "warnings"],
    68: ["human_creation", "time", "knowledge"],
    # 69–83 · Not poetry; who will revive the bones? "Be," and it is
    69: ["story_muhammad", "revelation"],
    70: ["revelation", "dawah"],
    71: ["animals", "shukr"],
    72: ["animals", "food_halal"],
    73: ["animals", "shukr"],
    74: ["shirk"],
    75: ["shirk"],
    76: ["story_muhammad", "grief_loss", "knowledge"],
    77: ["human_creation", "kufr"],
    78: ["resurrection", "kufr", "human_creation"],
    79: ["resurrection", "human_creation"],
    80: ["nature_signs"],
    81: ["resurrection", "nature_signs"],
    82: ["qadr", "tawheed", "asma_ul_husna"],
    83: ["tawheed", "dhikr", "akhirah"],
}
