"""37 · As-Saffat · Those who set the Ranks · الصافات — 182 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · Oaths by the ranks of angels; the guarded heaven
    1: ["oaths", "angels"],
    2: ["oaths", "angels"],
    3: ["oaths", "angels", "revelation"],
    4: ["tawheed"],
    5: ["tawheed", "nature_signs"],
    6: ["nature_signs"],
    7: ["nature_signs", "shaytan"],
    8: ["shaytan", "angels"],
    9: ["shaytan"],
    10: ["shaytan", "nature_signs"],
    # 11–39 · Mockery of resurrection; followers and leaders blame each other
    11: ["human_creation", "resurrection"],
    12: ["kufr", "speech_ethics"],
    13: ["kufr"],
    14: ["kufr", "miracles"],
    15: ["kufr"],
    16: ["resurrection", "kufr"],
    17: ["resurrection", "kufr"],
    18: ["resurrection"],
    19: ["resurrection", "akhirah"],
    20: ["akhirah"],
    21: ["akhirah"],
    22: ["akhirah", "shirk"],
    23: ["jahannam", "shirk"],
    24: ["akhirah"],
    25: ["akhirah"],
    26: ["akhirah"],
    27: ["akhirah"],
    28: ["akhirah", "leadership"],
    29: ["akhirah", "leadership", "kufr"],
    30: ["akhirah", "leadership"],
    31: ["akhirah"],
    32: ["akhirah", "hidayah"],
    33: ["akhirah", "jahannam"],
    34: ["adl", "warnings"],
    35: ["kibr", "tawheed"],
    36: ["shirk", "story_muhammad"],
    37: ["story_muhammad", "prophethood"],
    38: ["jahannam", "warnings"],
    39: ["adl"],
    # 40–74 · The chosen servants in Paradise; the tree of zaqqum
    40: ["ikhlas"],
    41: ["jannah", "rizq"],
    42: ["jannah"],
    43: ["jannah"],
    44: ["jannah"],
    45: ["jannah"],
    46: ["jannah"],
    47: ["jannah", "food_halal"],
    48: ["jannah"],
    49: ["jannah"],
    50: ["jannah"],
    51: ["jannah", "wala_bara"],
    52: ["resurrection", "kufr"],
    53: ["resurrection", "kufr"],
    54: ["jannah", "jahannam"],
    55: ["jahannam"],
    56: ["wala_bara", "hidayah"],
    57: ["rahmah", "shukr"],
    58: ["jannah", "death_reminder"],
    59: ["jannah", "death_reminder"],
    60: ["jannah", "glad_tidings"],
    61: ["jannah", "ihsan"],
    62: ["jannah", "jahannam"],
    63: ["jahannam", "trial_test"],
    64: ["jahannam"],
    65: ["jahannam", "shaytan"],
    66: ["jahannam"],
    67: ["jahannam"],
    68: ["jahannam"],
    69: ["hidayah"],
    70: ["hidayah", "history_lessons"],
    71: ["history_lessons"],
    72: ["prophethood"],
    73: ["history_lessons", "warnings"],
    74: ["ikhlas"],
    # 75–82 · Nuh
    75: ["story_nuh", "dua"],
    76: ["story_nuh", "family"],
    77: ["story_nuh"],
    78: ["story_nuh"],
    79: ["story_nuh"],
    80: ["story_nuh", "ihsan"],
    81: ["story_nuh", "iman"],
    82: ["story_nuh", "history_lessons"],
    # 83–113 · Ibrahim breaks the idols; the sacrifice of his son
    83: ["story_ibrahim", "story_nuh"],
    84: ["story_ibrahim", "tazkiyah", "ikhlas"],
    85: ["story_ibrahim", "shirk", "parents"],
    86: ["story_ibrahim", "shirk"],
    87: ["story_ibrahim", "tawheed"],
    88: ["story_ibrahim", "nature_signs"],
    89: ["story_ibrahim"],
    90: ["story_ibrahim"],
    91: ["story_ibrahim", "shirk"],
    92: ["story_ibrahim", "shirk"],
    93: ["story_ibrahim", "shirk"],
    94: ["story_ibrahim"],
    95: ["story_ibrahim", "shirk"],
    96: ["story_ibrahim", "tawheed", "qadr"],
    97: ["story_ibrahim", "oppression"],
    98: ["story_ibrahim", "miracles"],
    99: ["story_ibrahim", "hidayah", "tawakkul"],
    100: ["story_ibrahim", "dua", "parenting"],
    101: ["story_ibrahim", "story_ismail", "glad_tidings", "hilm"],
    102: ["story_ibrahim", "story_ismail", "trial_test", "sabr", "parenting"],
    103: ["story_ibrahim", "story_ismail", "trial_test", "iman"],
    104: ["story_ibrahim", "story_ismail"],
    105: ["story_ibrahim", "ihsan"],
    106: ["story_ibrahim", "trial_test"],
    107: ["story_ibrahim", "story_ismail", "hajj"],
    108: ["story_ibrahim"],
    109: ["story_ibrahim"],
    110: ["story_ibrahim", "ihsan"],
    111: ["story_ibrahim", "iman"],
    112: ["story_ishaq", "story_ibrahim", "glad_tidings", "prophethood"],
    113: ["story_ishaq", "story_ibrahim", "ihsan", "oppression"],
    # 114–122 · Musa and Harun
    114: ["story_musa", "story_harun"],
    115: ["story_musa", "story_harun", "story_bani_israil"],
    116: ["story_musa", "story_harun"],
    117: ["story_musa", "story_harun", "revelation"],
    118: ["story_musa", "story_harun", "hidayah"],
    119: ["story_musa", "story_harun"],
    120: ["story_musa", "story_harun"],
    121: ["story_musa", "story_harun", "ihsan"],
    122: ["story_musa", "story_harun", "iman"],
    # 123–132 · Ilyas
    123: ["story_ilyas", "prophethood"],
    124: ["story_ilyas", "taqwa"],
    125: ["story_ilyas", "shirk"],
    126: ["story_ilyas", "tawheed"],
    127: ["story_ilyas", "kufr"],
    128: ["story_ilyas", "ikhlas"],
    129: ["story_ilyas"],
    130: ["story_ilyas"],
    131: ["story_ilyas", "ihsan"],
    132: ["story_ilyas", "iman"],
    # 133–138 · Lut
    133: ["story_lut", "prophethood"],
    134: ["story_lut", "family"],
    135: ["story_lut", "women"],
    136: ["story_lut", "history_lessons"],
    137: ["story_lut", "history_lessons"],
    138: ["history_lessons", "knowledge"],
    # 139–148 · Yunus and the whale
    139: ["story_yunus", "prophethood"],
    140: ["story_yunus"],
    141: ["story_yunus"],
    142: ["story_yunus", "animals"],
    143: ["story_yunus", "dhikr"],
    144: ["story_yunus", "dhikr", "resurrection"],
    145: ["story_yunus", "health", "rahmah"],
    146: ["story_yunus", "rahmah"],
    147: ["story_yunus", "dawah"],
    148: ["story_yunus", "iman", "tawbah"],
    # 149–182 · Refuting 'daughters of Allah'; peace upon the messengers
    149: ["shirk", "angels", "women"],
    150: ["shirk", "angels"],
    151: ["shirk", "sidq"],
    152: ["shirk", "sidq"],
    153: ["shirk"],
    154: ["shirk", "knowledge"],
    155: ["shirk"],
    156: ["shirk"],
    157: ["shirk", "revelation"],
    158: ["shirk", "jinn"],
    159: ["tawheed", "dhikr"],
    160: ["ikhlas"],
    161: ["shirk"],
    162: ["shirk", "hidayah"],
    163: ["jahannam"],
    164: ["angels"],
    165: ["angels", "salah"],
    166: ["angels", "dhikr"],
    167: ["kufr"],
    168: ["kufr"],
    169: ["kufr"],
    170: ["kufr", "warnings"],
    171: ["prophethood", "qadr"],
    172: ["prophethood", "glad_tidings"],
    173: ["prophethood", "conflict", "glad_tidings"],
    174: ["story_muhammad", "sabr"],
    175: ["story_muhammad", "warnings"],
    176: ["warnings"],
    177: ["warnings"],
    178: ["story_muhammad", "sabr"],
    179: ["warnings"],
    180: ["tawheed", "dhikr"],
    181: ["prophethood", "dhikr"],
    182: ["dhikr", "shukr"],
}
