"""38 · Sad · The Letter "Saad" · ص — 88 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–16 · Pride and dissension; the destroyed factions
    1: ["muqattaat", "oaths", "revelation"],
    2: ["kufr", "kibr"],
    3: ["history_lessons"],
    4: ["kufr", "prophethood"],
    5: ["shirk", "tawheed", "kufr"],
    6: ["shirk", "leadership"],
    7: ["kufr"],
    8: ["kufr", "revelation"],
    9: ["rahmah", "asma_ul_husna"],
    10: ["tawheed"],
    11: ["kufr"],
    12: ["history_lessons"],
    13: ["history_lessons"],
    14: ["history_lessons", "prophethood"],
    15: ["akhirah"],
    16: ["akhirah", "kufr"],
    # 17–29 · Dawud: the mountains glorify with him; the two litigants
    17: ["story_dawud", "sabr", "tawbah"],
    18: ["story_dawud", "dhikr", "nature_signs"],
    19: ["story_dawud", "dhikr", "animals"],
    20: ["story_dawud", "leadership", "knowledge", "speech_ethics"],
    21: ["story_dawud", "adl"],
    22: ["story_dawud", "adl", "anxiety_fear"],
    23: ["story_dawud", "oppression"],
    24: ["story_dawud", "oppression", "tawbah", "trial_test", "sajdah_tilawah"],
    25: ["story_dawud", "rahmah"],
    26: ["story_dawud", "leadership", "adl", "tazkiyah", "akhirah"],
    27: ["purpose_of_life", "nature_signs", "kufr"],
    28: ["adl", "iman", "taqwa"],
    29: ["revelation", "quran_recitation", "knowledge"],
    # 30–40 · Sulayman: the horses, the trial and a kingdom like no other
    30: ["story_sulayman", "story_dawud", "tawbah"],
    31: ["story_sulayman", "animals"],
    32: ["story_sulayman", "dhikr", "dunya"],
    33: ["story_sulayman", "animals"],
    34: ["story_sulayman", "trial_test"],
    35: ["story_sulayman", "dua", "tawbah", "leadership"],
    36: ["story_sulayman", "miracles", "nature_signs"],
    37: ["story_sulayman", "jinn", "shaytan"],
    38: ["story_sulayman", "jinn"],
    39: ["story_sulayman", "rizq"],
    40: ["story_sulayman", "glad_tidings"],
    # 41–48 · Ayyub's patience; Ibrahim, Ishaq, Yaqub, Ismail, Al-Yasa, Dhul-Kifl
    41: ["story_ayyub", "dua", "shaytan", "health"],
    42: ["story_ayyub", "health", "miracles"],
    43: ["story_ayyub", "rahmah", "family"],
    44: ["story_ayyub", "sabr", "amanah", "tawbah"],
    45: ["story_ibrahim", "story_ishaq", "story_yaqub", "knowledge"],
    46: ["prophethood", "akhirah", "ikhlas"],
    47: ["prophethood"],
    48: ["story_ismail", "story_alyasa", "story_dhulkifl", "prophethood"],
    # 49–64 · The good return and the evil return; quarrels in the Fire
    49: ["taqwa", "glad_tidings"],
    50: ["jannah"],
    51: ["jannah"],
    52: ["jannah"],
    53: ["jannah", "akhirah"],
    54: ["jannah", "rizq"],
    55: ["jahannam"],
    56: ["jahannam"],
    57: ["jahannam"],
    58: ["jahannam"],
    59: ["jahannam"],
    60: ["jahannam", "leadership"],
    61: ["jahannam"],
    62: ["jahannam", "kibr"],
    63: ["jahannam", "speech_ethics"],
    64: ["jahannam"],
    # 65–88 · The great news; Iblis refuses to prostrate and vows to mislead
    65: ["story_muhammad", "tawheed", "asma_ul_husna"],
    66: ["tawheed", "asma_ul_husna"],
    67: ["revelation"],
    68: ["kufr"],
    69: ["story_adam", "angels", "revelation"],
    70: ["story_muhammad", "prophethood"],
    71: ["story_adam", "angels", "human_creation"],
    72: ["story_adam", "angels", "human_creation"],
    73: ["story_adam", "angels"],
    74: ["story_adam", "shaytan", "kibr"],
    75: ["story_adam", "shaytan", "kibr"],
    76: ["story_adam", "shaytan", "kibr"],
    77: ["story_adam", "shaytan"],
    78: ["shaytan"],
    79: ["shaytan"],
    80: ["shaytan"],
    81: ["shaytan", "akhirah"],
    82: ["shaytan", "hidayah"],
    83: ["shaytan", "ikhlas"],
    84: ["shaytan", "sidq"],
    85: ["shaytan", "jahannam"],
    86: ["story_muhammad", "ikhlas"],
    87: ["revelation"],
    88: ["revelation", "warnings"],
}
