"""39 · Az-Zumar · The Troops · الزمر — 75 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–9 · Sincere religion is for Allah; creation in the three darknesses
    1: ["revelation", "asma_ul_husna"],
    2: ["revelation", "ikhlas", "commands"],
    3: ["ikhlas", "shirk", "akhirah"],
    4: ["tawheed", "shirk", "asma_ul_husna"],
    5: ["nature_signs", "asma_ul_husna"],
    6: ["human_creation", "animals", "tawheed"],
    7: ["kufr", "shukr", "adl", "akhirah"],
    8: ["dua", "shukr", "shirk", "warnings"],
    9: ["knowledge", "salah", "taqwa", "hope_raja"],
    # 10–20 · The patient rewarded without account; those who follow the best speech
    10: ["sabr", "taqwa", "ihsan", "hijrah", "glad_tidings"],
    11: ["ikhlas", "story_muhammad"],
    12: ["iman", "story_muhammad"],
    13: ["akhirah", "taqwa"],
    14: ["ikhlas", "tawheed"],
    15: ["akhirah", "family", "warnings"],
    16: ["jahannam", "taqwa"],
    17: ["shirk", "tawbah", "glad_tidings"],
    18: ["hidayah", "knowledge", "speech_ethics"],
    19: ["jahannam", "hidayah"],
    20: ["jannah", "taqwa"],
    # 21–35 · The best statement makes skins shiver; parable of the slave with many owners
    21: ["nature_signs", "dunya", "knowledge"],
    22: ["hidayah", "tazkiyah", "dhikr", "iman"],
    23: ["revelation", "quran_recitation", "taqwa", "tazkiyah", "hidayah"],
    24: ["jahannam", "akhirah"],
    25: ["history_lessons"],
    26: ["history_lessons", "akhirah"],
    27: ["revelation", "parables"],
    28: ["revelation", "taqwa"],
    29: ["parables", "tawheed", "shirk"],
    30: ["death_reminder", "story_muhammad"],
    31: ["akhirah"],
    32: ["sidq", "kufr", "jahannam"],
    33: ["sidq", "taqwa", "iman"],
    34: ["jannah", "ihsan"],
    35: ["rahmah", "glad_tidings"],
    # 36–52 · Is not Allah sufficient? Souls taken in sleep; intercession belongs to Allah
    36: ["tawakkul", "tawheed", "story_muhammad", "hidayah"],
    37: ["hidayah", "asma_ul_husna"],
    38: ["tawakkul", "tawheed", "shirk"],
    39: ["dawah", "warnings"],
    40: ["warnings"],
    41: ["revelation", "hidayah"],
    42: ["death_reminder", "nature_signs", "knowledge"],
    43: ["shirk"],
    44: ["akhirah", "tawheed"],
    45: ["tawheed", "shirk", "tazkiyah"],
    46: ["dua", "asma_ul_husna", "akhirah"],
    47: ["akhirah", "oppression"],
    48: ["akhirah"],
    49: ["dua", "kibr", "trial_test"],
    50: ["history_lessons"],
    51: ["history_lessons", "warnings"],
    52: ["rizq", "qadr"],
    # 53–61 · Do not despair of the mercy of Allah
    53: ["hope_raja", "tawbah", "rahmah"],  # La taqnatu
    54: ["tawbah", "commands", "warnings"],
    55: ["revelation", "commands"],
    56: ["akhirah"],
    57: ["akhirah", "hidayah"],
    58: ["akhirah"],
    59: ["kibr", "kufr"],
    60: ["akhirah", "kibr", "sidq", "jahannam"],
    61: ["taqwa", "glad_tidings"],
    # 62–75 · The Horn blown twice; the troops driven to Hell and to Paradise
    62: ["tawheed", "tawakkul"],
    63: ["tawheed", "kufr"],
    64: ["shirk", "story_muhammad"],
    65: ["shirk", "warnings", "prophethood"],
    66: ["tawheed", "shukr", "commands"],
    67: ["tawheed", "akhirah", "shirk"],
    68: ["resurrection", "death_reminder", "akhirah"],
    69: ["akhirah", "adl", "prophethood"],
    70: ["akhirah", "adl"],
    71: ["jahannam", "kufr", "prophethood"],
    72: ["jahannam", "kibr"],
    73: ["jannah", "taqwa", "angels"],
    74: ["jannah", "shukr", "dhikr"],
    75: ["angels", "dhikr", "akhirah"],
}
