"""40 · Ghafir · The Forgiver · غافر — 85 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–22 · Forgiver of sin; the angels' dua for the believers
    1: ["muqattaat"],
    2: ["revelation", "asma_ul_husna"],
    3: ["asma_ul_husna", "tawbah", "rahmah", "tawheed"],
    4: ["kufr", "dunya"],
    5: ["history_lessons", "prophethood"],
    6: ["kufr", "jahannam"],
    7: ["angels", "dua", "tawbah", "rahmah"],
    8: ["angels", "dua", "jannah", "family"],
    9: ["angels", "dua", "rahmah"],
    10: ["kufr", "jahannam"],
    11: ["resurrection", "death_reminder", "akhirah"],
    12: ["shirk", "tawheed", "akhirah"],
    13: ["nature_signs", "rizq", "tawbah"],
    14: ["dua", "ikhlas", "commands"],
    15: ["revelation", "akhirah", "asma_ul_husna"],
    16: ["akhirah", "tawheed"],
    17: ["akhirah", "adl"],
    18: ["akhirah", "anxiety_fear", "warnings"],
    19: ["knowledge", "taqwa"],
    20: ["adl", "shirk"],
    21: ["history_lessons"],
    22: ["history_lessons", "prophethood"],
    # 23–54 · Musa, Pharaoh, and the believer from Pharaoh's family
    23: ["story_musa", "miracles"],
    24: ["story_musa", "kufr"],
    25: ["story_musa", "oppression"],
    26: ["story_musa", "oppression"],
    27: ["story_musa", "dua", "kibr"],
    28: ["story_musa", "dawah", "iman", "sidq"],
    29: ["story_musa", "dawah", "leadership"],
    30: ["story_musa", "dawah", "history_lessons"],
    31: ["story_musa", "history_lessons", "adl"],
    32: ["story_musa", "akhirah"],
    33: ["story_musa", "akhirah", "hidayah"],
    34: ["story_yusuf", "story_musa", "history_lessons"],
    35: ["kibr", "tazkiyah", "kufr"],
    36: ["story_musa", "kibr"],
    37: ["story_musa", "kibr", "shirk"],
    38: ["story_musa", "dawah", "hidayah"],
    39: ["story_musa", "dunya", "akhirah"],
    40: ["adl", "women", "iman", "jannah"],
    41: ["story_musa", "dawah"],
    42: ["story_musa", "shirk", "dawah"],
    43: ["story_musa", "shirk", "akhirah"],
    44: ["story_musa", "tawakkul", "tawheed"],
    45: ["story_musa", "tawakkul", "history_lessons"],
    46: ["story_musa", "death_reminder", "jahannam"],
    47: ["jahannam", "leadership"],
    48: ["jahannam", "leadership", "adl"],
    49: ["jahannam", "angels", "dua"],
    50: ["jahannam", "prophethood", "kufr"],
    51: ["prophethood", "iman", "glad_tidings"],
    52: ["akhirah", "oppression"],
    53: ["story_musa", "story_bani_israil", "revelation"],
    54: ["revelation", "hidayah"],
    # 55–68 · "Call upon Me; I will respond"; stages of life
    55: ["sabr", "tawbah", "dhikr", "story_muhammad", "time"],
    56: ["kibr", "dua"],
    57: ["nature_signs", "human_creation"],
    58: ["iman", "kufr", "parables"],
    59: ["akhirah"],
    60: ["dua", "kibr", "glad_tidings", "commands"],  # Uduni astajib lakum
    61: ["nature_signs", "shukr"],
    62: ["tawheed"],
    63: ["kufr"],
    64: ["nature_signs", "human_creation", "rizq"],
    65: ["tawheed", "dua", "ikhlas", "asma_ul_husna"],
    66: ["tawheed", "shirk"],
    67: ["human_creation", "death_reminder", "time"],
    68: ["death_reminder", "qadr"],
    # 69–85 · Disputers dragged in chains; faith too late benefits no one
    69: ["kufr"],
    70: ["kufr", "revelation"],
    71: ["jahannam"],
    72: ["jahannam"],
    73: ["jahannam", "shirk"],
    74: ["shirk", "hidayah"],
    75: ["kibr", "jahannam"],
    76: ["jahannam", "kibr"],
    77: ["sabr", "story_muhammad", "death_reminder"],
    78: ["prophethood", "miracles", "qadr"],
    79: ["animals", "rizq"],
    80: ["animals", "nature_signs"],
    81: ["nature_signs", "kufr"],
    82: ["history_lessons"],
    83: ["history_lessons", "knowledge", "kibr"],
    84: ["tawbah", "history_lessons"],
    85: ["tawbah", "history_lessons", "death_reminder"],
}
