"""41 · Fussilat · Explained in Detail · فصلت — 54 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–12 · A Book explained in detail; the creation of earth and heavens
    1: ["muqattaat"],
    2: ["revelation", "asma_ul_husna", "rahmah"],
    3: ["revelation", "knowledge"],
    4: ["revelation", "glad_tidings", "warnings", "kufr"],
    5: ["kufr", "tazkiyah"],
    6: ["prophethood", "tawheed", "tawbah", "shirk"],
    7: ["zakat", "akhirah", "kufr"],
    8: ["iman", "glad_tidings"],
    9: ["nature_signs", "shirk", "tawheed"],
    10: ["nature_signs", "rizq"],
    11: ["nature_signs"],
    12: ["nature_signs"],
    # 13–29 · 'Ad and Thamud; skins that testify on the Day
    13: ["warnings", "history_lessons"],
    14: ["prophethood", "tawheed", "kufr"],
    15: ["story_hud", "kibr", "history_lessons"],
    16: ["story_hud", "history_lessons", "warnings"],
    17: ["story_salih", "hidayah", "history_lessons"],
    18: ["iman", "taqwa", "rahmah"],
    19: ["akhirah", "jahannam"],
    20: ["akhirah"],
    21: ["akhirah", "resurrection", "qadr"],
    22: ["taqwa", "knowledge"],
    23: ["kufr", "tazkiyah"],
    24: ["jahannam", "sabr"],
    25: ["shaytan", "jinn", "wala_bara", "history_lessons"],
    26: ["kufr", "quran_recitation"],
    27: ["jahannam", "warnings"],
    28: ["jahannam", "kufr"],
    29: ["jahannam", "jinn", "shaytan"],
    # 30–36 · "Our Lord is Allah" and then stood firm; repel evil with what is better
    30: ["iman", "angels", "glad_tidings", "anxiety_fear", "tawakkul"],
    31: ["angels", "jannah", "wala_bara"],
    32: ["jannah", "rahmah"],
    33: ["dawah", "ihsan", "speech_ethics"],
    34: ["hilm", "ihsan", "speech_ethics", "commands"],
    35: ["sabr", "hilm", "glad_tidings"],
    36: ["shaytan", "dua", "commands"],
    # 37–54 · Signs in night, day, sun and moon; signs in the horizons and in themselves
    37: ["nature_signs", "tawheed", "shirk", "commands"],
    38: ["sajdah_tilawah", "angels", "dhikr", "kibr"],
    39: ["nature_signs", "resurrection"],
    40: ["revelation", "kufr", "akhirah"],
    41: ["revelation", "kufr"],
    42: ["revelation"],
    43: ["prophethood", "story_muhammad", "rahmah"],
    44: ["revelation", "hidayah", "health", "kufr"],
    45: ["story_musa", "revelation", "community"],
    46: ["akhirah", "adl"],
    47: ["knowledge", "akhirah", "shirk"],
    48: ["shirk", "akhirah"],
    49: ["dua", "hope_raja", "human_creation"],
    50: ["kufr", "shukr", "akhirah", "dunya"],
    51: ["human_creation", "shukr", "dua"],
    52: ["revelation", "kufr"],
    53: ["nature_signs", "human_creation", "revelation"],
    54: ["akhirah", "kufr", "asma_ul_husna"],
}
