"""42 · Ash-Shuraa · The Consultation · الشورى — 53 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–12 · Revelation as to the prophets before; nothing is like Him
    1: ["muqattaat"],
    2: ["muqattaat"],
    3: ["revelation", "prophethood", "asma_ul_husna"],
    4: ["tawheed", "asma_ul_husna"],
    5: ["angels", "dhikr", "rahmah", "tawbah"],
    6: ["wala_bara", "shirk", "story_muhammad"],
    7: ["revelation", "dawah", "akhirah"],
    8: ["qadr", "community", "rahmah"],
    9: ["wala_bara", "tawheed", "resurrection"],
    10: ["tawheed", "tawakkul", "revelation"],
    11: ["tawheed", "asma_ul_husna", "human_creation", "marriage"],
    12: ["rizq", "qadr", "tawheed"],
    # 13–26 · The one religion enjoined on all prophets; the harvest of the Hereafter
    13: ["revelation", "prophethood", "community", "hidayah"],
    14: ["community", "hasad", "revelation"],
    15: ["dawah", "adl", "revelation", "commands"],
    16: ["kufr", "warnings"],
    17: ["revelation", "adl", "akhirah"],
    18: ["akhirah", "iman", "taqwa"],
    19: ["rizq", "asma_ul_husna"],
    20: ["akhirah", "dunya", "ihsan"],
    21: ["shirk", "revelation"],
    22: ["akhirah", "jannah", "oppression"],
    23: ["glad_tidings", "family", "ihsan", "shukr"],
    24: ["revelation", "sidq", "knowledge"],
    25: ["tawbah", "rahmah", "asma_ul_husna"],
    26: ["dua", "iman", "glad_tidings"],
    # 27–36 · Provision measured out; disasters from our own hands
    27: ["rizq", "qadr", "oppression", "tawheed"],
    28: ["nature_signs", "rahmah", "hope_raja"],
    29: ["nature_signs", "animals", "resurrection"],
    30: ["trial_test", "tawbah", "rahmah", "qadr"],
    31: ["qadr", "wala_bara"],
    32: ["nature_signs"],
    33: ["nature_signs", "sabr", "shukr"],
    34: ["qadr", "rahmah"],
    35: ["kufr", "warnings"],
    36: ["dunya", "akhirah", "tawakkul", "iman"],
    # 37–43 · Their affairs by consultation; pardon and reconciliation
    37: ["prohibitions", "hilm", "haya", "iman"],
    38: ["iman", "salah", "shura", "zakat", "community"],
    39: ["oppression", "adl"],
    40: ["adl", "hilm", "criminal_law", "love_of_allah"],
    41: ["adl", "oppression"],
    42: ["oppression", "criminal_law", "warnings"],
    43: ["sabr", "hilm"],
    # 44–53 · How Allah speaks to man; the straight path
    44: ["hidayah", "akhirah", "oppression"],
    45: ["akhirah", "jahannam", "family"],
    46: ["hidayah", "wala_bara"],
    47: ["akhirah", "tawbah", "commands"],
    48: ["story_muhammad", "dawah", "shukr", "human_creation"],
    49: ["qadr", "parenting", "women", "tawheed"],
    50: ["qadr", "parenting", "human_creation"],
    51: ["revelation", "prophethood", "angels"],
    52: ["revelation", "story_muhammad", "hidayah", "iman"],
    53: ["tawheed", "akhirah"],
}
