"""43 · Az-Zukhruf · The Ornaments of Gold · الزخرف — 89 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–14 · The Mother of the Book; signs in the earth, ships and cattle
    1: ["muqattaat"],
    2: ["oaths", "revelation"],
    3: ["revelation", "knowledge"],
    4: ["revelation", "qadr"],
    5: ["revelation", "rahmah"],
    6: ["prophethood", "history_lessons"],
    7: ["prophethood", "speech_ethics", "kufr"],
    8: ["history_lessons"],
    9: ["tawheed", "nature_signs", "shirk"],
    10: ["nature_signs", "hidayah"],
    11: ["nature_signs", "resurrection"],
    12: ["nature_signs", "animals"],
    13: ["animals", "dhikr", "shukr", "adab"],
    14: ["akhirah", "dhikr"],
    # 15–25 · Daughters ascribed to Allah; blind following of forefathers
    15: ["shirk", "shukr"],
    16: ["shirk", "women", "parenting"],
    17: ["shirk", "women", "grief_loss"],
    18: ["shirk", "women"],
    19: ["shirk", "angels", "women", "knowledge"],
    20: ["shirk", "qadr", "knowledge"],
    21: ["shirk", "revelation"],
    22: ["hidayah", "kufr"],
    23: ["history_lessons", "wealth", "hidayah"],
    24: ["dawah", "hidayah", "kufr"],
    25: ["history_lessons", "warnings"],
    # 26–35 · Ibrahim's word of tawheed; if not for one community, silver houses
    26: ["story_ibrahim", "shirk", "parents", "wala_bara"],
    27: ["story_ibrahim", "tawheed", "hidayah"],
    28: ["story_ibrahim", "tawheed", "family"],
    29: ["dunya", "prophethood"],
    30: ["kufr", "revelation"],
    31: ["kufr", "leadership", "wealth"],
    32: ["rizq", "qadr", "rahmah", "community"],
    33: ["dunya", "wealth", "kufr"],
    34: ["dunya", "wealth"],
    35: ["dunya", "wealth", "akhirah", "taqwa"],
    # 36–45 · A devil appointed as companion; hold to what is revealed
    36: ["shaytan", "dhikr", "wala_bara"],
    37: ["shaytan", "hidayah"],
    38: ["akhirah", "wala_bara"],
    39: ["akhirah", "oppression"],
    40: ["hidayah", "story_muhammad"],
    41: ["warnings", "story_muhammad"],
    42: ["warnings", "qadr"],
    43: ["revelation", "hidayah", "commands"],
    44: ["revelation", "akhirah", "story_muhammad"],
    45: ["prophethood", "tawheed", "shirk"],
    # 46–56 · Musa and Pharaoh's boast over the rivers of Egypt
    46: ["story_musa", "prophethood"],
    47: ["story_musa", "miracles", "speech_ethics"],
    48: ["story_musa", "miracles", "trial_test"],
    49: ["story_musa", "dua", "kufr"],
    50: ["story_musa", "amanah", "kufr"],
    51: ["story_musa", "kibr", "leadership", "dunya"],
    52: ["story_musa", "kibr", "speech_ethics"],
    53: ["story_musa", "kibr", "wealth", "angels"],
    54: ["story_musa", "leadership", "kufr"],
    55: ["story_musa", "history_lessons"],
    56: ["story_musa", "history_lessons", "parables"],
    # 57–73 · Isa as an example; friends become enemies except the righteous
    57: ["story_isa", "kufr", "speech_ethics"],
    58: ["story_isa", "shirk", "knowledge"],
    59: ["story_isa", "prophethood", "story_bani_israil"],
    60: ["angels", "qadr"],
    61: ["story_isa", "akhirah", "hidayah"],
    62: ["shaytan", "hidayah"],
    63: ["story_isa", "knowledge", "taqwa", "dawah"],
    64: ["story_isa", "tawheed", "hidayah"],
    65: ["community", "warnings", "ahl_al_kitab"],
    66: ["akhirah", "warnings"],
    67: ["wala_bara", "taqwa", "akhirah"],
    68: ["jannah", "glad_tidings", "anxiety_fear"],
    69: ["iman", "jannah"],
    70: ["jannah", "family"],
    71: ["jannah"],
    72: ["jannah", "ihsan"],
    73: ["jannah", "rizq"],
    # 74–89 · The people of the Fire call on Malik; say "Peace"
    74: ["jahannam"],
    75: ["jahannam"],
    76: ["jahannam", "adl"],
    77: ["jahannam", "angels", "dua"],
    78: ["revelation", "kufr"],
    79: ["qadr", "kufr"],
    80: ["knowledge", "angels", "taqwa"],
    81: ["shirk", "tawheed", "story_muhammad"],
    82: ["tawheed", "shirk", "dhikr"],
    83: ["warnings", "dunya"],
    84: ["tawheed", "asma_ul_husna"],
    85: ["tawheed", "akhirah", "knowledge"],
    86: ["shirk", "akhirah", "knowledge"],
    87: ["tawheed", "shirk", "hidayah"],
    88: ["story_muhammad", "dua", "kufr"],
    89: ["hilm", "speech_ethics", "story_muhammad", "warnings"],
}
