"""44 · Ad-Dukhan · The Smoke · الدخان — 59 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–16 · The blessed night; the smoke and the great assault
    1: ["muqattaat"],
    2: ["oaths", "revelation"],
    3: ["revelation", "time", "dawah"],
    4: ["qadr", "time"],
    5: ["qadr", "revelation"],
    6: ["rahmah", "prophethood"],
    7: ["tawheed", "nature_signs"],
    8: ["tawheed", "death_reminder"],
    9: ["kufr", "dunya"],
    10: ["akhirah", "warnings"],
    11: ["warnings", "akhirah"],
    12: ["dua", "warnings", "iman"],
    13: ["prophethood", "kufr"],
    14: ["kufr", "speech_ethics", "story_muhammad"],
    15: ["warnings", "kufr"],
    16: ["akhirah", "warnings"],
    # 17–37 · Musa and Pharaoh; what they left behind
    17: ["story_musa", "trial_test", "prophethood"],
    18: ["story_musa", "amanah", "story_bani_israil"],
    19: ["story_musa", "kibr", "miracles"],
    20: ["story_musa", "dua", "tawakkul"],
    21: ["story_musa", "dawah"],
    22: ["story_musa", "dua"],
    23: ["story_musa", "story_bani_israil", "qadr"],
    24: ["story_musa", "miracles", "history_lessons"],
    25: ["history_lessons", "dunya"],
    26: ["history_lessons", "dunya"],
    27: ["history_lessons", "dunya"],
    28: ["history_lessons", "qadr"],
    29: ["history_lessons", "kufr"],
    30: ["story_bani_israil", "oppression", "rahmah"],
    31: ["story_musa", "kibr", "oppression"],
    32: ["story_bani_israil", "knowledge"],
    33: ["story_bani_israil", "miracles", "trial_test"],
    34: ["kufr", "resurrection"],
    35: ["resurrection", "kufr"],
    36: ["resurrection", "kufr"],
    37: ["history_lessons", "warnings"],
    # 38–59 · Creation is not play; the tree of zaqqum and the secure place
    38: ["purpose_of_life", "nature_signs"],
    39: ["purpose_of_life", "knowledge"],
    40: ["akhirah"],
    41: ["akhirah", "family"],
    42: ["akhirah", "rahmah"],
    43: ["jahannam"],
    44: ["jahannam"],
    45: ["jahannam"],
    46: ["jahannam"],
    47: ["jahannam"],
    48: ["jahannam"],
    49: ["jahannam", "kibr"],
    50: ["jahannam", "kufr"],
    51: ["jannah", "taqwa"],
    52: ["jannah"],
    53: ["jannah"],
    54: ["jannah", "marriage"],
    55: ["jannah", "rizq"],
    56: ["jannah", "death_reminder"],
    57: ["jannah", "rahmah", "glad_tidings"],
    58: ["revelation", "quran_recitation"],
    59: ["story_muhammad", "sabr", "warnings"],
}
