"""50 · Qaf · The Letter "Qaf" · ق — 45 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–15 · Denial of resurrection answered by the signs of creation
    1: ["muqattaat", "oaths", "revelation"],
    2: ["resurrection", "kufr", "prophethood"],
    3: ["resurrection", "kufr"],
    4: ["resurrection", "knowledge", "qadr"],
    5: ["kufr"],
    6: ["nature_signs"],
    7: ["nature_signs"],
    8: ["nature_signs", "tawbah"],
    9: ["nature_signs", "rizq"],
    10: ["nature_signs", "rizq"],
    11: ["nature_signs", "resurrection", "rizq"],
    12: ["history_lessons"],
    13: ["history_lessons"],
    14: ["history_lessons", "prophethood", "warnings"],
    15: ["resurrection", "human_creation"],
    # 16–35 · Closer than the jugular vein; the two recorders; Hell and Paradise
    16: ["human_creation", "knowledge", "tazkiyah", "asma_ul_husna"],
    17: ["angels", "akhirah"],
    18: ["angels", "speech_ethics", "taqwa"],
    19: ["death_reminder"],
    20: ["resurrection", "akhirah"],
    21: ["akhirah", "angels"],
    22: ["akhirah", "dunya"],
    23: ["akhirah", "angels"],
    24: ["jahannam", "kufr"],
    25: ["jahannam", "kufr"],
    26: ["shirk", "jahannam"],
    27: ["shaytan", "akhirah"],
    28: ["akhirah", "warnings"],
    29: ["adl", "qadr"],
    30: ["jahannam"],
    31: ["jannah", "taqwa"],
    32: ["jannah", "tawbah", "amanah"],
    33: ["jannah", "taqwa", "tawbah", "tazkiyah"],
    34: ["jannah", "anxiety_fear"],
    35: ["jannah", "rahmah"],
    # 36–45 · Be patient and glorify Him; the Day of Emergence
    36: ["history_lessons", "warnings"],
    37: ["tazkiyah", "knowledge", "quran_recitation"],
    38: ["nature_signs", "tawheed"],
    39: ["sabr", "dhikr", "salah", "time", "commands"],
    40: ["dhikr", "salah", "time"],
    41: ["resurrection", "akhirah"],
    42: ["resurrection", "akhirah"],
    43: ["death_reminder", "resurrection", "tawheed"],
    44: ["resurrection", "akhirah"],
    45: ["quran_recitation", "dawah", "story_muhammad", "commands"],
}
