"""51 · Adh-Dhariyat · The Winnowing Winds · الذاريات — 60 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–23 · Oaths by the winds; the night prayer and the right of the needy
    1: ["oaths", "nature_signs"],
    2: ["oaths", "nature_signs"],
    3: ["oaths", "nature_signs"],
    4: ["oaths", "angels"],
    5: ["akhirah", "resurrection"],
    6: ["akhirah"],
    7: ["oaths", "nature_signs"],
    8: ["kufr", "community"],
    9: ["hidayah", "kufr"],
    10: ["sidq", "warnings"],
    11: ["dunya", "kufr"],
    12: ["akhirah", "kufr"],
    13: ["jahannam"],
    14: ["jahannam"],
    15: ["jannah", "taqwa"],
    16: ["jannah", "ihsan"],
    17: ["salah", "ihsan", "time"],
    18: ["tawbah", "dhikr", "time"],
    19: ["zakat", "social_justice"],
    20: ["nature_signs", "iman"],
    21: ["human_creation", "nature_signs", "knowledge"],
    22: ["rizq", "nature_signs", "qadr"],
    23: ["oaths", "akhirah", "sidq"],
    # 24–37 · The honoured guests of Ibrahim and the people of Lut
    24: ["story_ibrahim", "angels", "adab"],
    25: ["story_ibrahim", "angels", "adab"],
    26: ["story_ibrahim", "adab", "ihsan"],
    27: ["story_ibrahim", "adab"],
    28: ["story_ibrahim", "story_ishaq", "anxiety_fear", "glad_tidings"],
    29: ["story_ishaq", "women", "miracles"],
    30: ["story_ishaq", "qadr", "asma_ul_husna"],
    31: ["story_ibrahim", "angels"],
    32: ["story_lut", "angels"],
    33: ["story_lut", "history_lessons"],
    34: ["story_lut", "history_lessons"],
    35: ["story_lut", "iman", "rahmah"],
    36: ["story_lut", "iman"],
    37: ["story_lut", "history_lessons", "taqwa"],
    # 38–46 · Signs in Musa, 'Ad, Thamud and the people of Nuh
    38: ["story_musa", "miracles"],
    39: ["story_musa", "kibr", "kufr"],
    40: ["story_musa", "history_lessons"],
    41: ["story_hud", "history_lessons"],
    42: ["story_hud", "history_lessons"],
    43: ["story_salih", "history_lessons"],
    44: ["story_salih", "kibr", "history_lessons"],
    45: ["story_salih", "history_lessons"],
    46: ["story_nuh", "history_lessons", "kufr"],
    # 47–60 · Flee to Allah; created only to worship Him
    47: ["nature_signs", "qadr"],
    48: ["nature_signs"],
    49: ["nature_signs", "human_creation", "knowledge"],
    50: ["dawah", "tawbah", "commands", "warnings"],
    51: ["shirk", "tawheed", "prohibitions", "warnings"],
    52: ["prophethood", "kufr", "speech_ethics"],
    53: ["kufr", "oppression"],
    54: ["story_muhammad", "dawah"],
    55: ["dawah", "iman", "commands"],
    56: ["purpose_of_life", "tawheed", "jinn"],
    57: ["rizq", "tawheed"],
    58: ["rizq", "asma_ul_husna", "tawakkul"],
    59: ["oppression", "warnings", "history_lessons"],
    60: ["kufr", "akhirah", "warnings"],
}
