"""52 · At-Tur · The Mount · الطور — 49 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–16 · Oaths by the Mount and the frequented House; the Day of the Fire
    1: ["oaths", "nature_signs"],
    2: ["oaths", "revelation"],
    3: ["oaths", "revelation"],
    4: ["oaths", "kaaba", "angels"],
    5: ["oaths", "nature_signs"],
    6: ["oaths", "nature_signs"],
    7: ["akhirah", "warnings"],
    8: ["akhirah", "qadr"],
    9: ["akhirah", "nature_signs"],
    10: ["akhirah", "nature_signs"],
    11: ["warnings", "kufr"],
    12: ["dunya", "kufr"],
    13: ["jahannam", "angels"],
    14: ["jahannam", "kufr"],
    15: ["jahannam", "kufr"],
    16: ["jahannam", "adl", "sabr"],
    # 17–28 · The righteous in gardens, joined by their offspring
    17: ["jannah", "taqwa"],
    18: ["jannah", "rahmah"],
    19: ["jannah", "ihsan"],
    20: ["jannah", "marriage"],
    21: ["jannah", "family", "adl"],
    22: ["jannah", "rizq"],
    23: ["jannah", "speech_ethics"],
    24: ["jannah"],
    25: ["jannah"],
    26: ["jannah", "taqwa", "family"],
    27: ["jannah", "rahmah"],
    28: ["dua", "rahmah", "asma_ul_husna"],
    # 29–49 · "Or…?" — every excuse of the deniers answered
    29: ["story_muhammad", "dawah", "revelation"],
    30: ["story_muhammad", "speech_ethics", "kufr"],
    31: ["warnings"],
    32: ["kufr", "knowledge"],
    33: ["revelation", "kufr"],
    34: ["revelation", "kufr"],
    35: ["human_creation", "tawheed", "kufr"],
    36: ["nature_signs", "tawheed", "kufr"],
    37: ["rizq", "tawheed"],
    38: ["kufr", "knowledge"],
    39: ["shirk", "women"],
    40: ["ikhlas", "dawah"],
    41: ["knowledge", "kufr"],
    42: ["qadr", "kufr"],
    43: ["tawheed", "shirk"],
    44: ["kufr", "nature_signs"],
    45: ["akhirah", "warnings"],
    46: ["akhirah", "qadr"],
    47: ["warnings", "oppression"],
    48: ["sabr", "dhikr", "story_muhammad", "commands"],
    49: ["dhikr", "salah", "time"],
}
