"""53 · An-Najm · The Star · النجم — 62 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–18 · He does not speak from desire; the vision at the Lote Tree
    1: ["oaths", "nature_signs"],
    2: ["story_muhammad", "revelation", "hidayah"],
    3: ["revelation", "story_muhammad"],
    4: ["revelation"],
    5: ["revelation", "angels"],
    6: ["angels", "isra_miraj"],
    7: ["angels", "isra_miraj"],
    8: ["angels", "isra_miraj"],
    9: ["angels", "isra_miraj"],
    10: ["revelation", "isra_miraj"],
    11: ["isra_miraj", "story_muhammad", "sidq"],
    12: ["isra_miraj", "kufr"],
    13: ["isra_miraj", "angels"],
    14: ["isra_miraj", "jannah"],
    15: ["isra_miraj", "jannah"],
    16: ["isra_miraj"],
    17: ["isra_miraj", "story_muhammad", "adab"],
    18: ["isra_miraj", "miracles"],
    # 19–32 · Al-Lat, al-'Uzza and Manat; do not claim purity for yourselves
    19: ["shirk"],
    20: ["shirk"],
    21: ["shirk", "women"],
    22: ["shirk", "adl"],
    23: ["shirk", "knowledge", "tazkiyah", "hidayah"],
    24: ["dunya", "qadr"],
    25: ["akhirah", "tawheed"],
    26: ["angels", "akhirah", "shirk"],
    27: ["shirk", "angels", "women", "akhirah"],
    28: ["knowledge", "shirk"],
    29: ["dunya", "dhikr", "wala_bara"],
    30: ["dunya", "knowledge", "hidayah"],
    31: ["akhirah", "adl", "ihsan"],
    32: ["prohibitions", "haya", "rahmah", "tazkiyah", "human_creation", "ikhlas"],
    # 33–62 · The scriptures of Musa and Ibrahim; so prostrate to Allah
    33: ["kufr", "wealth"],
    34: ["wealth", "zakat", "kufr"],
    35: ["knowledge", "kufr"],
    36: ["story_musa", "revelation"],
    37: ["story_ibrahim", "amanah", "revelation"],
    38: ["akhirah", "adl"],
    39: ["akhirah", "work_ethics", "adl"],
    40: ["akhirah", "adl"],
    41: ["akhirah", "adl"],
    42: ["akhirah", "tawheed"],
    43: ["qadr", "human_creation"],
    44: ["death_reminder", "resurrection", "qadr"],
    45: ["human_creation", "qadr"],
    46: ["human_creation"],
    47: ["resurrection", "qadr"],
    48: ["rizq", "wealth", "qadr"],
    49: ["nature_signs", "tawheed"],
    50: ["story_hud", "history_lessons"],
    51: ["story_salih", "history_lessons"],
    52: ["story_nuh", "history_lessons", "oppression"],
    53: ["story_lut", "history_lessons"],
    54: ["story_lut", "history_lessons"],
    55: ["shukr", "nature_signs"],
    56: ["prophethood", "story_muhammad", "dawah"],
    57: ["akhirah", "warnings"],
    58: ["akhirah", "tawheed"],
    59: ["kufr", "quran_recitation"],
    60: ["kufr", "dunya", "warnings"],
    61: ["kufr", "dunya", "kibr"],
    62: ["sajdah_tilawah", "salah", "tawheed", "commands"],
}
