"""55 · Ar-Rahman · The Beneficent · الرحمن — 78 ayaat (medinan)"""

STATUS = "deep"

# The refrain "So which of the favours of your Lord would you deny?" is tagged shukr + rahmah.

TAGS = {
    # 1–13 · The Most Merciful taught the Quran; the balance
    1: ["asma_ul_husna", "rahmah"],
    2: ["revelation", "rahmah"],
    3: ["human_creation"],
    4: ["human_creation", "speech_ethics", "knowledge"],
    5: ["nature_signs", "time"],
    6: ["nature_signs", "dhikr"],
    7: ["nature_signs", "adl"],
    8: ["adl", "trade"],
    9: ["adl", "trade", "commands"],
    10: ["nature_signs", "rizq"],
    11: ["nature_signs", "rizq"],
    12: ["nature_signs", "rizq"],
    13: ["shukr", "rahmah"],
    # 14–25 · Man and jinn; the two seas
    14: ["human_creation"],
    15: ["jinn"],
    16: ["shukr", "rahmah"],
    17: ["nature_signs"],
    18: ["shukr", "rahmah"],
    19: ["nature_signs"],
    20: ["nature_signs"],
    21: ["shukr", "rahmah"],
    22: ["nature_signs", "rizq"],
    23: ["shukr", "rahmah"],
    24: ["nature_signs"],
    25: ["shukr", "rahmah"],
    # 26–36 · All will perish but His Face; O company of jinn and mankind
    26: ["death_reminder", "dunya"],
    27: ["tawheed", "asma_ul_husna", "death_reminder"],
    28: ["shukr", "rahmah"],
    29: ["tawheed", "dua", "qadr"],
    30: ["shukr", "rahmah"],
    31: ["akhirah", "jinn"],
    32: ["shukr", "rahmah"],
    33: ["jinn", "akhirah", "qadr"],
    34: ["shukr", "rahmah"],
    35: ["jahannam", "jinn"],
    36: ["shukr", "rahmah"],
    # 37–45 · The Day the heaven splits; the criminals seized
    37: ["akhirah", "nature_signs"],
    38: ["shukr", "rahmah"],
    39: ["akhirah", "jinn"],
    40: ["shukr", "rahmah"],
    41: ["akhirah", "jahannam"],
    42: ["shukr", "rahmah"],
    43: ["jahannam", "kufr"],
    44: ["jahannam"],
    45: ["shukr", "rahmah"],
    # 46–61 · Two gardens for whoever feared the station of his Lord
    46: ["jannah", "taqwa"],
    47: ["shukr", "rahmah"],
    48: ["jannah"],
    49: ["shukr", "rahmah"],
    50: ["jannah"],
    51: ["shukr", "rahmah"],
    52: ["jannah"],
    53: ["shukr", "rahmah"],
    54: ["jannah"],
    55: ["shukr", "rahmah"],
    56: ["jannah", "haya"],
    57: ["shukr", "rahmah"],
    58: ["jannah"],
    59: ["shukr", "rahmah"],
    60: ["jannah", "ihsan"],
    61: ["shukr", "rahmah"],
    # 62–78 · And below them two other gardens; blessed is the name of your Lord
    62: ["jannah"],
    63: ["shukr", "rahmah"],
    64: ["jannah"],
    65: ["shukr", "rahmah"],
    66: ["jannah"],
    67: ["shukr", "rahmah"],
    68: ["jannah", "rizq"],
    69: ["shukr", "rahmah"],
    70: ["jannah"],
    71: ["shukr", "rahmah"],
    72: ["jannah"],
    73: ["shukr", "rahmah"],
    74: ["jannah", "haya"],
    75: ["shukr", "rahmah"],
    76: ["jannah"],
    77: ["shukr", "rahmah"],
    78: ["dhikr", "asma_ul_husna", "tawheed"],
}
