"""56 · Al-Waqi'ah · The Inevitable · الواقعة — 96 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · The Occurrence; mankind sorted into three kinds
    1: ["akhirah"],
    2: ["akhirah", "sidq"],
    3: ["akhirah"],
    4: ["akhirah", "nature_signs"],
    5: ["akhirah", "nature_signs"],
    6: ["akhirah"],
    7: ["akhirah"],
    8: ["akhirah", "jannah"],
    9: ["akhirah", "jahannam"],
    10: ["akhirah", "ihsan", "glad_tidings"],
    # 11–40 · The forerunners and the companions of the right in the Gardens
    11: ["jannah", "ihsan"],
    12: ["jannah"],
    13: ["jannah"],
    14: ["jannah"],
    15: ["jannah"],
    16: ["jannah"],
    17: ["jannah"],
    18: ["jannah"],
    19: ["jannah", "food_halal"],
    20: ["jannah", "rizq"],
    21: ["jannah", "rizq"],
    22: ["jannah"],
    23: ["jannah"],
    24: ["jannah", "adl"],
    25: ["jannah", "speech_ethics"],
    26: ["jannah"],
    27: ["jannah"],
    28: ["jannah"],
    29: ["jannah"],
    30: ["jannah"],
    31: ["jannah"],
    32: ["jannah", "rizq"],
    33: ["jannah", "rizq"],
    34: ["jannah"],
    35: ["jannah", "women", "human_creation"],
    36: ["jannah", "women"],
    37: ["jannah", "women", "marriage"],
    38: ["jannah"],
    39: ["jannah"],
    40: ["jannah"],
    # 41–56 · The companions of the left and the tree of zaqqum
    41: ["jahannam"],
    42: ["jahannam"],
    43: ["jahannam"],
    44: ["jahannam"],
    45: ["jahannam", "dunya", "wealth"],
    46: ["jahannam", "shirk", "kufr"],
    47: ["resurrection", "kufr"],
    48: ["resurrection", "kufr"],
    49: ["akhirah", "resurrection"],
    50: ["akhirah", "qadr"],
    51: ["jahannam", "hidayah"],
    52: ["jahannam"],
    53: ["jahannam"],
    54: ["jahannam"],
    55: ["jahannam"],
    56: ["jahannam", "akhirah"],
    # 57–74 · Who creates the seed, the water and the fire?
    57: ["human_creation", "resurrection", "iman"],
    58: ["human_creation"],
    59: ["human_creation", "tawheed"],
    60: ["death_reminder", "qadr"],
    61: ["resurrection", "qadr", "human_creation"],
    62: ["resurrection", "human_creation", "knowledge"],
    63: ["nature_signs", "rizq"],
    64: ["nature_signs", "tawheed", "rizq"],
    65: ["nature_signs", "qadr", "shukr"],
    66: ["nature_signs", "wealth"],
    67: ["nature_signs", "rizq"],
    68: ["nature_signs", "rizq"],
    69: ["nature_signs", "tawheed"],
    70: ["nature_signs", "shukr", "qadr"],
    71: ["nature_signs"],
    72: ["nature_signs", "tawheed"],
    73: ["nature_signs", "rizq", "dhikr"],
    74: ["dhikr", "asma_ul_husna", "commands"],
    # 75–96 · A noble Quran in a protected Register; the soul at the throat
    75: ["oaths", "nature_signs"],
    76: ["oaths", "revelation"],
    77: ["revelation", "quran_recitation"],
    78: ["revelation", "angels"],
    79: ["quran_recitation", "taharah", "revelation"],
    80: ["revelation", "tawheed"],
    81: ["kufr", "revelation"],
    82: ["shukr", "rizq", "kufr"],
    83: ["death_reminder"],
    84: ["death_reminder"],
    85: ["death_reminder", "angels"],
    86: ["death_reminder", "akhirah"],
    87: ["death_reminder", "qadr", "sidq"],
    88: ["death_reminder", "jannah", "ihsan"],
    89: ["jannah", "glad_tidings"],
    90: ["death_reminder", "jannah"],
    91: ["jannah", "angels", "glad_tidings"],
    92: ["death_reminder", "kufr", "hidayah"],
    93: ["jahannam"],
    94: ["jahannam"],
    95: ["sidq", "akhirah", "iman"],
    96: ["dhikr", "asma_ul_husna", "commands"],
}
