"""68 · Al-Qalam · The Pen · القلم — 52 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–16 · By the pen; a great moral character; the traits not to obey
    1: ["muqattaat", "oaths", "knowledge"],
    2: ["story_muhammad", "revelation"],
    3: ["story_muhammad", "glad_tidings"],
    4: ["story_muhammad", "ihsan", "adab"],
    5: ["kufr", "story_muhammad"],
    6: ["kufr"],
    7: ["hidayah", "knowledge"],
    8: ["kufr", "prohibitions", "commands"],
    9: ["kufr", "amanah", "sidq"],
    10: ["speech_ethics", "amanah", "prohibitions"],
    11: ["speech_ethics", "prohibitions"],
    12: ["zakat", "oppression", "prohibitions"],
    13: ["kibr", "prohibitions"],
    14: ["wealth", "parenting", "kibr"],
    15: ["kufr", "revelation", "kibr"],
    16: ["warnings", "kibr"],
    # 17–33 · The owners of the garden who excluded the poor
    17: ["parables", "trial_test", "wealth"],
    18: ["parables", "qadr", "adab"],
    19: ["parables", "qadr", "history_lessons"],
    20: ["parables", "history_lessons"],
    21: ["parables"],
    22: ["parables", "wealth"],
    23: ["parables"],
    24: ["parables", "social_justice", "wealth"],
    25: ["parables", "kibr"],
    26: ["parables", "history_lessons"],
    27: ["parables", "wealth"],
    28: ["parables", "dhikr", "shukr"],
    29: ["parables", "dhikr", "tawbah"],
    30: ["parables", "community"],
    31: ["parables", "tawbah", "oppression"],
    32: ["parables", "hope_raja", "tawbah"],
    33: ["akhirah", "warnings", "dunya"],
    # 34–52 · The Day the shin is uncovered; be not like the companion of the fish
    34: ["jannah", "taqwa"],
    35: ["adl", "iman"],
    36: ["adl", "knowledge"],
    37: ["revelation", "knowledge"],
    38: ["kufr", "akhirah"],
    39: ["amanah", "akhirah", "kufr"],
    40: ["kufr"],
    41: ["shirk", "sidq"],
    42: ["akhirah", "salah", "kibr"],
    43: ["akhirah", "salah", "kibr"],
    44: ["kufr", "revelation", "warnings"],
    45: ["qadr", "warnings"],
    46: ["ikhlas", "dawah"],
    47: ["knowledge", "kufr"],
    48: ["sabr", "story_yunus", "story_muhammad", "commands"],
    49: ["story_yunus", "rahmah", "dua"],
    50: ["story_yunus", "hidayah", "prophethood"],
    51: ["hasad", "kufr", "story_muhammad", "quran_recitation"],
    52: ["revelation", "dhikr"],
}
