"""69 · Al-Haqqah · The Reality · الحاقة — 52 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–12 · The Inevitable Reality and the nations that denied it
    1: ["akhirah"],
    2: ["akhirah"],
    3: ["akhirah"],
    4: ["story_salih", "story_hud", "akhirah", "kufr"],
    5: ["story_salih", "history_lessons"],
    6: ["story_hud", "history_lessons"],
    7: ["story_hud", "history_lessons", "nature_signs"],
    8: ["story_hud", "history_lessons"],
    9: ["story_musa", "story_lut", "history_lessons", "kufr"],
    10: ["prophethood", "history_lessons", "warnings"],
    11: ["story_nuh", "history_lessons", "rahmah"],
    12: ["story_nuh", "dhikr", "knowledge"],
    # 13–37 · The Horn, the Throne, and the two records
    13: ["akhirah", "resurrection"],
    14: ["akhirah", "nature_signs"],
    15: ["akhirah", "resurrection"],
    16: ["akhirah", "nature_signs"],
    17: ["akhirah", "angels"],
    18: ["akhirah", "knowledge"],
    19: ["akhirah", "glad_tidings", "jannah"],
    20: ["akhirah", "iman"],
    21: ["jannah"],
    22: ["jannah"],
    23: ["jannah"],
    24: ["jannah", "ihsan", "sabr"],
    25: ["akhirah", "jahannam"],
    26: ["akhirah", "kufr"],
    27: ["death_reminder", "akhirah"],
    28: ["wealth", "dunya", "akhirah"],
    29: ["akhirah", "leadership", "dunya"],
    30: ["jahannam"],
    31: ["jahannam"],
    32: ["jahannam"],
    33: ["jahannam", "iman", "kufr"],
    34: ["jahannam", "social_justice", "zakat"],
    35: ["jahannam", "wala_bara"],
    36: ["jahannam"],
    37: ["jahannam", "kufr"],
    # 38–52 · The Quran is the word of a noble Messenger, not of a poet
    38: ["oaths", "nature_signs"],
    39: ["oaths"],
    40: ["revelation", "prophethood"],
    41: ["revelation", "speech_ethics", "kufr"],
    42: ["revelation", "kufr"],
    43: ["revelation"],
    44: ["revelation", "sidq", "story_muhammad"],
    45: ["revelation", "warnings"],
    46: ["revelation", "warnings"],
    47: ["revelation", "qadr"],
    48: ["revelation", "taqwa", "dhikr"],
    49: ["kufr", "knowledge"],
    50: ["kufr", "akhirah"],
    51: ["revelation", "sidq", "iman"],
    52: ["dhikr", "asma_ul_husna", "commands"],
}
