"""74 · Al-Muddaththir · The Cloaked One · المدثر — 56 ayaat (meccan)"""

STATUS = "deep"

TAGS = {
    # 1–10 · Arise and warn; purify your garments
    1: ["story_muhammad", "dawah"],
    2: ["dawah", "commands", "story_muhammad"],
    3: ["dhikr", "tawheed", "commands"],
    4: ["taharah", "haya", "commands"],
    5: ["taharah", "prohibitions", "tazkiyah"],
    6: ["ikhlas", "zakat", "prohibitions"],
    7: ["sabr", "commands"],
    8: ["akhirah", "resurrection"],
    9: ["akhirah"],
    10: ["akhirah", "kufr"],
    # 11–31 · The man who deliberated, and Saqar with nineteen keepers
    11: ["kufr", "human_creation"],
    12: ["wealth", "kufr"],
    13: ["parenting", "wealth"],
    14: ["dunya", "wealth"],
    15: ["kibr", "shukr"],
    16: ["kufr", "kibr"],
    17: ["jahannam", "warnings"],
    18: ["kufr", "revelation"],
    19: ["kufr", "warnings"],
    20: ["kufr", "warnings"],
    21: ["kufr"],
    22: ["kibr", "kufr"],
    23: ["kibr", "kufr"],
    24: ["kufr", "revelation"],
    25: ["kufr", "revelation"],
    26: ["jahannam"],
    27: ["jahannam"],
    28: ["jahannam"],
    29: ["jahannam"],
    30: ["jahannam", "angels"],
    31: ["jahannam", "angels", "iman", "nifaq", "trial_test", "hidayah"],
    # 32–56 · What put you into Saqar? — prayer, feeding the poor, idle talk, the Day
    32: ["oaths", "nature_signs"],
    33: ["oaths", "nature_signs", "time"],
    34: ["oaths", "nature_signs", "time"],
    35: ["jahannam", "warnings"],
    36: ["warnings", "dawah"],
    37: ["hidayah", "akhirah"],
    38: ["akhirah", "adl"],
    39: ["jannah", "akhirah"],
    40: ["jannah"],
    41: ["jannah", "jahannam"],
    42: ["jahannam", "akhirah"],
    43: ["salah", "jahannam"],
    44: ["social_justice", "zakat", "jahannam"],
    45: ["speech_ethics", "dunya", "jahannam"],
    46: ["akhirah", "kufr"],
    47: ["death_reminder", "kufr"],
    48: ["akhirah", "shirk"],
    49: ["kufr", "dhikr", "revelation"],
    50: ["parables", "kufr", "animals"],
    51: ["parables", "kufr", "animals"],
    52: ["kufr", "revelation", "kibr"],
    53: ["akhirah", "kufr"],
    54: ["revelation", "dhikr"],
    55: ["hidayah", "dhikr"],
    56: ["qadr", "taqwa", "rahmah"],
}
